### ISSUE TITLE
No version 3.0.0-alpha02 in maven repositories.

### ISSUE THREAD

**Issue by DTHeaven** [square/wire#1007]
Only 3.0.0-alpha01 can be found, no 3.0.0-alpha02.

**Comment by Egorand** [comment]
We're still working on releasing 3.0.0-alpha02, it's blocked by an issue with one of the Gradle plugins we use. Apologies for the miscommunication.

**Comment by DTHeaven** [comment]
> We're still working on releasing 3.0.0-alpha02, it's blocked by an issue with one of the Gradle plugins we use. Apologies for the miscommunication.

Thanks for your working at first.
Is there any other problems if I only use runtime and compiler?

**Comment by Egorand** [comment]
Sure, you can self-publish current master while we're figuring out the release.

**Comment by Blisse** [comment]
Anything we can help with to get the alpha 2 out?

**Comment by jrodbx** [comment]
alpha03 has been published.  Should appear on Maven Central shortly.
