### ISSUE TITLE
Should I use WireEnum?

### ISSUE THREAD

**Issue by lymxit** [square/wire#1046]
If I have a enum Type:
`enum FeedType{
    IMAGE = 0;
    VIDEO = 1;
}`
then wire-compiler will generate FeedType.java: 

```
public enum FeedType implements WireEnum { 
  IMAGE(0),
  VIDEO(1);
  public static final ProtoAdapter<FeedType> ADAPTER = new ProtoAdapter_FeedType();

  private final int value;

  FeedType(int value) {
    this.value = value;
  }

  public static FeedType fromValue(int value) {
    switch (value) {
      case 0: return IMAGE;
      case 1: return VIDEO;
      default: return null;
    }
  }

 private static final class ProtoAdapter_FeedType extends EnumAdapter<FeedType> {
    ProtoAdapter_FeedType() {
      super(FeedType.class);
    }

    @Override
    protected FeedType fromValue(int value) {
      return FeedType.fromValue(value);
    }
  }
}
```
but if some day server add one enum type:
`enum FeedType{
    IMAGE = 0;
    VIDEO = 1;
    VR = 2;
}`

we have two classes ,and our code just use BusinessModel.
```
public class PbModel{
  private final FeedType feed_type;
}

public class BusinessModel{
  private int feedType;
 ... init ...
feedType = pbModel.feed_type == null? 0 : pbModel.feed_type.getValue();
 ...
}
```
if server response get FeedType is VR(2),old client code will BusinessModel.feedType convert to IMAGE(0).

**I want to know if there is a way to not use WireEnum** , because Enum also will be added in mainDex.
![image](https://user-images.githubusercontent.com/16099259/60441626-f8123800-9c49-11e9-9056-37e74dbc976e.png)

**Comment by lymxit** [comment]
Is there any compiler options to generate int instead of wireEnum?

**Comment by lymxit** [comment]
In JavaGenerator#fieldType:
```
private TypeName fieldType(Field field) {
    ProtoType type = field.type();
    // add start
    if (isEnum(field.type())){
      field.setType(ProtoType.INT32);
      type = ProtoType.INT32;
    }
    // add end
    if (type.isMap()) {
      return ParameterizedTypeName.get(ClassName.get(Map.class),
          typeName(type.keyType()),
          typeName(type.valueType()));
    }
    TypeName messageType = typeName(type);
    return field.isRepeated() ? listOf(messageType) : messageType;
  }
```
and in JavaGenerator#generateMessage:
```
    for (Field field : type.fieldsAndOneOfFields()) {
      TypeName fieldJavaType = fieldType(field);
      // ignore default Field
//      if ((field.type().isScalar() || isEnum(field.type()))
//          && !field.isRepeated()
//          && !field.isPacked()) {
//        builder.addField(defaultField(nameAllocator, field, fieldJavaType));
//      }
```
then you will get int instead of wireEnum

**Comment by Egorand** [comment]
> if server response get FeedType is VR(2),old client code will BusinessModel.feedType convert to IMAGE(0).

This is the expected behavior for Protobuf enums. The recommended approach is to make the first enum value special:

```proto
enum FeedType { 
  UNKNOWN = 0;
  IMAGE = 1; 
  VIDEO = 2; 
}
```

The clients should be able to handle the `UNKNOWN` value properly.

> I want to know if there is a way to not use WireEnum , because Enum also will be added in mainDex.

If you don't want the generated code to contain `WireEnum`s you should model your protos differently to avoid `enum`s.

> Is there any compiler options to generate int instead of wireEnum?

No.
