### ISSUE TITLE
Incompatible with gradle 5.3.1.

### ISSUE THREAD

**Issue by DTHeaven** [square/wire#1057]
> Unable to find a matching variant of com.squareup.wire:wire-runtime-metadata:3.0.0-alpha03:
          - Variant 'metadata-api' capability com.squareup.wire:wire-runtime-metadata:3.0.0-alpha03:
              - Required com.android.build.api.attributes.BuildTypeAttr 'debug' but no value provided.
              - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' but no value provided.
              - Found org.gradle.status 'release' but wasn't required.
              - Required org.gradle.usage 'java-runtime' and found incompatible value 'kotlin-api'.
              - Required org.jetbrains.kotlin.platform.type 'androidJvm' and found incompatible value 'common'.

**Comment by Egorand** [comment]
Can you share your Gradle config please? There's not enough data to figure out what the issue is.

**Comment by DTHeaven** [comment]
Changed 'com.squareup.wire:wire-runtime-metadata:3.0.0-alpha03' to 'com.squareup.wire:wire-runtime:3.0.0-alpha03', it works.

Bug there is another problem:
      override fun decode(reader: ProtoReader): CreateHashTagResponse {
        var base_resp: BaseResponse? = null
        var tag: HashTag? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> base_resp = BaseResponse.ADAPTER.decode(reader)
            2 -> tag = HashTag.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return CreateHashTagResponse(
          base_resp = base_resp,
          tag = tag,
          unknownFields = unknownFields
        )
      } 


"reader.forEachTag { tag ->" conflict with " var tag: HashTag? = null".
Maybe change "reader.forEachTag { tag ->" to "reader.forEachTag { it ->" is better.

**Comment by DTHeaven** [comment]
Okio 2.3.0-SNAPSHOT is incompatible with Kotlin 1.3.41, where can I get it's code?

**Comment by Egorand** [comment]
> Changed 'com.squareup.wire:wire-runtime-metadata:3.0.0-alpha03' to 'com.squareup.wire:wire-runtime:3.0.0-alpha03', it works.

Right, you shouldn't be depending on `wire-runtime-metadata`, `wire-runtime` is the correct one.

> Bug there is another problem: ...

Good catch! We'll fix that.

> Okio 2.3.0-SNAPSHOT is incompatible with Kotlin 1.3.41, where can I get it's code?

1. Latest Okio 2.3.0-SNAPSHOT was built with Kotlin 1.3.40 so there should be no compatibility issues. Make sure you're not using a cached artifact. Running Gradle from command line with `--refresh-dependencies` should help.
2. If you're looking for Okio sources, they live here: https://github.com/square/okio

A few things I'd like to ask:
- Please report different issues in separate tickets, it'll make it much easier for us to triage and address them.
- Please use appropriate Markdown syntax to format code, otherwise it's hard to read.

Thanks!

**Comment by DTHeaven** [comment]
> > Changed 'com.squareup.wire:wire-runtime-metadata:3.0.0-alpha03' to 'com.squareup.wire:wire-runtime:3.0.0-alpha03', it works.
> 
> Right, you shouldn't be depending on `wire-runtime-metadata`, `wire-runtime` is the correct one.
> 
> > Bug there is another problem: ...
> 
> Good catch! We'll fix that.
> 
> > Okio 2.3.0-SNAPSHOT is incompatible with Kotlin 1.3.41, where can I get it's code?
> 
> 1. Latest Okio 2.3.0-SNAPSHOT was built with Kotlin 1.3.40 so there should be no compatibility issues. Make sure you're not using a cached artifact. Running Gradle from command line with `--refresh-dependencies` should help.
> 2. If you're looking for Okio sources, they live here: https://github.com/square/okio
> 
> A few things I'd like to ask:
> 
> * Please report different issues in separate tickets, it'll make it much easier for us to triage and address them.
> * Please use appropriate Markdown syntax to format code, otherwise it's hard to read.
> 
> Thanks!

OK. I will create another issue and close this.
Thanks.
