### ISSUE TITLE
gradle plugin generating code at the wrong folder

### ISSUE THREAD

**Issue by oldergod** [square/wire#1130]
In my `app/build.gradle`
```
wire {
  kotlin {
    out "src/main/java"
  }
}
```
The generated code is going to `/src/main/java` instead of `/app/src/main/java`. I believe `WireCompiler` was doing it as expected.

- [ ] write tests.
- [ ] fix.

**Comment by oldergod** [comment]
How about we generate code into `build/wire` instead of `build/generated` as well

**Comment by Egorand** [comment]
I believe `build/generated` is a special directory, so if sources are generated under `build/wire` they won't get compiled.

**Comment by JakeWharton** [comment]
There are no special directories. The generated folder is explicitly added as an input to the compiler task: https://github.com/square/wire/blob/master/wire-gradle-plugin/src/main/kotlin/com/squareup/wire/gradle/WireOutput.kt#L74-L75
