### ISSUE TITLE
(Android) grpc-client and runtime both define 'Util.kt'

### ISSUE THREAD

**Issue by MorrisonCole** [square/wire#1133]
AFAIK Android support for 3.0.0 is not yet ready so maybe this is known, but I tried crunching through to see where I'd get stuck anyway :)

Because both modules define `com.squareup.wire.internal.Util`, on the latest SNAPSHOT builds (and alpha) Android builds fail with:

```
Duplicate class com.squareup.wire.internal.UtilKt found in modules wire-grpc-client-3.0.0-SNAPSHOT.jar (com.squareup.wire:wire-grpc-client:3.0.0-SNAPSHOT:20190809.205059-66) and wire-runtime-3.0.0-SNAPSHOT.jar (com.squareup.wire:wire-runtime:3.0.0-SNAPSHOT)
```

*Edit:* this was the only issue blocking Android from making a successful gRPC call with grpc-client. I managed to make a successful call after changing the namespace to something more specific.

**Comment by Egorand** [comment]
Yep, looks like a bug, thanks for reporting!
