### ISSUE TITLE
Add Experimental annotations to coroutines-based gRPC API

### ISSUE THREAD

**Issue by Egorand** [square/wire#1151]
The following APIs are marked with `@Experimental`:

- kotlinx-coroutines-core
  - `@ObsoleteCoroutinesApi` suspend fun <E> ReceiveChannel<E>.consumeEach(action: (E) -> Unit)
  - `@ExperimentalCoroutinesApi` SendChannel<in E>.invokeOnClose(handler: (cause: Throwable?) -> Unit)

**Comment by oldergod** [comment]
Let's also update to latest kotlin and coroutines
