### ISSUE TITLE
protobuf to map

### ISSUE THREAD

**Issue by Globegitter** [square/wire#1163]
I am trying to convert a protobuf, using version 3.0.0-RC1 + kotlin generated code, to a `Map<String, Any>` to be able to add it to structured/json logging via log4j2. The only way I can think off doing it currently is converting it to JSON via moshi and then to a map, which seems quite expensive if that happens frequently.

So I was trying to look at https://github.com/square/wire/blob/972d535cf4c25199dec9387e059ab098d6584167/wire-moshi-adapter/src/main/java/com/squareup/wire/MessageJsonAdapter.kt and implement an Adapter myself, something like

```
class MessageJsonAdapter<M : Message<M, B>, B : Message.Builder<M, B>>(
    type: Type
) {
    private val messageAdapter = RuntimeMessageAdapter.create(type as Class<M>)
    private val fieldBindings = messageAdapter.fieldBindings.values.toTypedArray()

    @Throws(IOException::class)
    fun toMap(message: M?): Map<String, Any?> {
        if (message == null) {
            return mapOf()
        }
        val map = mutableMapOf<String, Any?>()
        fieldBindings.forEachIndexed { _, fieldBinding ->
            map[fieldBinding.name] = fieldBinding[message]
        }
        return map
    }
}
```

but that just throws an exception `No builder class found`. I am also not sure how to get a builder class in the first place as I can not find much documentation on it.

If there was an easy/builtin wa to convert protobufs to maps, then it would also be easier to satisfy https://github.com/square/wire/issues/1138 as I can ocnfigure log4j2 to print the json non-compacted.

**Comment by Egorand** [comment]
You'd have to generate your Kotlin protos in Java interop mode, cause the JSON adapter relies on the `Builder`. If you're using the Gradle plugin, pass in the following flag:
```groovy
wire {
  kotlin {
    javaInterop = true
  }
}
```
Sorry for the lack of documentation, we're working on it.
