### ISSUE TITLE
gRPC support Rxjava and service generation

### ISSUE THREAD

**Issue by laiyuejin99** [square/wire#1179]
Hi guys,

what is your timestamp to make wire support service generation?

Also I know it is easy to make wire-gRPC to support RxJava, will you guys implement it?

Thanks,
Andy

**Comment by oldergod** [comment]
Although we are gonna change the APIs really soon, you can have a peek at our 3.0.0-rc01 version where service generation is supported.
We are gonna finalize it real soon.

No plan for RxJava now.
