### ISSUE TITLE
WireRpc annotation populated with incorrect adapter locations

### ISSUE THREAD

**Issue by malachid** [square/wire#1235]
In the proto file, you may specify the java_package in addition to the package. For example:
```
package Company.Proto.Auth
option java_package com.example.proto.auth
```
When Wire auto-generates the classes, it will put them under the java_package. For example `com.example.proto.auth.LoginRequest#ADAPTER`.

The auto-generated service will instead use the package, and say something like:
```
  @WireRpc(
    path = "/Company.Proto.Auth.Authentication/Login",
    requestAdapter = "Company.Proto.Auth.LoginRequest#ADAPTER",
    responseAdapter = "Company.Proto.Auth.LoginResponse#ADAPTER"
  )
  suspend fun Login(request: LoginRequest): LoginResponse
```

GrpcMethod.toGrpc then does
```
val requestAdapter = ProtoAdapter.get(wireRpc.requestAdapter) as ProtoAdapter<S>
```
and ProtoAdapter does
```
val hash = adapterString.indexOf('#')
val className = adapterString.substring(0, hash)
val fieldName = adapterString.substring(hash + 1)
return Class.forName(className).getField(fieldName).get(null) as ProtoAdapter<Any>
```

This results in `Class.forName("Company.Proto.Auth.LoginRequest#ADAPTER")` when the actual auto-generated class exists as `com.example.proto.auth.LoginRequest#ADAPTER`; causing ClassNotFoundException.

**Comment by swankjesse** [comment]
Fix: https://github.com/square/wire/pull/1238
