### ISSUE TITLE
ProtoPruner

### ISSUE THREAD

**Issue by Egorand** [square/wire#1243]
- [x] in which case should we keep the `google/protobuf/descriptor` and other around?
- [x] default are pruned out.
- [x] Need to support non-scalar default values
- [x] `google.protobuf.*` pruning doesn't seem to work.
- [x] even though options' type might be pruned, the options itself are not when excluding `google.protobuf.*`. That's because we prune `Options#map` but we print `Options#elements`

**Comment by oldergod** [comment]
- [ ] in which case should we keep the `google/protobuf/descriptor` and other around?

**Comment by oldergod** [comment]
done.
