### ISSUE TITLE
wire-maven-plugin not found 3.0.3 

### ISSUE THREAD

**Issue by onexuan** [square/wire#1348]
maven 
wire-maven-plugin not found 3.0.3

**Comment by Egorand** [comment]
As mentioned in the [CHANGELOG](https://github.com/square/wire/blob/master/CHANGELOG.md#version-303), we're not maintaining the Maven plugin anymore. You should still be able to use `wire-maven-plugin:3.0.2`.

**Comment by onexuan** [comment]
I use wire-maven-plugin to generate .java files in Spring, if remove this plugin, Does it mean that it can be generated in other ways? How to do it.

**Comment by Egorand** [comment]
You can stay on version 3.0.2 if it works fine for you. Alternatively, if you're willing to switch to Gradle you can use Wire's Gradle plugin.

**Comment by onexuan** [comment]
OK, I got, thank you!

**Comment by jrodbx** [comment]
Alternatively, you can fork and maintain the Maven plugin part of the project!

We realize this may be a burden, but [our limited data](https://twitter.com/Piwai/status/1208409908598710273) seems to show that the plugin wasn't worth the maintenance cost.

**Comment by marcelmay** [comment]
Created a [fork](https://marcelmay.github.io/wire-maven-plugin/usage.html) of the Maven plugin. 

@jrodbx , the wire documentation [still references](https://square.github.io/wire/#generating-code-with-wire) the discontinued plugin with a [non-existing](https://search.maven.org/search?q=g:com.squareup.wire%20AND%20a:wire-maven-plugin) version "3.2.1".

**Comment by jrodbx** [comment]
Good catch @marcelmay.   https://github.com/square/wire/pull/1584
