### ISSUE TITLE
Generated options field can generate not compiling code.

### ISSUE THREAD

**Issue by oldergod** [square/wire#1373]
Say we depend on Java written/generated/whatever `FieldOptions`. Now, if we generate via the `KotlinTarget` a message and its options, the generated code might look like
```
val FIELD_OPTIONS_FOO: FieldOptions = 	
    FieldOptions(	
      my_field_option_one = 17	
    )
```
but this code can only compile if `FieldOptions` is in Kotlin, otherwise named parameter are forbidden and this will forbid any compilation of the generated code.

**Comment by Egorand** [comment]
Can you suggest steps to repro? Does this manifest when you're generating different protos containing custom options in different targets? So `FieldOptions` gets generated multiple times?

**Comment by oldergod** [comment]
I'll try to write a not-compiling test in the gradle plugin module.

**Comment by oldergod** [comment]
We're thinking of removing the custom options fields generation from all target.
