### ISSUE TITLE
Proto3: Support for Duration and Timestamp

### ISSUE THREAD

**Issue by oldergod** [square/wire#1382]
- [x] code gen and runtime API (timestamp.proto, duration.proto)
- [x] serialization & deserialization

Maybe create a `WireDuration` and `WireTimestamp` to allow MPP and map it to `java.time.*` on the JVM.

**Comment by pavlospt** [comment]
@oldergod is it safe to map it to `java.time.*`? This might need some different mapping for Android though 😐

**Comment by JakeWharton** [comment]
Both `Duration` and `Instant` are available on Android and are part of library desugaring back to 19 or 14 (I can't remember which, not that it really makes a difference).

**Comment by pavlospt** [comment]
@JakeWharton you mean when using AGP 4.0+, right? Otherwise is it documented that `java.time` is desugared?

**Comment by JakeWharton** [comment]
For 4.0, yes.

**Comment by pavlospt** [comment]
@JakeWharton so that will be a hard requirement probably if someone wants to use Wire for proto3?

**Comment by JakeWharton** [comment]
If you're using the built-in timestamp and/or duration types and your minSdk is lower than 26, yes.

**Comment by Egorand** [comment]
Our aspiration is to keep generated Kotlin code platform-agnostic, so I'd be against using `java.time.*` for Kotlin.

**Comment by JakeWharton** [comment]
Nothing about the use of java.time prevents platform agnostic code, it just means the types in common are defined in a shape that can be successfully typealias'd.
