### ISSUE TITLE
Proto3: Json Support

### ISSUE THREAD

**Issue by oldergod** [square/wire#1387]
Both moshi-adapter and gson-support are concerned, maybe we can decide to only support moshi...

The task is about to change the way we encode/decode JSON to match the proto3 spec. We also wanna guarantee backward compatibility. Be aware of casing!

- [x] moshi
- [x] gson
- [x] backward compat
- [x] Fix moshi to look up the proper type on primitive (It's looking for `Long` when the generated code is of `long`)
- [x] name mapping: `order_ids` become `orderIds` in Json.
- [x] we shouldn't print empty lists (how about other default values?)
- [x] _If a value is missing in the JSON-encoded data or if **its value is null**, it will be interpreted as the appropriate default value_
- [ ] uint64 map keys

**Comment by swankjesse** [comment]
Hold the phone. We need to use strings for these three: int64, fixed64, uint64:
https://developers.google.com/protocol-buffers/docs/proto3#json

**Comment by oldergod** [comment]
Let's follow in #279
