### ISSUE TITLE
Generated Kotlin code with member `adapter` is hiding supertype member

### ISSUE THREAD

**Issue by pavelreiter** [square/wire#1446]
## About:
If the proto definition contains field named `adapter` it will cause that the generated Kotlin code will contain conflicting member.

This is caused by the fact that `nameAllocatorStore` in `KotlinGenerator` is [set only with the constant variant (uppercase)](https://github.com/square/wire/blob/7aab9195bf1c898d355b117a9b5e3c954219789f/wire-library/wire-kotlin-generator/src/main/java/com/squareup/wire/kotlin/KotlinGenerator.kt#L257) of the member name but in the supertype `Message` it is defined lowercase.

## Example proto:
```proto
message Broken {

    // This will hide supertype member
    optional string adapter = 1;

    // This is changed to `unknownFields_`
    repeated string unknownFields = 2;
}
```

This issue is present in current master (3.2.0-SNAPSHOT).

**Comment by Egorand** [comment]
Thanks for reporting! Wanna send us a PR?

**Comment by pavelreiter** [comment]
Hi @Egorand, I would like to but first I will need permission from my employer to sign the CLA, since I was working on this issue on his time. Sorry for the bother and I understand if you won't wait for it.
