### ISSUE TITLE
Generated Kotlin code is malformed for long identifiers

### ISSUE THREAD

**Issue by pavelreiter** [square/wire#1451]
## About
If the proto definition contains member with name longer then 82 chars, it will cause that generated
Kotlin will contain incorrect wrapping.
As described [here](https://github.com/square/kotlinpoet#spaces-wrap-by-default), the KotlinPoet wraps the code by default and unfortunately the KotlinGenerator.kt contains large number of templates like `%L =`  where the space has to be replaced with `·` in order to prevent wrapping at incorrect location, eg.: `%L·=`
This issue is also present in case of message names, but the char limit is higher.

Issue is present in current master

## Sample proto:
```proto
syntax = "proto2";

package squareup.sample;

message Broken {

    required string membernamewhichis82charactersloooooooooooooooooooooooooooooooooooooooooooooooooong = 1;

}
```
### Generated Kotlin class
```kotlin
      // ..shortened
      override fun decode(reader: ProtoReader): Broken {
          // ..shortened
          val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> membernamewhichis82charactersloooooooooooooooooooooooooooooooooooooooooooooooooong
                = ProtoAdapter.STRING.decode(reader)

```

**Comment by oldergod** [comment]
Thank you. Are you just looking for bugs in the code, or is this something you actually encountered?

**Comment by pavelreiter** [comment]
Hi @oldergod, I admit that this one I found by trying if it will break. Previous issues I have encountered when I was triing to compile our old proto definitions (which work well with wire 2.2, with small exceptions) with kotlin target.
This one I have found by trying some scenario (using generated proto definitions, to generate Kotlin code) which probably would become reality for me somewhere in the future.

**Comment by therealsphinx** [comment]
What is the impact here?

**Comment by therealsphinx** [comment]
@pavelreiter What is the impact here?

**Comment by pavelreiter** [comment]
@therealsphinx What do you mean? As I have stated above I don't have real usage for such long identifier right now. I have found the issue during research if wire can be used for our planned multiplatform library which we would like to write in kotlin, and this was edge case test.
Also if you don't need kotlin generated class, you can use java one which is not affected by the issue, so I would say that impact is right now low, unless someone else comes and says that he is also affected and it is real use-case for him.
