### ISSUE TITLE
Proto3: Struct support

### ISSUE THREAD

**Issue by oldergod** [square/wire#1463]
See `google.protobuf.Struct`

Moshi would match that with a `map<string, Any?>` probably 

- [x] Maps and Lists should be nullable
- [x] Canonilization of fields.
- [x] Java support.

**Comment by oldergod** [comment]
@swankjesse For the canonilization, do we want something like we do for `oneof`s like in `init` and in the `build()` to throw if any Value is not `null`, `double`, `string`, `boolean`, `list`, `map`?

**Comment by swankjesse** [comment]
Implemented!
