### ISSUE TITLE
Delimited toString Output

### ISSUE THREAD

**Issue by aerb** [square/wire#1486]
The output of a generated `Message`'s `toString()` can be difficult to read in scenarios with heavily nested messages. I want something like  pretty printing for `toString()`, but without having to worry about the bloat of introducing lots of whitespace into the `toString()` response itself. What I would like to propose is properly delimited `toString()` output so a separate tool can then format that String.

At present `toString()` will return something like this:
```
Person{name=Jadzia Dax, age=1,300, greeting=Hi, I'm {CURRENT_HOST} dax!, file=C:\Users\Dax.bat}
```
Writing a reliable formatter for this will be hard:
- `age=1,` looks like the end of the field
- A template format `{CURRENT_HOST}` could potentially look like a new internal message.

I propose escaping characters `,{}[]\` so we can reliably format the output of `toString()`
The example above would now become:
```
Person{name=Jadzia Dax, age=1\,300, greeting=Hi\, I'm \{CURRENT_HOST\} Dax!, file=C:\\Users\\Dax.bat}
```

**Comment by Egorand** [comment]
As an alternative, would we want to make the output look a bit more like JSON? I.e., double-quote strings, print numbers without any punctuation etc.

**Comment by aerb** [comment]
My first choice would be to just have `toString()` emit proper JSON. There has been some concern that JSON would bloat server logs too much, so this format is intended to add as few additional characters as possible.

**Comment by oldergod** [comment]
By adding double quotes, we'd have to escape them as well.
I'm gonna try escaping `,{}[]\=` and let's see

**Comment by aerb** [comment]
I don't think we need `=`

**Comment by oldergod** [comment]
What if a value has an `=` in it?

**Comment by aerb** [comment]
`MyProto{this_is_my_field=I'm now in a mode where I'm reading strings and if I see an = sign I will just ignore it until I encounter a, my_next_field=I will also terminate if I see a}`

**Comment by oldergod** [comment]
```MyProto{this_is_my_field=a, b=3, this_is_my_second_field=d}```

**Comment by aerb** [comment]
in that case you don't escape the `=` you escape the `,`
