### ISSUE TITLE
WireTask is not compatible with instant execution

### ISSUE THREAD

**Issue by stephanenicolas** [square/wire#1496]
Hi there,

[WireTask](https://github.com/square/wire/blob/master/wire-library/wire-gradle-plugin/src/main/kotlin/com/squareup/wire/gradle/WireTask.kt) is breaking with instant execution as it uses the `project` object. This is not allowed in instant execution anymore.

The `rules` input should be declared as input files directly. 

This issue is the root cause of https://issuetracker.google.com/issues/153711618

**Comment by Egorand** [comment]
Thanks! If you'd like to submit a PR that'd be awesome.

**Comment by stephanenicolas** [comment]
I would love to, but it will take a couple days to prioritize it.

**Comment by stephanenicolas** [comment]
The problem is more complex than I thought. Here is a screenshot of the instant execution error:
![image](https://user-images.githubusercontent.com/1832925/79191369-3d6bb480-7ddb-11ea-998d-72ade8f79c0e.png)

The issue is that 2 fields in the `WireTask` are `com.squareup.wire.gradle.WireInput` instances and this classes uses a `Project` as a constructor parameter. But a project is not serializable and should be not used anymore after the configuration phase. Tasks should be serializable and their parameters too.

I checked the code and the change looks important to remove a constructor dependency on the project object passed to `WireInput`.  It is used in a few places.

**Comment by oldergod** [comment]
I can only find two places for a call to `WireInput`. What's the workaround passing the `project.dependencies` to the constructor?

**Comment by oldergod** [comment]
fixed by #1498
