### ISSUE TITLE
Field presence support for proto3

### ISSUE THREAD

**Issue by wfansh** [square/wire#1497]
Google will update the proto3 syntax to support "optional" for field presence:

*  Summary
Add field presence to proto3 in a backward-compatible way by introducing the optional keyword with the same semantics as proto2.

* .proto syntax changes
Users can put `optional` on any proto3 field, with syntax and semantics identical to proto2:

```
syntax = "proto3";
message Foo {
  // Optional fields track presence.
  optional int32 a = 1;
  optional int64 b = 2;
  optional string c = 3;
  optional double d = 4;
```

Public announcement will come soon. Can we support this for proto3? 

Removing line 299 - 301 would be OK.
https://github.com/square/wire/blob/master/wire-library/wire-schema/src/commonMain/kotlin/com/squareup/wire/schema/internal/parser/ProtoParser.kt#L299

**Comment by oldergod** [comment]
Does this affect the encoding on the wire? what happens on a `optional int32` of value `0`? Same with decoding, is an `optional int32` set to `0` or to `null` if there's bytes for it?

**Comment by jwendel** [comment]
Looks like the doc has been posted describing this: https://github.com/protocolbuffers/protobuf/blob/master/docs/field_presence.md

**Comment by wfansh** [comment]
Yes. That's the doc.

**Comment by wfansh** [comment]
Here is another update.
https://github.com/protocolbuffers/protobuf/issues/1606#issuecomment-618687169

**Comment by wfansh** [comment]
Thanks guys!
