### ISSUE TITLE
Kotlin code generation from proto

### ISSUE THREAD

**Issue by cupertank** [square/wire#1507]
When you generate Java code from proto files, you connect this code to the "compileJava" task.
https://github.com/square/wire/blob/dfd5c35170a748dc8c9b5b33041a97c21cfb8e9b/wire-library/wire-gradle-plugin/src/main/kotlin/com/squareup/wire/gradle/WireOutput.kt#L73-L94
But when you generate Kotlin code from proto files, you connect this code to all "compile" tasks, that is: "compileKotlin" and "compileTestKotlin". 
https://github.com/square/wire/blob/dfd5c35170a748dc8c9b5b33041a97c21cfb8e9b/wire-library/wire-gradle-plugin/src/main/kotlin/com/squareup/wire/gradle/WireOutput.kt#L131-L145
Why are Java and Kotlin versions of the code connection so different? 

Because of this, if I generate code for Kotlin, then my tests are compiled for the first time, and then if I change the test code, I get the error "_Cannot access class * classname *. Check your module classpath for missing or conflicting dependencies"_. Maybe I'm doing something wrong, or connecting incorrectly. My wire config:
```
val generatedDir = "src/main/kotlin-gen"
wire {
    protoPath("src/main/proto")

    kotlin {
        out = generatedDir
    }
}
```

**Comment by oldergod** [comment]
I think that's fixed since Wire ~3.3 or 3.4.

Please reopen if you see another problem.
