### ISSUE TITLE
wire-maven-plugin-3.2.0.pom 404 not found 

### ISSUE THREAD

**Issue by onexuan** [square/wire#1526]
https://repo.maven.apache.org/maven2/com/squareup/wire/wire-maven-plugin/3.2.0/wire-maven-plugin-3.2.0.pom

404 Not Found

**Comment by Egorand** [comment]
The Maven plugin has been discontinued: https://github.com/square/wire/blob/master/CHANGELOG.md#version-303

**Comment by marcelmay** [comment]
@onexuan , try my [forked](https://github.com/marcelmay/wire-maven-plugin) plugin supporting latest Wire version.
