### ISSUE TITLE
map with a recursive value cannot be initialized.

### ISSUE THREAD

**Issue by drashkov** [square/wire#1545]
Example proto:

```
message ModelEvaluation {
  optional string name = 1;
  optional double score = 2;
  map<string, double> signals = 3;
  map<string, ModelEvaluation> models = 4;
}
```

When trying to initialize a `ModelEvaluation` with an empty map, an error is thrown, so a recursive map can not be used.
```
 ModelEvaluation.Builder()
  .name(name)  
   .score(score)
   .signals(mapOf()) // works
  .models(mapOf()) // crashes
  .build()
```

**Comment by oldergod** [comment]
Recursive or not, for maps _the value_type can be any type except another map._

We should probably crash when building the schema.
