### ISSUE TITLE
How to use any type in wire?

### ISSUE THREAD

**Issue by onexuan** [square/wire#1564]
How to use any type in wire?

**Comment by oldergod** [comment]
We don't officially support it but you can have a loot at those tests if you wanna know more.
https://github.com/square/wire/blob/master/wire-library/wire-tests/src/commonTest/kotlin/com/squareup/wire/AnyMessageTest.kt

**Comment by onexuan** [comment]
unable to generate AnyMessage

This is result.proto file
syntax = "proto3";

import 'google/protobuf/any.proto';
option java_package = "com.test.data.proto";

message Result {

int32 code = 1;
int64 version = 2;
google.protobuf.Any data = 3;
}

generate java file is com.google.protobuf.Any

@WireField(
      tag = 3,
      adapter = "com.google.protobuf.Any#ADAPTER"
  )

But not generate com.squareup.wire.AnyMessage
WireField(
    tag = 3,
    adapter = "com.squareup.wire.AnyMessage#ADAPTER",
  )
