### ISSUE TITLE
Failed to locate google/protobuf/*.proto

### ISSUE THREAD

**Issue by MadDataScience** [square/wire#1565]
I'm trying to use `wire-compiler-3.2.2-jar-with-dependencies.jar` to generate Kotlin code for Android. The proto files I'm using have dependencies like 
```protobuf
import "google/protobuf/struct.proto";
import "google/protobuf/timestamp.proto";
```
When I try running 
```bash
java -jar jars/wire-compiler-3.2.2-jar-with-dependencies.jar --proto_path=protos --kotlin_out=android
```
I get exceptions like:

> Exception in thread "main" java.io.FileNotFoundException: Failed to locate google/protobuf/struct.proto

When I use `protoc` for other languages (including Java) it just works. `struct` and `timestamp` are [well-known types](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf). How do we include these using this library?

**Comment by oldergod** [comment]
`struct` and `timestamp` are proto3 types which Wire doesn't support yet; broadly Wire doesn't support proto3 yet as a whole.

Check #1463 and #1382 if you wanna follow-up.

**Comment by mickeyreiss** [comment]
Are well known types, like struct timestamp, now supported as of the 3.5.0 release?

**Comment by oldergod** [comment]
They are. What's up?
