### ISSUE TITLE
unable to generate AnyMessage in java

### ISSUE THREAD

**Issue by onexuan** [square/wire#1567]
unable to generate AnyMessage in java

This is result.proto file
syntax = "proto3";

import 'google/protobuf/any.proto';
option java_package = "com.test.data.proto";

message Result {

int32 code = 1;
int64 version = 2;
google.protobuf.Any data = 3;
}

generate java file is com.google.protobuf.Any

@WireField(
tag = 3,
adapter = "com.google.protobuf.Any#ADAPTER"
)

But not generate com.squareup.wire.AnyMessage
WireField(
tag = 3,
adapter = "com.squareup.wire.AnyMessage#ADAPTER",
)

**Comment by onexuan** [comment]
@oldergod @swankjesse

**Comment by swankjesse** [comment]
Wire doesn't support proto3 at this time, including Any. But we'll need to fix this before we do!

**Comment by onexuan** [comment]
--kotlin_out, it is able to generate with kotlin_out, but java not

use kotlin
WireField(
tag = 3,
adapter = "com.squareup.wire.AnyMessage#ADAPTER",
)

use java
@WireField(
tag = 3,
adapter = "com.google.protobuf.Any#ADAPTER"
)
