### ISSUE TITLE
Wire generated folder not registered as a source directory 

### ISSUE THREAD

**Issue by daniellevass** [square/wire#1574]
Hi,

The [wire compiler docs](https://github.com/square/wire/blame/master/wire-library/docs/wire_compiler.md#L66) specify that it will register the generated folder as a source directory automatically. However this didn't happen for me.

I'm using `api("com.squareup.wire:wire-runtime:3.2.2")` and `apply plugin: 'com.squareup.wire'`

I tried to manually add the source directory by adding the following to my build.gradle:

```
android {
    sourceSets {
        main.java.srcDirs += "$project.buildDir/generated/source/wire"
    }
}
```

Which seems to work for most of the time. Until I edit and run my tests.

I get the following error: `Cannot access class <generated class> Check your module classpath for missing or conflicting dependencies`. This only happens after I edit a test and run them.

I can fix it by cleaning and building the project again, but that's getting quite time consuming to do each time I edit a test.

Could you perhaps expand the docs to let us know what the correct gradle command is to register the generated folder as a source directory?

I'm unsure if this is connected to #1507 - I'm also generating kotlin only.

Thanks,

**Comment by JakeWharton** [comment]
This is tracked by #1123. Basically the plugin needs to call registerSourceGeneratingTask for Android projects and everything will be handled automatically.

**Comment by cupertank** [comment]
Hi @daniellevass  
I faced a similar problem and for a very long time I could not solve it, but today I decided to end it once and for all and I succeeded. Keep my decision.
```
tasks.compileTestKotlin{
    doFirst(){
        val badPath = "$project.buildDir/generated"
        source = source.filter { "$project.buildDir/generated" !in it.path }.asFileTree
    }
}
```
In the badPath variable, you can specify the path to the folder with the generated classes and it will work. You can also save your sourceSets block.

Good luck!
