### ISSUE TITLE
Integer overflow when using UInt32 in protobuf message

### ISSUE THREAD

**Issue by vivekrishnan** [square/wire#1577]
Hello,

I am using wire(v3.0.0-alpha01) in my projects to generate java files using the wire compiler. One of my proto files has a message like this
```
message PushFileChunkRequest {
    required string id = 1;
    required uint32 startByte = 2;

    /// Checksum for this chunk; the checksum format is crc32
    required uint32 checksumValue = 3;
}
```
Now when wire translates this to a java class, the checksumValue field is mapped to the following:
```  
  @WireField(
      tag = 3,
      adapter = "com.squareup.wire.ProtoAdapter#UINT32",
      label = WireField.Label.REQUIRED
  )
  public final Integer checksumValue;
```
Since the UInt32 is mapped to an Integer, in many cases I am receiving garbage value in this field because of overflow especially when being sent values that are greater than `Integer. MAX_VALUE`. It looks like wire should internally map UINT32 to Long so that it can accommodate all the possible values in the UNIT32 space. Is there a reason for this particular implementation? Changing the spec is currently hard so I am looking for possible workarounds for this problem. Any suggestions?

**Comment by JakeWharton** [comment]
The bits of the integer reflect the unsigned value and the JDK has a few methods for operating on the unsigned value using the signed storage type (`compareUnsigned`, `divideUnsigned`, `remainderUnsigned`, `toUnsignedString`).

We can't really widen to long since that leaves nothing to do for uint64.

**Comment by JakeWharton** [comment]
Also, notably, you can get the desired long by doing `checksumValue & 0xFFFFFFFFL` or `Integer.toUnsignedLong(checksumValue)`

**Comment by JakeWharton** [comment]
Eventually for Kotlin we'll be able to use `UInt` and if project valhalla/panama ever ship we'll likely have some kind of 32-bit unsigned "primitive" for Java 19 users.

For now, though, this is working as intended.

**Comment by vivekrishnan** [comment]
Agreed. Thanks for the response. The use of `&` operator solves the issue for now.
