### ISSUE TITLE
Wire alternative toString that render the with (almost) source code that would build the proto

### ISSUE THREAD

**Issue by acostama** [square/wire#1581]
When I want to generate test data by running some code it would be to be able to call a method on the object that gives me most of this source code. Almost correct is enough since resolving imports is probably unnecessary. Today the best I can do is call write the proto as json and manually create a builder. This feature would save lots of time!

**Comment by JakeWharton** [comment]
This seems like a highly specialized requirement that isn't worth supporting directly in the library.

You can likely achieve this yourself by using `SchemaLoader` to parse your proto definitions which will give you a `Schema` in which you can look up any type which will provide information about the type. Coupled with the instance, you should be able to combine the two to generate whatever you want. This is how Wire itself generates its code and is available for you to use.
