### ISSUE TITLE
Add parameter to Gradle plugin to not generate services.

### ISSUE THREAD

**Issue by oldergod** [square/wire#1602]

**Comment by swankjesse** [comment]
We already have excludes, isn’t that sufficient? More mechanisms for stuff like this feels bad.

**Comment by JakeWharton** [comment]
Does that work if the service is both the root and also an exclude?

**Comment by oldergod** [comment]
Yes it should work.

`root` is used for the tree shaking root.
`exclude` is only for target to know if they are to generate a specific type/service or not.

Unless you meant `prune` for exclude, in which case Wire throws.
