### ISSUE TITLE
Feature pitch: MessageMethods

### ISSUE THREAD

**Issue by swankjesse** [square/wire#162]
I've got a proto message called `Money`. It's straightforward:

```
message Money {
  optional int64 amount = 2;
  optional CurrencyCode currency_code = 3 [default = USD];
}
```

But the class it generates isn't _ergonomic_. I want my Wire classes to be easy and awesome like the classes I write myself. In particular, I want to do stuff like this:

```
    Money price = Money.usd(500_00);
    Money taxes = Money.usd(10_00);
    Money total = price.plus(taxes);
```

I propose we embrace our dear friend _annotation processing_ in Wire. Specifically I'd like to be able to write a utility class composed of static methods:

```
@MessageMethods(Money.class)
final class MoneyMethods {
  public static Money plus(Money me, Money other) {
    checkArgument(me.currency_code == other.currency_code);
    return new Money.Builder(me)
        .amount(me.amount + other.amount)
        .build();
  }

  public static Money usd(long amount) {
    return new Money.Builder()
        .currency_code(CurrencyCode.USD)
        .amount(amount)
        .build();
  }
}
```

This would cause Wire to include delegating methods in its generated Message:

```
public final class Money extends Message {
  ...

  public Money plus(Money other) {
    return MoneyMethods.plus(this, other);
  }

  public static Money usd(long amount) {
    return MoneyMethods.usd(amount);
  }
```

The rules would be straightforward. If a `MoneyMethods` method's first argument is `Money`, we generate an instance method that delegates and passes `this` as that first argument. Otherwise we generate a static method that delegates. 

MoneyMethods need not be public, but only its `public` methods yield generated trampolines.

**Comment by JakeWharton** [comment]
@swankjesse are you ok if we close this or do you want to pursue further? Can we just say "use Kotlin" :grinning: ?

**Comment by swankjesse** [comment]
Kotlin.
