### ISSUE TITLE
Support UTF-8 with BOM in proto files please

### ISSUE THREAD

**Issue by miltocoal** [square/wire#1647]
Hey guys,

I have a bunch of 3rd-party proto files that are UTF-8 with BOM and without BOM:

Example #1 (with BOM):
```
d@OMEN:.../WireTest/app/src/main/proto$ hexdump -C MachineId.proto
00000000  ef bb bf 73 79 6e 74 61  78 20 3d 20 22 70 72 6f  |...syntax = "pro|
```

Example #2 (without BOM):
```
d@OMEN:.../WireTest/app/src/main/proto$ hexdump -C StatDoc.proto
00000000  73 79 6e 74 61 78 20 3d  20 22 70 72 6f 74 6f 33  |syntax = "proto2|
```

Wire compiler v3.2.2 apparently doesn't like BOM:
```
Syntax error in .../MachineId.proto:1:1: expected a word
```

Would it be feasible for Wire to support this?

**Comment by swankjesse** [comment]
Can do. Will need to attempt to skip `efbbbf` if that's a prefix of the .proto file.

**Comment by JakeWharton** [comment]
Should we just add proper BOM support like we have in OkHttp? It's only like 10 LOC if I recall.
