### ISSUE TITLE
Make Element types mutable and public

### ISSUE THREAD

**Issue by sgarfinkel** [square/wire#1687]
Although they are data classes, their properties are all immutable, which results in substantial numbers of `copy` calls if you are manipulating the parsed AST in memory. There's already an immutable container `ProtoFile`, so it would be handy to be able to mutate the underlying parts.

**Comment by swankjesse** [comment]
Just curious – what are you using it for? Might make it easier for us to make APIs that work for you.

**Comment by sgarfinkel** [comment]
My use case is to parse another serialization format and generate corresponding Protobuf DSL.

Also it doesn't appear as though you can add an in-memory only `ProtoFile` to a `Schema`. The CoreLoader crashes when it can't open the non-existent file from the FileSystem. I can open another issue about that.

**Comment by JakeWharton** [comment]
Would #1688 solve your problem?

**Comment by sgarfinkel** [comment]
@JakeWharton Yes I think this can be closed in favor of #1688. I'll follow up there.
