### ISSUE TITLE
Avoiding code generation pain in Windows

### ISSUE THREAD

**Issue by yschimke** [square/wire#1766]
Let me know if this should be a stackoverflow question.  I'm coding on Windows recently as my son built me a development/gaming PC.

It's noticeable that by default a github checkout and build will flag all generated files (but checked in) as changed because of line endings.  Assuming modern Windows Java tooling can handle unix newlines, can you make it configurable to ignore platform line endings and default to \n?

I think I can get around this with git config, but making this the default seems like it would save a lot of time.

**Comment by JakeWharton** [comment]
Did your git config have `autocrlf` set to something when you checked out? Or are you saying the problem is that on Windows we generate the files with CRLF instead of just LF

**Comment by yschimke** [comment]
Ahhh, yep inverted, my bad.  So the Git for Windows installer sets it to true globally.

The generator is creating LF files, but the default checkout was originally CRLF.  Without looking at git config I don't think there is much any code generator can do.

**Comment by yschimke** [comment]
Coming back to this, should the default be generating crlf on Windows?

**Comment by swankjesse** [comment]
I don’t think `\r\n` makes sense anywhere in 2020. It’s a relic of non-networked computers, when being consistent with the local device was useful.

**Comment by yschimke** [comment]
Let me restate this :)

"I don’t think developing Java on Windows makes sense anywhere in 2020. Windows for Java development is a relic of corporate developers, when having Office, Excel and Outlook work well was more important than a decent Java development environment."

**Comment by yschimke** [comment]
No objection at all, hence closing - but using Wire codegen on a Windows PC is a broken experience by default.  Would work once you change your git config.

**Comment by JakeWharton** [comment]
The overwhelming majority of Android development is done on Windows. Even Notepad can handle `\n`-only line endings now. I think it's more that `\r\n` isn't needed _anywhere_ anymore, even on Windows.

**Comment by yschimke** [comment]
So what am I missing? Set LF as the global git config?

It's been painful intro so far. Found myself editing the registry to get certain gradle builds working for completely unrelated reasons

**Comment by JakeWharton** [comment]
I thought that was the default and you have to opt-in to settings like autocrlf which do the conversion.

**Comment by yschimke** [comment]
I believe the windows installer (at least when run standalone, presumably via some other package that needed it) defaults core.autocrlf to true. Or I missed this dialog

https://www.edwardthomson.com/blog/git_for_windows_line_endings.html

Following

https://stackoverflow.com/questions/39408793/git-core-autocrlf-line-ending-default-setting/48230871

And setting

`git config --global autocrlf input`

shows

```
git config --list --show-origin
file:C:/Program Files/Git/etc/gitconfig core.autocrlf=true
file:C:/Users/yuri/.gitconfig   core.autocrlf=input
```

So the installer default in an admin owned file, overrides the global value.
