### ISSUE TITLE
Unable to resolve references on Android Studio 4.0.1

### ISSUE THREAD

**Issue by vincent-paing** [square/wire#1773]
Codes are generated, and can be consumed using manually typing out imports, functions, field. etc. However, Android Studio 4.0.1 is not recognizing it as source directory.

Environment:
Android Studio 4.0.1
Gradle 6.1.1
Wire version : 3.2.2

I've tried
- Invalidate Cache & Restart
- Deleting .gradle folder
- Deleting .idea folder

Work around:
Manually marking `source/generatedwire/` as generated source root directory.

**Comment by oldergod** [comment]
This is tracked by #1123. Basically the plugin needs to call registerSourceGeneratingTask for Android projects and everything will be handled automatically.
