### ISSUE TITLE
Wire / Moshi default improvement

### ISSUE THREAD

**Issue by yschimke** [square/wire#1781]
I'm using Wire code generation with Moshi default kotlin serialization.  I assume this isn't explicitly supported.  That said it works really well, except for an additional synthetic field.

"cachedSerializedSize$wire_runtime":0

Should this be officially supported without additional fields?

**Comment by yschimke** [comment]
Think it breaks on 3.3.0 with proto3, closing for now as it's probably definitely not supported or expected to work.

**Comment by oldergod** [comment]
I don't think it's doable. Moshi cannot support it by default since specific fields need specific behaviors in protos.
https://github.com/square/wire/blob/master/wire-library/wire-runtime/src/jvmMain/kotlin/com/squareup/wire/internal/JsonIntegration.kt

I guess it would work for other fields not part of the exceptions.

**Comment by yschimke** [comment]
Is best solution something like a WireJsonAdapterFactory?

**Comment by oldergod** [comment]
We actually have one?
https://github.com/square/wire/blob/master/wire-library/wire-moshi-adapter/src/main/java/com/squareup/wire/WireJsonAdapterFactory.kt

Maybe we could add a doc for JSON. I am not sure we do.

**Comment by yschimke** [comment]
Thanks. Not sure how I missed this. I assumed I was doing something weird

**Comment by yschimke** [comment]
I'm an idiot and I apologise for wasting your time. :)  

I had it registered correctly already, but it's behind a framework that is stubbornly using a different library not moshi here!

**Comment by oldergod** [comment]
You gave me a good idea though! https://github.com/square/wire/pull/1783/files
