### ISSUE TITLE
Understanding wire handling of null strings in proto3

### ISSUE THREAD

**Issue by yschimke** [square/wire#1782]
With proto2 it seemed possible to model a null as an optional string field.

If I understand correctly with proto3, optional is now the default, so not required in the proto, but also the null is now strictly handled as "" as the default value for proto strings?

Hence the solution is using google.protobuf.StringValue to model a string that can be null?

**Comment by oldergod** [comment]
By default proto3 isn't optional, it's what we call "identity if absent".
```protobuf
string a = 1;
```
So if `a` isn't set, its value will be the identity of its type (string) which is an empty string.
Only `message` 's identity is `null` if I recall. But proto3 brought back `optional` back to life.

https://github.com/protocolbuffers/protobuf/blob/master/docs/implementing_proto3_presence.md

**Comment by yschimke** [comment]
Interesting the Intellij proto plugin flags as an error since it's already the default
