### ISSUE TITLE
[feature request] Make generateProtos Gradle task cacheable

### ISSUE THREAD

**Issue by damianw** [square/wire#1784]
The `generateProtos` task is not currently [cacheable](https://docs.gradle.org/current/userguide/build_cache.html#sec:task_output_caching_details). Adding cache support has the potential to save build time for users of Gradle's local and remote caches.

**Comment by oldergod** [comment]
We have tests for the plugin cacheability https://github.com/square/wire/blob/1f28ff5ad180fe3c944a37b27424c4183715888a/wire-library/wire-gradle-plugin/src/test/kotlin/com/squareup/wire/gradle/WirePluginTest.kt#L797-L813

Are you talking about something else? If no, could you provide a repo sample or something? If yes, could you elaborate?

**Comment by damianw** [comment]
Thanks for the reply! I'm referring to cacheability as it pertains to the [Gradle build cache](https://docs.gradle.org/current/userguide/build_cache.html) - not just [up-to-date checks](https://docs.gradle.org/current/userguide/more_about_tasks.html#sec:up_to_date_checks).

Making a task cacheable usually involves annotating it with `@CacheableTask` and declaring input `@PathSensitivity`. [Documentation](https://docs.gradle.org/current/userguide/build_cache.html#enable_caching_of_non_cacheable_tasks)
