### ISSUE TITLE
Allow filtering by path for srcJar dependencies

### ISSUE THREAD

**Issue by Mishkun** [square/wire#1795]
We use proto schema published as jar, but we need just a subset of that. But `include` option of `sourcePath` closure only works for directory dependencies. It would be nice to allow it for jar dependencies too

**Comment by oldergod** [comment]
You should be able to do so.

```groovy
wire {
  sourcePath {
    srcJar 'myJar'
    include 'com/example/pizza/pizza.proto'
  }
}
```

**Comment by Mishkun** [comment]
As far as I see, it doesn't.
https://github.com/square/wire/blob/master/wire-library/wire-gradle-plugin/src/main/kotlin/com/squareup/wire/gradle/WireExtension.kt#L194

**Comment by oldergod** [comment]
How about as far as you tried? I'm using it.

**Comment by Mishkun** [comment]
I'll try to make a reproducable example soon, or close the issue

**Comment by oldergod** [comment]
We have tests for that already, you can see the execution here: https://github.com/square/wire/blob/b77b2b09cfbc12dd905b10ea8a0cf94dffca8122/wire-library/wire-gradle-plugin/src/test/kotlin/com/squareup/wire/gradle/WirePluginTest.kt#L219-L232

and the repo here: https://github.com/square/wire/tree/master/wire-library/wire-gradle-plugin/src/test/projects/sourcejar-local-single-file

**Comment by Mishkun** [comment]
@oldergod hmm. Can I resolve a jar using gradle-style dependency notation? Or I need to manually download and provide path to it locally?

**Comment by Mishkun** [comment]
And what about 'some/directory/contents/**' notation?

**Comment by oldergod** [comment]
You can use maven coordinates for `srcJar` but wildcards only works for `srcDirs`, not `srcJar`.

**Comment by Mishkun** [comment]
Oh, so that's why. Any chances it could be implemented?

**Comment by oldergod** [comment]
I actually tried a few months ago. I thought it would be super easy but it
wasn't and I gave up.
It isn't on my todo list right now.

Any contribution would be welcome though!

**Comment by benjamin-bader** [comment]
I just hit this the other day.  @oldergod do you happen to recall what made this difficult to implement?

**Comment by oldergod** [comment]
I don't recall in details. I think it only needs some work which I didn't have time of back then. We can use it for `srcDirs` because that's Gradle doing it for us. For `srcJar`, I think we'd need to do it from scratch.

**Comment by benjamin-bader** [comment]
I finally had a chance to look at this and got a PR up.  It's definitely a bit squirrely - would love to have ideas on how it might be possible to make this nicer.
