### ISSUE TITLE
Invalid type of annotation member

### ISSUE THREAD

**Issue by miltocoal** [square/wire#1798]
```
syntax = "proto3";
import "google/protobuf/descriptor.proto";
import "google/protobuf/wrappers.proto";

extend google.protobuf.FieldOptions
{
  bool field_option_bool = 7776; // this is good
  int32 field_option_int32 = 7777; // this is good
  string field_option_string = 7778; // this is good
  bytes field_option_bytes = 7779; // this is bad
}

package com.play7776.wiretest;

message Occupation {
  string name = 1 [(field_option_bool)=true];
}
```

It gives compilation error: 
e: D:\StudioProjects\WireTest\app\build\generated\source\wire\com\play7776\wiretest\FieldOptionBytesOption.kt: (17, 14): Invalid type of annotation member

The cause of the error is that Wire generates `FieldOptions` as annotations. In Java primitives, classes, enums or Strings are the only allowed annotation type elements. Wire uses non-primitive object of type `ByteString` for proto's `bytes` which is invalid.

https://docs.oracle.com/javase/specs/jls/se8/html/jls-9.html#jls-9.6.1

**Comment by swankjesse** [comment]
Yikes. Can fix!

**Comment by swankjesse** [comment]
@miltocoal any idea if `bytes` as a field is usable? I couldn’t find docs on how to use it in a real option.

**Comment by miltocoal** [comment]
I'm going to ask maintainers of my proto files to justify `bytes` as a field usage. Alas, I'm not the owner, otherwise I will just use `string` instead.

**Comment by miltocoal** [comment]
Well, they want to have not only UTF-8 strings, but another encodings too and this is why they employ `bytes` in `FieldOptions` and in other place as well. Such a legacy.
