### ISSUE TITLE
Provide ProtobufHttpMessageConverter for Spring MVC

### ISSUE THREAD

**Issue by davidpelfree** [square/wire#181]
Hi.

I really liked your "wire" open source project.

I just saw this mini project: https://github.com/making/spring-mvc-tutorial-protobuf
It's about easily integrating Protobuf in Spring MVC.

However, the amazing results are only achieved using Google's own protobuf java library, not using your amazing Wire framework.
It's all about Spring's ProtobufHttpMessageConverter class which is not compatible with Wire.

I wonder if you can mimic this behavior also on Wire?

I may provide pull request if I have some time but either way I thought it's good to notice you about this nice and easy feature.

Thanks,
David.

**Comment by danrice-square** [comment]
We would welcome a PR to add this as a submodule. I haven't developed with Spring myself so it would be better for someone with Spring experience to write this class and to verify its operation.

**Comment by swankjesse** [comment]
No plans to implement this.

**Comment by kaybinwong** [comment]
@swankjesse why?

**Comment by swankjesse** [comment]
We don't use Spring! You should implement what you need & you can open source you results!
