### ISSUE TITLE
Feature request: wire-compile: generate Java annotations from "options" in ".proto" file

### ISSUE THREAD

**Issue by davidpelfree** [square/wire#183]
Hi.

I am using [Swagger](http://swagger.io)'s _@ApiModel_ and _@ApiModelProperty_ annotations in my DTOs  to automatically document my API request and response classes in Swagger. Swagger easily takes these annotations and generates live documentation where you can even invoke the API methods. (See example here: http://petstore.swagger.wordnik.com/)

I thought it would be very useful to generate my whole DTO tree of classes from a single ".proto" file instead of manually writing boiler plate Java classes. It's even more elegant than writing classes with [Lombok](http://projectlombok.org/)  _@Builder_ annotation, which is what I am doing today.

I thought that the equivalent to Java annotations in Protobuf is _[options](https://developers.google.com/protocol-buffers/docs/proto#options)_. 
Maybe it would be possible to add "com.wordnik.swagger.annotations.ApiModel" option to a Protobuf message and "com.wordnik.swagger.annotations.ApiModelProperty" option to a Protobuf field, and wire-compiler will take them and generate the appropriate Java annotations for the class and the field.

Enabling such a feature in wire-compile will leverage it to a whole new world of data-types and data-transfer-objects generation from Protobuf with the ability to annotate the classed with various frameworks stuff like [Jackson](https://github.com/FasterXML/jackson-annotations), Java JPA, Spring and more.

What do you think?
David.

**Comment by JakeWharton** [comment]
In version 2 you'll be able to plugin your own message generator (or potentially extend the built-in one) to enable this functionality. We are not going to specialize generation for a single library as that is an unsustainable model.
