### ISSUE TITLE
Wire gradle plugin is very verbose

### ISSUE THREAD

**Issue by yschimke** [square/wire#1839]
For a build system, it would be ideal if the default was no output.  But it seems to have shouty mode and chatty modes only.

https://github.com/square/wire/blob/0980bf7f46dbe58a724c5403031f368a90d2ef45/wire-library/wire-compiler/src/main/java/com/squareup/wire/ConsoleWireLogger.kt

I have a quick launcher for my project that does a quiet gradle build then launches the command.  And the only additional output is the printlns from above.

**Comment by oldergod** [comment]
If you're using the `WireCompiler` you could pass it your own `WireLogger`. For the Gradle plugin, I'll see if we can do something.

**Comment by oldergod** [comment]
Fixed with current 4 alphas.
