### ISSUE TITLE
Use JavaPoet for generated code.

### ISSUE THREAD

**Issue by mrwillis21** [square/wire#184]
Understanding this is a very contrived schema, it causes a compilation error in the output Java code:
```
message Wrapper {
    message Data {
        message DataFields {
            required string field1 = 1;
            required string field2 = 2;
            required uint32 field3 = 3;
        }
        optional DataFields fields = 1;
    }
    required Data data = 1;

    message Note {
        message Data {
            required uint64 timestamp = 1;
            required string timezone = 2;
        }
        required Data data = 1;

        message ExtraData {
            required Wrapper.Data.DataFields extra_fields = 1;
        }
        optional ExtraData meta = 2;
    }
    required Note note = 2;
}
```
Because `ExtraData` tries to use `Data.DataFields`, but there, `Data` refers to `Note.Data` (which does not have a nested `DataFields`) rather than `Wrapper.Data`.

**Comment by JakeWharton** [comment]
This probably isn't worth solving with v1. Wire v2 uses JavaWriter v3 which handles type-name collision / fully qualifiying automatically. We can use your example as a good test case though.

**Comment by swankjesse** [comment]
Good news / bad news. We switched to JavaPoet, but JavaPoet also has this bug. I'm closing this issue because it's just mirroring the JavaPoet bug that we'll fix separately.

**Comment by swankjesse** [comment]
https://github.com/square/javapoet/issues/298
