### ISSUE TITLE
Gradle Plugin Task "generateProtos" does not work anymore

### ISSUE THREAD

**Issue by StefanOltmann** [square/wire#1841]
In my project I want the plugin to generate my protobuf proxies everytime I create my Eclipse workspace or just before compiling java classes.

This _build.gradle_ does with the previous version 3.4 of the plugin exactly what I want:

```
buildscript {
  repositories {
    mavenCentral()
  }
  dependencies {
    classpath "com.squareup.wire:wire-gradle-plugin:$squareWireVersion"
  }
}

apply plugin: 'com.squareup.wire'

wire {
  java {
  }
}

tasks.eclipse.dependsOn(generateProtos)

compileJava.dependsOn(generateProtos)

[... other stuff... ]
```

After updating to the recently released version 3.5 I get this:

```
* What went wrong:
A problem occurred evaluating project ':protobuf'.
> Could not get unknown property 'generateProtos' for project ':protobuf' of type org.gradle.api.Project.
```

I don't find any hint in the release notes saying that this task is removed.

Please give me a hint what's wrong here.

**Comment by oldergod** [comment]
The task is now defined asynchronously, you would have to do something like

```groovy
afterEvaluate {
  tasks.eclipse.dependsOn(generateProtos)
  compileJava.dependsOn(generateProtos)
}
```

**Comment by StefanOltmann** [comment]
That worked. Thank you. :)
