### ISSUE TITLE
Adapt google.protobuf.*Value proto wrapper types to non-nullable kotlin types

### ISSUE THREAD

**Issue by CyrilFind** [square/wire#1846]
Hi there, i'm trying to setup Wire with gRPC

I have service routes defined in proto files such as this one:

```proto
rpc ReadPost(google.protobuf.UInt64Value) returns (Post) {}
```
This generates methods like this one:

```kotlin
override fun ReadPost(): GrpcCall<Long?, Post> =...  
```

All `google.protobuf.*Value` are adapted as Nullable types but GrpcCall doesn't accept nullables:

```kotlin
interface GrpcCall<S : Any, R : Any> (edited) 
```

after investigating more, I saw code like this in the library:  `UINT64_VALUE: ProtoAdapter<Long?>`

I found a workaround by replacing all `google.protobuf.*Value` by redefined `Custom*Value { uint64 value = 1; }`

I'm probably missing something here but I don't understand why those 2 solutions generate different code

**Comment by oldergod** [comment]
Wire treats the google wrapper types differently. In Kotlin, they are generated as nullable primitive types. The custom type you otherwise wrote is treated as a regular message type.
The incompatibility with gRPC is a bug and we'll see how we can fix it.
Thanks for reporting.

**Comment by oldergod** [comment]
Will follow up in https://github.com/square/wire/issues/1912
