### ISSUE TITLE
toJsonValue(), fromJsonValue() for Kotlin/JS

### ISSUE THREAD

**Issue by swankjesse** [square/wire#1850]
I create an object in Kotlin/JS and call `JSON.stringify()` on it:

```
var message = Message(delete_after = 10000L, type = Type.TEXT, data = "hello");
console.log(JSON.stringify(message));
```

I expect this:

```
{
  "delete_after": 10000,
  "type", "TEXT",
  "data": "hello"
}
```

But I get this:

```
{
  "delete_after": {
    "low_": 10000,
    "high_": 0
  },
  "type": {
    "name$": "TEXT",
    "ordinal$": 150,
    "value_ejbngw$_0": 840
  },
  "data_": "hello"
}
```

In particular:
 * Longs are emitted as high_, low_, not an inline value.
 * Enums are objects, not strings.
 * Fields with reserved names are emitted with the escaped name (`data_`), not the declared name (`data`).

We should add two new functions to `ProtoAdapter` for use in Kotlin/JS:

```
      open fun toJsonValue(value: T?): dynamic
      open fun fromJsonValue(value: dynamic): T?
```

And we should have a new option in KotlinTarget, `jsOutput = true` causes these methods to be implemented in the generated code. When this is used the generated Kotlin only compiles on Kotlin/JS.

**Comment by JakeWharton** [comment]
I don't think this is a wise path forward. It does nothing for Kotlin/JVM or Kotlin/Native. There's already a multiplatform serialization mechanism in kotlinx.serialization, why not generate serializers for it to enable JSON (and Javascript object) serialization on every platform?

**Comment by swankjesse** [comment]
Lets do what Jake recommends!

Add this on the Wire types:
```
@Serializable // required because of @SerialName
```

Add this on the field declarations that need it:

```
@SerialName("maintained") 
```
