### ISSUE TITLE
WireTask uses non-normalized paths and breaks Gradle build caching

### ISSUE THREAD

**Issue by ZacSweers** [square/wire#1859]
After doing some simple local build caching tests with the same project in multiple locations, build scans revealed that `WireTask` is not up to date when it should be due to using non-normalized paths in its `transforms` property

Namely - `outDirectory`

Output from a simple snippet to print it

```kotlin
tasks.withType<WireTask>().configureEach {
  doFirst { println(transforms) }
}
```

```
KotlinTarget(includes=[*], excludes=[], exclusive=true, outDirectory=/Users/zsweers/dev/slack/slack-android-ng/telemetry-definitions/build/generated/source/wire, android=false, javaInterop=false, emitDeclaredOptions=true, emitAppliedOptions=false, rpcCallStyle=SUSPENDING, rpcRole=CLIENT, singleMethodServices=false)
```

**Comment by staktrace** [comment]
Note that the inputFiles task property as well as the targets.outDirectory are both non-normalized. I have a fix for the inputFiles normalization which is pretty straightforward, but dealing with targets.outDirectory is more involved.

**Comment by staktrace** [comment]
https://github.com/square/wire/pull/1994 fixes this for me locally.
