### ISSUE TITLE
Wrong identifiers in KDOC make the compilation fails

### ISSUE THREAD

**Issue by oldergod** [square/wire#1869]
Something like
```protobuf
  // Not related to [ISO.8601.2003].
  string address = 2;
```
will generate
```kotlin
  /**
   * Not related to [ISO.8601.2003].
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY
  )
  @JvmField
  public val address: String = "",
```
which won't compile because the identifier `8601` starts with a digit.

https://kotlinlang.org/spec/syntax-and-grammar.html#identifiers

**Comment by Egorand** [comment]
Are brackets in the proto used for stylistic purposes only, or are they expected to be interpreted by the code generator in a certain way?

**Comment by JakeWharton** [comment]
Opening square brackets should probably be escaped since proto comments are not markdown but Kotlin ones are.
