### ISSUE TITLE
Update Wire's Swift generation to add default values enum

### ISSUE THREAD

**Issue by pickens117** [square/wire#1871]
Currently, without the default value available in the proto, the values are left to be hard coded somewhere else in the client. These values may not be in the client. It’s unlikely for the default values in the original proto definitions to change, but if they did, client code would all of a sudden be broken.

**Proposal**
Generate default values and make them available as constants wrapped in a Defaults enum on the proto. Fields will continue to be nil values and not the defaults.

**Example**

```
public struct Sample {
    public enum Defaults {
        static let compass: Compass = .WEST
        static let state: State = .NEW
    }
    
    public var compass: Compass?
    public var state: State?
    
    public init(compass: Compass? = nil, state: State? = nil) {
        self.compass = compass
        self.state = state
    }
    
    public enum Compass: UInt32, CaseIterable, Codable {
        case NORTH
        case EAST
        case SOUTH
        case WEST
    }
    
    public enum State: UInt32, CaseIterable, Codable {
        case NEW
        case OLD
    }
}
```

**Comment by efirestone** [comment]
This API proposal looks great. Now just a matter of implementing...

**Comment by lickel** [comment]
An alternative I discussed with @dnkoutso: we could use a property wrapper to return a projected non-nil value

Eg @Defaulted(value: 8) var count: Int? -> $count: Int
