### ISSUE TITLE
Wire tag do not exists in StackOverflow

### ISSUE THREAD

**Issue by joaoeudes7** [square/wire#1890]
Hi, please changes the link to StackOverflow on page of project, the tag wire do not exists and to better difference on names of technologies change to `square-wire`

Changes:
[https://stackoverflow.com/questions/tagged/wire?sort=active](https://stackoverflow.com/questions/tagged/wire?sort=active)
to 
[https://stackoverflow.com/questions/tagged/square-wire?sort=active](https://stackoverflow.com/questions/tagged/square-wire?sort=active)

Page: https://square.github.io/wire/

XPath: `/html/body/div[3]/main/div/div[1]/div/div/nav/ul/li[4]/a`

**Comment by oldergod** [comment]
Thanks
