### ISSUE TITLE
generateMainProtos fails with AGP 7.0.0-alpha07

### ISSUE THREAD

**Issue by kozaxinan** [square/wire#1898]
After changing from alpha06 to alpha07, build fails at generateMainProtos.

```
Caused by: java.lang.NoSuchFieldError: Companion
at com.squareup.wire.schema.RootKt.<clinit>(Root.kt:192)
at com.squareup.wire.schema.SchemaLoader.allRoots(SchemaLoader.kt:172)
at com.squareup.wire.schema.SchemaLoader.initRoots(SchemaLoader.kt:84)
at com.squareup.wire.schema.WireRun.execute(WireRun.kt:219)
at com.squareup.wire.schema.WireRun.execute(WireRun.kt:213)
at com.squareup.wire.schema.WireRun.execute$default(WireRun.kt:211)
at com.squareup.wire.gradle.WireTask.generateWireFiles(WireTask.kt:124)
```

Build Dependencies
7.0.0-alpha06 | 7.0.0-alpha07
------------ | -------------
<img width="562" alt="Screenshot 2021-02-23 at 22 41 30" src="https://user-images.githubusercontent.com/2559837/108898610-734b0d80-7628-11eb-9a81-d21fc42d3ee4.png"> | <img width="613" alt="Screenshot 2021-02-23 at 22 41 21" src="https://user-images.githubusercontent.com/2559837/108898640-7b0ab200-7628-11eb-91d9-4f2b43667b63.png">

It is most likely not about wire plugin but I couldn't find the root cause of the issue. 
Let me know what other information I can provide.

**Comment by kozaxinan** [comment]
Checked build dependencies for okio usage. We don't directly use okio.  

<img width="367" alt="Screenshot 2021-02-24 at 21 13 35" src="https://user-images.githubusercontent.com/2559837/109045877-2b3df080-76e5-11eb-9659-b1adbda560de.png">

Adding latest okio into buildSrc gradle dependencies resolved the issue. But I wonder why it isnt and issue with older version of AGP.

```
 implementation "com.squareup.okio:okio:2.10.0"
```

**Comment by kozaxinan** [comment]
`io.grpc:grpc-all:1.21.1` is the dependency that bring old okio into build dependencies. Even the latest version of `io.grpc:grpc-all:1.36.0` doesnt use okio 2.x version. (uses 1.17.5). 
This can only happen if you have agp dependency in buildSrc. 
I will replace `com.android.tools.build:gradle` with `com.android.tools.build:gradle-api`. That should fix issue for us.

Obliviously there is nothing wire plugin can do in this situations.

**Comment by oldergod** [comment]
Thank you for digging into it!
