### ISSUE TITLE
GRPC: 'Nothing' return type needs to be specified explicitly

### ISSUE THREAD

**Issue by RdeWilde** [square/wire#1903]
When I generate my rpc-services from .proto-file using Wire, I get this error in the `GreeterWireGrpc`-file.

This is an example:
```
  public abstract class GreeterImplBase : BindableService {
    public open fun sayHello(request: HelloRequest, response: StreamObserver<HelloReply>) = throw
        UnsupportedOperationException()
```
Produces this error:
```
'Nothing' return type needs to be specified explicitly
```
Should this have a return type (Unit) added?
https://github.com/square/wire/blob/ce5ff17d6176f85cc4084d8b271a7cae0f3f03c3/wire-library/wire-grpc-server-generator/src/main/java/com/squareup/wire/kotlin/grpcserver/ImplBaseGenerator.kt#L60

Also it is missing this class: `GreetersayHelloBlockingServer` used in the `GreeterImplLegacyAdapter` like this:
```
private val sayHello: () -> GreetersayHelloBlockingServer
```
Should we leave `${rpc.name}` out? Or should it have created a server per `${rpc.name}` although I did not set the option in gradle?
https://github.com/square/wire/blob/ce5ff17d6176f85cc4084d8b271a7cae0f3f03c3/wire-library/wire-grpc-server-generator/src/main/java/com/squareup/wire/kotlin/grpcserver/LegacyAdapterGenerator.kt#L80

Three lines below this, there's another error about `Unit` as return type

This is in my gradle file:
```
wire {
    kotlin {
        rpcCallStyle = "blocking" // suspending
        rpcRole = "server"
        grpcServerCompatible = true
        singleMethodServices = false
    }

    java {}
}
```
Proto:
```
// The greeting service definition.
service Greeter {
  // Sends a greeting
  rpc sayHello (HelloRequest) returns (HelloReply) {}
}
```
Why does it even give me a StreamObserver for HelloReply?

What am I missing? Can this be resolved?

PS. Is there a Slack or Discord or something for this community?

**Comment by RdeWilde** [comment]
Maybe this is relevant for the `Nothing` and Unit `errors`
https://github.com/square/wire/pull/1587

**Comment by RdeWilde** [comment]
It seems like adding a return type to the `${rpc.name}()` / `sayHello()` method in the `GreeterImplBase` (extending `BindableService`)

So changing this:
```
  public abstract class GreeterImplBase : BindableService {
    public open fun sayHello(request: HelloRequest, response: StreamObserver<HelloReply>) = throw
        UnsupportedOperationException()
```
to this
```
  public abstract class GreeterImplBase : BindableService {
    public open fun sayHello(request: HelloRequest, response: StreamObserver<HelloReply>): Unit = throw
        UnsupportedOperationException()
```

Does this relate to me using the Google `Empty` type in the RPC def?

**Comment by RdeWilde** [comment]
Is there any way to get support for an issue like that? Maybe some commercial support or anything?

**Comment by aarnaut** [comment]
I think this one can be closed.
