### ISSUE TITLE
Are there any testing utilities similar to KrotoPlus's Mock services?

### ISSUE THREAD

**Issue by carterhudson** [square/wire#1924]
I'm migrating from kroto to Wire, and I already have a lot of unit tests written using Kroto's mock services, like so:
```kotlin
    @Test
    fun `recoverable errors should retry MAX_RETRY_ATTEMPTS times and should return a failure with status`() =
        runBlockingTest {
            val recoverableStatus = GRPC_RECOVERABLE_STATUSES.first()
            val responseQueue = MockTracking.batchReportEventsResponseQueue
            val times = TrackingClient.Rules.MAX_RETRY_ATTEMPTS

            assertThat(responseQueue.isEmpty()).isEqualTo(true)

            responseQueue.apply {
                repeat(times) {
                    addError(recoverableStatus)
                }
            }

            assertThat(responseQueue.size).isEqualTo(times)
            val errorResult = client.reportEvents(listOf(EVENT_VALID_ID))
            assertThat(errorResult).isEqualTo(EventReporter.Result.Failure(status = recoverableStatus))
            assertThat(responseQueue.isEmpty()).isEqualTo(true)
        }
```

Is there anything similar available for Wire? I've googled, but "wire" is such a generic term when referring to gRPC stuff that it makes searching kind of useless. I didn't see anything in the issues, either. I'm already aware of [implementing client interfaces](https://square.github.io/wire/wire_grpc/#implementing-client-interfaces), but was hoping to avoid writing boilerplate and keep my tests reasonably similar.

**Comment by oldergod** [comment]
This is how we test it https://github.com/square/wire/tree/master/wire-grpc-tests/src/test/java/com/squareup/wire

**Comment by carterhudson** [comment]
Thanks, I'll check this out.
