### ISSUE TITLE
Gradle plugin prints output directory as warning

### ISSUE THREAD

**Issue by ChrisCraik** [square/wire#1952]
Gradle plugin's `:generateDebugProtos` task prints an output like the following as a warning:
```
Writing androidx.benchmark.macro.protos.TestProto to $OUT_DIR/androidx/benchmark/benchmark-macro/build/generated/source/wire
```
These should be instead printed as info, so that they don't show up as warnings.

**Comment by oldergod** [comment]
Thank you, this is fixed on master via https://github.com/square/wire/pull/1936
