### ISSUE TITLE
compilation of message fails due to invalid comment syntax

### ISSUE THREAD

**Issue by jwueller** [square/wire#196]
Java comments support unicode escape sequences. In unlucky circumstances, this can prevent the wire compiler from producing valid Java source files on Windows, if there is a path component starting with `u`:

    // Code generated by Wire protocol buffer compiler, do not edit.
    // Source file: repo\utilities.proto

This does not compile.

My suggestion would be to uniformly format paths with forward slashes only, making the generated files identical across platforms. This would also help with version control. 

Alternatively, `\u` needs to be escaped upon writing for this to work with arbitrary paths.

**Comment by JakeWharton** [comment]
Thanks for the report! Will fix soon.

**Comment by JakeWharton** [comment]
Ugh, our testing strategy prohibits an easy way to write a regression test for this...
