### ISSUE TITLE
UnknownFields param

### ISSUE THREAD

**Issue by tronku** [square/wire#1960]
Is there any way to generate Kotlin class without `unknownfields` param in the constructor?

I am using the generated Kotlin class in a Java class so can't use the default param and `@JvmOverloads` annotation.
When I generate the same proto in Java class, then wire generates two constructors - one with unknownfield, other without it.

**Comment by oldergod** [comment]
Generate a second constructor without `unkownfields` isn't doable right now. In our project, for java consumer, we instantiate all protos using the builder.

**Comment by tronku** [comment]
is there any extra option to generate a class with the builder?? I am not able to use the builder pattern in my java code.

**Comment by oldergod** [comment]
Yes, it's `javaInterop = true`
https://square.github.io/wire/wire_compiler/#kotlin

**Comment by tronku** [comment]
Thanks! it worked! closing the issue.
