### ISSUE TITLE
[Feature Request] Protocol-agnostic service client interfaces

### ISSUE THREAD

**Issue by benjamin-bader** [square/wire#1962]
I'm interested in using Wire to help our app talk to our backends, which speak Twirp.  (tl;dr: Twirp is basically "protobuf over HTTP 1.1").  The current implementation of `RpcRole.CLIENT` assumes gRPC.  Would you be open to adding an RpcRole that doesn't require a specific protocol?

`RpcRole.SERVER` is nearly ideal - the two drawbacks being that `WireRpc` is runtime-retained (not a dealbreaker), and also that the generated interface names have a `Server` suffix, which isn't great in a client context.  In my ideal world this hypothetical `RpcRole.GENERIC` would produce an interface only, with neither `Client` nor `Server` added to the name.

Is this something that you'd accept in a PR?

For clarity's sake, given this proto:

```proto
package tacotruck;

service TacoService {
  rpc FetchTacos(FetchTacosRequest) returns (FetchTacosResponse)
}
```

and this gradle plugin config:

```gradle
wire {
  kotlin {
    rpcRole = "generic"
  }
}
```

we'd get the following interface:

```kt
public interface TacoService : Service {
  @WireRpc(
      path = "/tacotruck.TacoService/FetchTacos",
      requestAdapter = "tacotruck.FetchTacosRequest#ADAPTER",
      responseAdapter = "tacotruck.FetchTacosResponse#ADAPTER")
  public suspend fun FetchTacos(request: FetchTacosRequest): FetchTacosResponse
}
```

(I guess we could get by with typealiasing `TacoServiceServer` to `TacoService`, or just living with the naming incongruity)

**Comment by swankjesse** [comment]
I like it. I don't think `generic` is the best name for this. The big feature here is `suspend`, otherwise it's difficult to make this work as a client because there's no call object.

Maybe `suspending` instead of `generic`? It's not exactly a role but I think it conveys the behavior nicely.

**Comment by benjamin-bader** [comment]
I didn't reach for "suspending" here because that's already governed by `rpcCallStyle`.  It seems weird to allow for

```
wire {
  kotlin {
    rpcRole = "suspending"
    rpcCall = "blocking" // why would you ever do that?  beats me.
  }
}
```

Agreed that "generic" isn't a great name; I struggled with that.  Maybe "none"?

**Comment by swankjesse** [comment]
Another option: wanna just use rpcRole and we can add an option to configure the suffix of the generated interface?
```
wire {
  kotlin {
    rpcRole = "server"
    nameSuffix = "" // null for the default suffix, Server
  }
}
```

**Comment by benjamin-bader** [comment]
Amazing.  Let's do that instead - small changes ftw!
