### ISSUE TITLE
Any way to avoid Java 8 time classes? Desugaring breaking third-party dependencies.

### ISSUE THREAD

**Issue by carterhudson** [square/wire#1964]
When we use `coreLibraryDesugaring` in our app, it seems like it's adding incorrect code to a third-party dependency that causes debug builds, built from the command line, to crash at runtime (https://issuetracker.google.com/issues/187977749). What I'm wondering is if there is a way to avoid using `Instant` and other Java 8 time classes so that we don't need desugaring in the first place?

**Comment by oldergod** [comment]
I don't think we do, no.
If you're not using this field, you could prune it. If you're using it, we need something. Maybe an option which would fall back to our native/js implementation 
```kotlin
actual class Duration internal constructor(
  private val seconds: Long,
  private val nanos: Int
) {
  actual fun getSeconds(): Long = seconds
  actual fun getNano(): Int = nanos
}

actual fun durationOfSeconds(
  seconds: Long,
  nano: Long
): Duration {
  val s = addExactLong(seconds, floorDivLong(nano, NANOS_PER_SECOND))
  val ns = floorModLong(nano, NANOS_PER_SECOND).toInt()
  return Duration(s, ns)
}
```
