### ISSUE TITLE
"Ambiguous Reference" error when importing classes with the same name

### ISSUE THREAD

**Issue by mhahn** [square/wire#200]
i have something like the following:

services/profile/actions/get_profile.proto
```
message RequestV1 {
     ...parameters
}
```
services/user/actions/get_user.proto
```
message RequestV1 {
    ...parameters
}
```

services/registry/requests.proto
```
import "services/profile/actions/get_profile.proto";
import "services/user/actions/get_user.proto";

extend ActionRequestParamsV1 {
    optional services.user.actions.get_user.RequestV1 get_user = 1;
    optional services.profile.actions.get_profile.RequestV1 get_profile = 2;
}
```

wire generates the files without error and the result is:

```
public final class Ext_requests {
  public static final Extension<ActionRequestParamsV1, RequestV1> get_user = Extension
      .messageExtending(RequestV1.class, ActionRequestParamsV1.class)
      .setName("services.registry.requests.get_user")
      .setTag(1)
      .buildOptional();
  public static final Extension<ActionRequestParamsV1, RequestV1> get_profile = Extension
      .messageExtending(RequestV1.class, ActionRequestParamsV1.class)
      .setName("services.registry.requests.get_profile")
      .setTag(2)
      .buildOptional();
}
```

which causes an error around an ambiguous reference to `RequestV1`.

I believe the only solution is to use the fully qualified name to access the request, but I'm new to java.

Any thoughts?

**Comment by JakeWharton** [comment]
This will be fixed by switching from JavaWriter to emit the code to JavaPoet, the latter of which does import conflict resolution automatically.

**Comment by JakeWharton** [comment]
I realize none of that may make sense as a user of the library. Bottom line: we can fix it, but it requires work.

**Comment by mhahn** [comment]
Is there something open to track the progress on that? My company is using protobufs extensively and just starting work on the android app. It's going to be a pain in the ass (or at least some additional work) for us to re-write the full paths in that file. I'd rather contribute to getting it done correctly.

**Comment by JakeWharton** [comment]
Tracking at #184. Closing this in favor of that issue.
