### ISSUE TITLE
Kotlin compiler generates methods with more than 255 parameters

### ISSUE THREAD

**Issue by sakulisko** [square/wire#2010]
Hello,
if proto message contains more than 255 fields it generates the `copy` method with the same number of parameters. This will fail in JVM environment because the jvm supports up to 255 parameters https://docs.oracle.com/javase/specs/jvms/se16/html/jvms-4.html#jvms-4.3.3. 

The kotlin file looks fine and kotlinc is able to compile *.kt to *.class without any issue. But it's not possible to use *.jar with these *.class files in android project.

The same issue was already resolved for java compiler: https://github.com/square/wire/issues/691
Another issue related to high number of fields: https://github.com/square/wire/issues/1575

Possible solutions:
- Limit the number of parameters in the same way as for java output and behave in the same way as `java_interop = true`, when the limit is reached
- Change how the generated message looks like. Use DSL-like syntax instead of named parameters (https://proandroiddev.com/writing-kotlin-dsls-with-nested-builder-pattern-66452476d5ef). This can be controlled by compiler flag to keep backward compatibility

Unfortunately both of the solutions can cause breaking changes in generated *.kt files

**Comment by oldergod** [comment]
What's causing your proto schema to have that many fields? Do you have a big oneof in there?

**Comment by sakulisko** [comment]
It's flat structure. The proto is generated from web-ui. No oneof, just message with many fields.

**Comment by oldergod** [comment]
Unfortunately there is no solution around this for now. The feature we've been working on in https://github.com/square/wire/issues/1448 will address very long oneof only.
