### ISSUE TITLE
Documentation does not mention the dependency required to generate server side code for a plain server

### ISSUE THREAD

**Issue by aarnaut** [square/wire#2011]
Documentation does not state that you have to add a dependency to ```com.squareup.wire:wire-grpc-server``` in order to generate server-side code for a plain server. Failing to add this dependency results in unresolved references to ```MessageSourceAdapter``` and ```MessageSinkAdapter```. 

I'm unsure if what I did is the right way to fix it, but it did help. I would be happy to update the docs as well if this is correct.

**Comment by oldergod** [comment]
Thank you. If you'd like to push a PR which updates the doc for a more helpful one, that would be great.
