### ISSUE TITLE
Support fully qualified type names parsing non-scalar fields in ProtoParser

### ISSUE THREAD

**Issue by blacktooth** [square/wire#2024]
I am using `ProtoParser` to parse below Protobuf file to a `ProtoFileElement` using following code,

```
syntax = "proto3";

package com.foo.bar;

message Address {
  string street = 1;

  int32 zip = 2;

  string city = 3;
}

message Customer {
  string name = 1;
  Address address = 3;
}

```

```
ProtoFileElement protoFileElement = ProtoParser.Companion.parse(Location.get(""), schema);
MessageElement msgElement = (MessageElement) protoFileElement.getTypes().get(1);
FieldElement addressField = msgElement.getFields().get(1);
```

**Contents of AddressField**
```
FieldElement(location=:15:3, label=REQUIRED, type=Address, name=address, defaultValue=null, jsonName=null, tag=3, documentation=, options=[])
```

The type of `addressField` is set to `Address`. However, the Protobuf Java compiler recognizes it's type as `.com.foo.bar.Address` [Reference](https://developers.google.com/protocol-buffers/docs/proto#packages_and_name_resolution)

Can the type names for non-scalar types be updated to have fully qualified names?

**Comment by JakeWharton** [comment]
The parser is _solely_ that: a parser. It does not perform linking where types of fields are actually resolved and replaced with fully-qualified references. For that you'll want `Schema` (or more accurately `SchemaLoader`).

**Comment by blacktooth** [comment]
I tried using the `SchemaLoader` using below code but it didn't resolve the fully-qualified type names for internal references.

```
        FileSystem jimfs = Jimfs.newFileSystem(Configuration.unix());
        Path path = jimfs.getPath("/schema.proto");
        Files.write(path, rawSchema.getBytes());

       SchemaLoader schemaLoader = new SchemaLoader(jimfs);
       schemaLoader.initRoots(Lists.newArrayList(Location.get("/")), Lists.newArrayList(Location.get("/")));
       
       MessageElement msgElement = ((MessageElement) schemaLoader.load("/schema.proto").toElement().getTypes().get(1));
       msgElement.getFields().get(1)
```
It still doesn't have the fully-qualified reference,

```
FieldElement(location=/schema.proto:15:3, label=REQUIRED, type=Address, name=address, defaultValue=null, jsonName=null, tag=3, documentation=, options=[])
```

Am I missing something?

**Comment by swankjesse** [comment]
That's surprising. Wanna send an executable test case?

**Comment by swankjesse** [comment]
Or maybe I can derive one from this....

**Comment by JakeWharton** [comment]
You're still accessing the element types rather than the schema types. Once you get a `Schema`, you should be calling `getType(..)` or `getService(..)`. The list of types are available as `getTypes()` which returns a set. Calling `toElement()` anywhere will throw away all linking information and produces types which represent only the AST of proto files.

**Comment by blacktooth** [comment]
Here's a working test case,

```
@Test
    public void test_IdentifiesReferencedType() throws Exception {
        String rawSchema = "syntax = \"proto3\";\n"
            + "\n"
            + "package com.foo.bar;\n"
            + "\n"
            + "message Address {\n"
            + "  string street = 1;\n"
            + "\n"
            + "  int32 zip = 2;\n"
            + "\n"
            + "  string city = 3;\n"
            + "}\n"
            + "\n"
            + "message Customer {\n"
            + "  string name = 1;\n"
            + "  Address address = 3;\n"
            + "}";
        FileSystem jimfs = Jimfs.newFileSystem(Configuration.unix());
        Path path = jimfs.getPath("/schema.proto");
        Files.write(path, rawSchema.getBytes());

        SchemaLoader schemaLoader = new SchemaLoader(jimfs);
        schemaLoader.initRoots(Lists.newArrayList(Location.get("/")), Lists.newArrayList(Location.get("/")));

        ProtoFile protoFile = schemaLoader.load("/schema.proto");

        MessageType messageType = (MessageType) protoFile.getTypes().get(1);

        Field addressField = (Field) messageType.getDeclaredFields().get(1);

        assertEquals(".com.foo.bar.Address", addressField.getType());
    }
```

The assertion fails as `getType` returns `null`

```
org.opentest4j.AssertionFailedError: 
Expected :.com.foo.bar.Address
Actual   :null
```

**Contents of `addressField`**

```
result = {Field@2205} "address"
 type = null
 deprecated = null
 isRedacted = false
 encodeMode = null
 jsonName = null
 packageName = "com.foo.bar"
 location = {Location@2538} "/schema.proto:15:3"
 label = null
 name = "address"
 documentation = ""
 tag = 3
 default = null
 elementType = "Address"
 options = {Options@2542} 
 isExtension = false
 isOneOf = false
 declaredJsonName = null
```

**Comment by blacktooth** [comment]
@JakeWharton were you able to replicate the problem?

**Comment by oldergod** [comment]
Ravindranath, can you explain a bit what you're actually trying to achieve, or what is blocking you?
Do you wanna be able to retrieve a type using its qualified name, such as `.com.foo.bar.Address` ?

**Comment by blacktooth** [comment]
I am building schema registry application for Protobuf. As part of it, I am developing a Protobuf schema normalizer that parses a `.proto` file into `ProtoFileElement` and translates it into `FileDescriptorProto` ([Code](https://github.com/Apicurio/apicurio-registry/blob/master/utils/protobuf-schema-utilities/src/main/java/io/apicurio/registry/utils/protobuf/schema/FileDescriptorUtils.java#L100)). The `FileDescriptorProto` will be stored in DB and later used to compare against `FileDescriptorProto` retrieved from `Message` objects. 

When I get the `FileDescriptorProto` for a `Message` of below schema, Protobuf compiler adds the fully qualified type name `.com.foo.bar.Addres` for `address` field. However, with wire library, it's `null`. 

I can write my own implementation on top of this to resolve the type but want to know if it is something supported by 
this library. 

```
syntax = "proto3";

package com.foo.bar;

message Address {
  string street = 1;

  int32 zip = 2;

  string city = 3;
}

message Customer {
  string name = 1;
  Address address = 3;
}
```

**Comment by oldergod** [comment]
You need to ask Wire to link the schema, namely to resolve all types. This is done via the `SchemaLoader#loadSchema` method.

Here is what you should see when it's done.
![image](https://user-images.githubusercontent.com/1767669/128103925-0bb0fccd-df71-4634-892f-8ba4aa64ec6d.png)

I don't think we have documentation for this yet but we're working on something that directly goes from a `.proto` to a `FileDescriptorProto` as you seem to be doing. This would be inside wire-reflector: https://github.com/square/wire/tree/master/wire-library/wire-reflector

**Comment by blacktooth** [comment]
Thanks! The above information is useful!
