### ISSUE TITLE
Cannot access GrpcStatus of a failed request

### ISSUE THREAD

**Issue by alexvasilkov** [square/wire#2026]
Our gRPC API can return `UNAUTHENTICATED` status code (as defined [here](https://github.com/grpc/grpc/blob/master/doc/statuscodes.md)). I would like to catch and handle this error but the library throws a generic `IOException` which does not provide the received gRPC status code, see [line #174 in grpc.kt](https://github.com/square/wire/blob/989e287/wire-library/wire-grpc-client/src/jvmMain/kotlin/com/squareup/wire/internal/grpc.kt#L174).

If there were no `transportException` then I would get a correct behavior (`GrpcException` with `GrpcStatus` is thrown), but I don't think I can avoid this `transportException`.

My RPC method is defined like this: `rpc RemoveMedia(RemoveMediaRequest) returns (AcknowledgeResponse) {}`, so the library is expecting a message in response and fails with `java.net.ProtocolException: expected 1 message but got none` if API returned no message along with `UNAUTHENTICATED` status. This `ProtocolException` exception becomes `transportException` which prevents `GrpcException` from being thrown.

Can we throw the `GrpcException` whenever `grpcStatus != "0"` regardless of `transportException`? Or is there something wrong with how our gRPC API is designed?

I can manually parse `grpc-status` header from OkHTTP interceptor, but it doesn't feel right.

**Comment by LaurentTreguier** [comment]
I have hit the same problem and tried looking at where the code goes during debugging.
From [grpc.kt](https://github.com/square/wire/blob/master/wire-library/wire-grpc-client/src/jvmMain/kotlin/com/squareup/wire/internal/grpc.kt):

```kotlin
  if (transportException != null) {
    return IOException(
        "gRPC transport failure" +
            " (HTTP status=$code, grpc-status=$grpcStatus, grpc-message=$grpcMessage)",
        transportException
    )
  }

  if (grpcStatus != "0") {
    val grpcStatusInt = grpcStatus?.toIntOrNull()
      ?: throw IOException(
          "gRPC transport failure" +
              " (HTTP status=$code, grpc-status=$grpcStatus, grpc-message=$grpcMessage)"
      )

    return GrpcException(GrpcStatus.get(grpcStatusInt), grpcMessage)
  }
```

It looks like the problem could come from the first `if`, in the second `if` a `GrpcException` is returned if possible, but not in the first one. If the same code was applied to both `if`s, maybe a `GrpcException` would be generated properly ?

**Comment by KostadinAlmishev** [comment]
I think library is expecting empty result when exception happens, but there is null. Same problem here.

**Comment by rekaszeru** [comment]
I'm facing the same problem, and afaik grpc should not have any content when there's a non-0 code (error) in the response. In my reading this is a _bad_ bug, and having to parse the `IOException`'s message as a workaround is like using an axe on the whole concept. When can we expect a fix?

**Comment by MehdiAghajani** [comment]
we are facing the same problem and also we need all trailers with 'GrpcException' to do some actions based on server error response which is not provided currently.

**Comment by oldergod** [comment]
It looks like OkHttp had a fix a while ago: https://github.com/square/okhttp/commit/480c20e46bb1745e280e42607bbcc73b2c953d97

I'll update OkHttp version and we should get fixed.

**Comment by eschgi** [comment]
Hi,

the bug still seems to exist.

I use the following versions:
* okhttp: 4.10.0
* wire-grpc-client: 4.4.3

In the backend I use the grpc-dotnet implementation.

@oldergod Can you please reopen the ticket? Thanks.

**Comment by eschgi** [comment]
Hi @oldergod,

should I open a new ticket?

**Comment by oldergod** [comment]
Hey @eschgi you can open a ticket, yes. The most efficient way to get closer to a fix would be to write a failing test if you feel like to.

**Comment by DoumanAsh** [comment]
Does okhttp handles trailing headers?
I noticed that google cloud proxy might re-arrange grpc-status and grpc-message away from rest of grpc headers, and I see in logs that okhttp is missing `grpc-status` and `grpc-message` headers even though I can see in cloud logs that status is definitely set to error

**Comment by oldergod** [comment]
@DoumanAsh yes it does https://github.com/square/okhttp/blob/f2771425cb714a5b0b27238bd081b2516b4d640f/okhttp/src/main/kotlin/okhttp3/Response.kt#L194

**Comment by DoumanAsh** [comment]
I see, I need to check how it works in 5.1.0 and come up with reproduction I guess
For some reason since upgrade to 5.1 from 4.x we had this issue on errors that grpc-details-bin is presents while other mandatory fields are missing so we have to downgrade to find working version

**Comment by DoumanAsh** [comment]
@oldergod I was reviewing code again and I actually had misunderstanding
It seems when IO exceptions happen previously (due to attempt to ready empty body which returns obviously empty message) wire will not read trailers?

I'm not sure what is intention here, but in any case it seems root cause of my issue was due to wire client not handling empty response (which is normal for error response in GRPC) correctly
https://github.com/square/wire/blob/8c3dce80d51d785184139619b150f79785cc7d1f/wire-grpc-client/src/jvmMain/kotlin/com/squareup/wire/internal/grpc.kt#L208

**Comment by karthi2007** [comment]
@oldergod I am encountering the same scenario where the library throws `IOException : ProtocolException("expected 1 message but got none")` when trying to read response body. 
Note: Backend uses connect library for the grpc server. 

Q: what is the wire library expectation of response body when server sends error response? (Currently my server sends grpc-status and message)

**Comment by oldergod** [comment]
@karthi2007 here's our test case for this https://github.com/square/wire/blob/master/wire-grpc-tests/src/test/java/com/squareup/wire/GrpcClientTest.kt#L1321-L1339
