### ISSUE TITLE
Example of a custom mapper/type adapter?

### ISSUE THREAD

**Issue by ivanr** [square/wire#2027]
From the documentation and some issues I believe there might be a way to use Wire with custom mappers. Is there an example of how that might work?

I am largely interested in adding support for new Java classes that map to protocol buffer primitives. For example InetAddress (string) and X509Certificate (bytes), in the first instance.

I am primarily interested in Java, but I may be able to write some Kotlin code need be.

Thanks.

**Comment by oldergod** [comment]
It's very much subject to change but you can find some example in `ProfileLoaderTest`. Naming your profile file `java.wire` or `android.wire` should be enough for `Wire` to find about it and use the defined adapter.
Note that it won't work for Kotlin generation.
