### ISSUE TITLE
Sink already folded

### ISSUE THREAD

**Issue by DiGorVi** [square/wire#2030]
Hello. When calling the StartDeviceStream method, the following error occurs. Tested on versions 3.6.1, 3.7.0, 4.0.0-alpha.5

<img width="868" alt="Снимок экрана 2021-07-28 в 18 27 31" src="https://user-images.githubusercontent.com/52032668/127350481-4d111bb7-2ae9-475a-a46d-505608dc952a.png">
<img width="753" alt="Снимок экрана 2021-07-28 в 18 30 04" src="https://user-images.githubusercontent.com/52032668/127350962-0a66f309-e50c-4f5f-bb66-28ada3aa3638.png">
<img width="983" alt="Снимок экрана 2021-07-28 в 18 30 35" src="https://user-images.githubusercontent.com/52032668/127351050-52a26523-3403-499c-ad34-84a530e3986e.png">
<img width="553" alt="Снимок экрана 2021-07-28 в 18 36 29" src="https://user-images.githubusercontent.com/52032668/127352116-92dd6831-2130-4fac-bcf4-ac905658239e.png">
<img width="723" alt="Снимок экрана 2021-07-28 в 18 37 46" src="https://user-images.githubusercontent.com/52032668/127352346-c9f64c39-7310-4062-9e4e-f6b776de7219.png">

**Comment by oldergod** [comment]
Probably related with the `OkHttp3Interceptor`. Can you opt out of this and see how it goes?

**Comment by DiGorVi** [comment]
I don't add an Interceptor for OkHttpClient

**Comment by DiGorVi** [comment]
I made a mistake, this error occurs when using two grpc clients. I use two clients to remove cyclic dependencies. Separately, everything works fine, but when using two clients at the same time, the methods with streams do not work.

<img width="723" alt="Снимок экрана 2021-07-29 в 10 40 26" src="https://user-images.githubusercontent.com/52032668/127451691-75882728-9cf1-4b3b-ac43-4cfe46f7e2f9.png">
<img width="529" alt="Снимок экрана 2021-07-29 в 10 40 57" src="https://user-images.githubusercontent.com/52032668/127451768-ed90379e-267e-410c-9879-6a1cdb18c0e3.png">

**Comment by Y2Kot** [comment]
I have the same problem when I'm creating two clients: one basic and one with interceptor (adding header too). Any solutions?

**Comment by BoD** [comment]
I've just opened an issue on Android Studio's bug tracker [here](https://issuetracker.google.com/issues/235863810).

**Comment by Vlad-M-1** [comment]
The problem still occurs.
And it is unclear how to disable network profiler on Android Studio Giraffe.

**Comment by ln-12** [comment]
I am having the same problem while using grpc/connect-kotlin streaming calls which also use OkHttp under the hood, see https://github.com/connectrpc/connect-kotlin/issues/153. Flipper also does not corretly handle the streaming case, see https://github.com/facebook/flipper/issues/5294.

Is there no workaournd possible for these debugging case? Many tools seem to work like that and cause issues so fixing it here would benefit them all. Maybe some debugging option/flag that does not affect release builds?

**Comment by stanislavnastasiu-dev** [comment]
I got the same error and ended up here. So there is still no way on using a streaming call?
I'm currently using v4.9.3

**Comment by Vlad-M-1** [comment]
In the newest version of Android Studio even layout inspector crashes the app when GRPC streams are used.

Is there really no hope for this getting fixed? 

I liked this library but I'm starting to think about migrating back to the google's grpc generator, cause it's getting quite uncomfortable. I'd prefer to be able to use Android Studio's layout and network inspectors.

**Comment by hamzasdsol** [comment]
Any update on this? The issue is closed but still not fixed.

**Comment by Vlad-M-1** [comment]
I wonder if devs are getting notifications about comments for this issue, considering that it's marked as closed. Maybe we mention someone explicitly, but I'm not sure.

**Comment by oldergod** [comment]
_maybe_ related https://github.com/square/wire/pull/2791

**Comment by rndhacker** [comment]
When is this change shipping to a new version?

**Comment by Vlad-M-1** [comment]
Still happens with wire 4.9.7. The app is crashing when profiler is used.

My current workaround to prevent the crash: 
• Add an OkHttp interceptor which catches IllegalStateException with message "sink already folded" and wraps it into okio.IOException
• Catch the exception like a regular exception where the request is executed

The reason for the wrapping is:
>We consider other exceptions like IllegalStateException to be application crashes and do not send them over thread boundaries because we don’t want to burden most callers with catching them.

https://stackoverflow.com/a/58711127/3971523

**Comment by stanislavnastasiu-dev** [comment]
> Still happens with wire 4.9.7. The app is crashing when profiler is used.
> 
> My current workaround to prevent the crash: • Add an OkHttp interceptor which catches IllegalStateException with message "sink already folded" and wraps it into okio.IOException • Catch the exception like a regular exception where the request is executed
> 
> The reason for the wrapping is:
> 
> > We consider other exceptions like IllegalStateException to be application crashes and do not send them over thread boundaries because we don’t want to burden most callers with catching them.
> 
> https://stackoverflow.com/a/58711127/3971523

same here still happens with version 4.9.7

**Comment by tonymiceli-geoshare** [comment]
This also occurs to me and it happens on user devices. ie. not confined to any device connected to an android studio debugging session as was suggested earlier.
