### ISSUE TITLE
NPE parsing .proto with no package name

### ISSUE THREAD

**Issue by blacktooth** [square/wire#2042]
I am trying to parse a `.proto` with no package name defined. It is resulting into a `NullPointerException`. It seems to be explicitly being thrown from [here](https://github.com/square/wire/blob/aef3945e26cf83705235fd8204584cf5042a972a/wire-library/wire-compiler/src/main/java/com/squareup/wire/schema/SchemaLoader.kt#L283).

Is there any reason why .protos with no explicit `package` defined are not supported?

**Code**

```
  @Test
    public void test_NPE_OnNoPackage() throws Exception {
        String rawSchema = "syntax = \"proto3\";\n"
            + "\n"
            + "\n"
            + "option java_package =\"com.foo.bar\";"
            + "message Address {\n"
            + "  string street = 1;\n"
            + "\n"
            + "  int32 zip = 2;\n"
            + "\n"
            + "  string city = 3;\n"
            + "}\n"
            + "\n"
            + "message Customer {\n"
            + "  string name = 1;\n"
            + "  Address address = 3;\n"
            + "}";
        FileSystem jimfs = Jimfs.newFileSystem(Configuration.unix());
        Path path = jimfs.getPath("/schema.proto");
        Files.write(path, rawSchema.getBytes());

        SchemaLoader schemaLoader = new SchemaLoader(jimfs);
        schemaLoader.initRoots(Lists.newArrayList(Location.get("/")), Lists.newArrayList(Location.get("/")));
        schemaLoader.loadSchema();
    }
```

```

java.lang.NullPointerException
	at com.squareup.wire.schema.SchemaLoaderKt.canonicalImportPath(SchemaLoader.kt:274)
	at com.squareup.wire.schema.SchemaLoaderKt.importPath(SchemaLoader.kt:267)
	at com.squareup.wire.schema.SchemaLoader.load(SchemaLoader.kt:154)
	at com.squareup.wire.schema.SchemaLoader.loadSourcePathFiles$wire_compiler(SchemaLoader.kt:107)
	at com.squareup.wire.schema.SchemaLoader.loadSchema(SchemaLoader.kt:90)

```

**Comment by swankjesse** [comment]
Just a bug. I wonder how we missed this? Can fix.

**Comment by blacktooth** [comment]
Will this fix be merged into 3.7.x release?

**Comment by swankjesse** [comment]
@blacktooth will 4.x work for you? Lots of good stuff there and very little danger in the upgrade.

**Comment by blacktooth** [comment]
I am bit concerned about stability given the [releases](https://github.com/square/wire/releases) are still named alpha. Will a stable 4.x version be released into Maven soon?

**Comment by swankjesse** [comment]
The releases are production quality but the APIs might change. Hoping to finalize Okio this month, and ship a final Wire release next month.

**Comment by blacktooth** [comment]
Thanks! Looking forward for the final release!

**Comment by blacktooth** [comment]
Hi, I want to know if the APIs are finalized and are ready to be released? Are we still on track for the timeline mentioned above?
