### ISSUE TITLE
Wire config as client and service at the same time.

### ISSUE THREAD

**Issue by Coinfo** [square/wire#2047]
Hi, 

I have an Android application that should act as a Server and Client at the same time. 
I have created 2 android modules, one for the Client and another for the Server, they both are using the same protos.

**Server**
```
wire {
    kotlin {
        rpcRole = 'server'
        rpcCallStyle = 'suspending'
    }
}
```

**Client**
```
wire {
    kotlin {
        rpcRole = 'client'
        rpcCallStyle = 'suspending'
    }
}
```

When I am trying to build the project I am getting an error 
   **Type awsomeapp.AuthenticateRequest$Companion$ADAPTER$1 is defined multiple times**

This is because when I am using Server and Client inside the app, it has duplicates, is there a way to configure wire in a way that it's and Server and Client at the same time, something like 

```
wire {
    kotlin {
        rpcRole = 'client, service'
        rpcCallStyle = 'suspending'
    }
}
```
or how I can solve the issue which I have?

**Comment by ChamichApps** [comment]
Hi @swankjesse, 

Thanks for your respons.
Will this approach work

**Comment by ChamichApps** [comment]
Hi @swankjesse, 
I tried your suggestion

```
wire {
    kotlin {
        rpcRole = 'server'
        rpcCallStyle = 'suspending'
        exclusive = false
    }
    kotlin {
        rpcRole = 'client'
        rpcCallStyle = 'suspending'
    }
}
```
but I am still getting the same issue

* What went wrong:
Execution failed for task ':libraries:awsomeapp:generateDebugProtos'.
> Same type is getting generated by different messages:
    Duration at /home/awsomeapp/src/main/proto/awsomeapp/user.proto:21:1
    Duration at /home/awsomeapp/src/main/proto/awsomeapp/user.proto:21:1

**Comment by oldergod** [comment]
You need to use an `include` clause in your first `kotlin` block for this block to generate only the services you wish to generate with the `server` rpc role.
Something like this

```protobuf
wire {
    kotlin {
        rpcRole = 'server'
        rpcCallStyle = 'suspending'
        includes = ['com.example.services.*', 'com.service.OneService']
        exclusive = false
    }
    kotlin {
        rpcRole = 'client'
        rpcCallStyle = 'suspending'
    }
}
```

**Comment by oldergod** [comment]
Your include might need the wildcard?

```diff
- includes = listOf("com.example.sdk")
+ includes = listOf("com.example.sdk.*")
```

The string has to match types, so package are not enough without wildcards.

**Comment by oldergod** [comment]
We'll keep the current API for now.
