### ISSUE TITLE
Question for nested extensions

### ISSUE THREAD

**Issue by hhkkxxx133** [square/wire#2069]
Hello, I am trying to test the library for Protobuf nested extensions with the following schema where extension for message **Customer** is declared in message **VIPCustomer**:
```
message Customer {
  required string name = 1;

  extensions 100 to 199;
}

message VIPCustomer {
  extend Customer {
    optional int32 vipNumber = 100;
  }
}
```
There are two issues I ran into:
1. Is there any reason why [`ExtendElement`](https://github.com/square/wire/blob/master/wire-library/wire-schema/src/commonMain/kotlin/com/squareup/wire/schema/internal/parser/ExtendElement.kt) is not included in the constructor of the [`MessageElement`](https://github.com/square/wire/blob/master/wire-library/wire-schema/src/commonMain/kotlin/com/squareup/wire/schema/internal/parser/MessageElement.kt)? When I tried to construct a `MessageElement` for **VIPCustomer** from `FileDescriptorProto`, the declaration for such extension (extended fields and extendee) is missing.
Specifically, `FileDescriptorProto` contains the following information that is missing in `MessageElement`:
```
message_type {
  name: "VIPCustomer"
  extension {
    name: "vipNumber"
    extendee: ".test.Customer"
    number: 100
    label: LABEL_OPTIONAL
    type: TYPE_INT32
  }
}
```

2. When I use `SchemaLoader` to parse the schema from string to `ProtoFile`, I can see that extended field **vipNumber** is shown under the `extensionsFields` of the extendee `MessageType` **Customer** directly. However, the information for where the extension is declared is missing. Namely, I cannot tell **VIPCustomer** declares such extension. There is no attribute under `MessageType` **VIPCustomer** indicating such information. Is this something that can be added to the `MessageType`?

**Comment by oldergod** [comment]
1. Wire parses proto files to create `*Element` types which are the representation of the file content, nothing more. I'm not sure having the `extend Customer` inside `VIPCustomer` affects it in any way.
2. From the [spec](https://developers.google.com/protocol-buffers/docs/proto#nested_extensions): 
> You can declare extensions in the scope of another type. [...] This is a common source of confusion: Declaring an extend block nested inside a message type does not imply any relationship between the outer type and the extended type. In particular, the above example does not mean that Baz is any sort of subclass of Foo. All it means is that the symbol bar is declared inside the scope of Baz; it's simply a static member.

If I'm not answering your question, would you be able to write a failing test?

**Comment by oldergod** [comment]
See our test to see how we model this case: https://github.com/square/wire/blob/master/wire-library/wire-schema/src/jvmTest/kotlin/com/squareup/wire/schema/internal/parser/ProtoParserTest.kt#L1469-L1498
