### ISSUE TITLE
Question for RpcElement

### ISSUE THREAD

**Issue by LinyuYao1021** [square/wire#2070]
Hi, I'm trying to use your ``wire-schema`` library to convert a ``MethodDescriptorProto`` into ``RpcElement``. But I'm running an issue that I can't pass a null value for the ``Options``, which makes it inconsistent with the original ``MethodDescriptorProto`` because ``Options`` of ``MethodDescriptorProto`` can be either null or an empty list. And this inconsistence does cause the following issue.

My ``.proto`` file is like this:
```protobuf
service Service {
  rpc Foo(Customer) returns(Address) {}
}
```
We parse ``.proto`` file by using:
```java
ProtoFileElement protoFileElement = ProtoParser.Companion.parse(FileDescriptorUtils.DEFAULT_LOCATION, schema);
```
And here's how I convert the `MethodDescriptorProto` into `RpcElement`:
```java
ImmutableList.Builder<RpcElement> rpcs = ImmutableList.builder();
for (MethodDescriptorProto md : sv.getMethodList()) {
    rpcs.add(new RpcElement(DEFAULT_LOCATION, md.getName(), "", md.getInputType(),
            md.getOutputType(), md.getClientStreaming(), md.getServerStreaming(),
            getOptionList(md.getOptions().hasDeprecated(), md.getOptions().getDeprecated())));
}
```
The expected descriptor proto should be:
```protobuf
service {
  name: "Service"
  method {
    name: "Foo"
    input_type: ".io.apicurio.registry.utils.protobuf.schema.syntax2.Customer"
    output_type: ".io.apicurio.registry.utils.protobuf.schema.syntax2.Address"
    options {
    }
  }
}
```
But the actual one I got is:
```protobuf
service {
  name: "Service"
  method {
    name: "Foo"
    input_type: ".io.apicurio.registry.utils.protobuf.schema.syntax2.Customer"
    output_type: ".io.apicurio.registry.utils.protobuf.schema.syntax2.Address"
  }
}
```

**Comment by swankjesse** [comment]
Is this distinction meaningful? We could change the API to care about null vs. empty here, but is there a behavior benefit to doing so?

**Comment by LinyuYao1021** [comment]
Yes, the distinction would affect what kind of ``FileDescriptorProto`` we can get from the ``.proto`` file. It can differentiate these two kinds of files:
```
service Service {
  rpc Foo(Customer) returns(Address) {}
}
```
and
```
service Service {
  rpc Foo(Customer) returns(Address);
}
```

**Comment by swankjesse** [comment]
Yeah, I see that it's different, but does it matter? To me it looks equivalent to a whitespace difference, and we deliberately don't preserve that to save complexity.
