### ISSUE TITLE
Promote CustomHandlerBeta to a proper public API

### ISSUE THREAD

**Issue by swankjesse** [square/wire#2077]
We’re starting to get lots of use from this. Let’s make it a public API and emphasize that Wire’s Schema is the best API for proto schemas.

Use Cases
 - Code generators like JavaGenerator, KotlinGenerator
 - Schema registry clients
   - These may send schemas to servers, perform backwards-compatibility checks, etc.
 - Documentation tools
   - These may build Javadoc-like reports
 - Validators
   - These may enforce additional rules, such as enforcing a naming style guide

Schema Handlers should be able to:
 - Report errors (with Locations!)
 - Emit zero or more files (and we may need to notify Gradle about these?)
 - Self-identify as needing either a fast shallow schema or an exhaustive schema
 - Be tested! Something like our own testing facets should be public API
 - Receive PruningRules, maybe the schema-before-pruning and after
 - Receive its own list of includes+excludes
 - Differentiate source vs. library protos in the build

TODO
- [x] Update doc
  - `CustomHandlerBeta` -> `SchemaHandler.Factory`
  - `CustomHandler` -> `SchemaHandler`
- [x] Add recipes to doc

**Comment by oldergod** [comment]
Will be release in Wire 5
