### ISSUE TITLE
Support of generating plain grpc server code

### ISSUE THREAD

**Issue by michaelfyc** [square/wire#2089]
I'm aware that wire does generates plain grpc server code (See `samples/wire-grpc-sample/server-plain/`). Nevertheless,  I can't find any documentation on this but only in #1903... Some issues mentioned in this comment https://github.com/square/wire/pull/2013#issuecomment-877862096 still exists as I attempted. I wonder whether plain grpc server support is still considered experimental now. Is this on the roadmap?

**Comment by oldergod** [comment]
It is experimental and I don't think there are any plans on iterate on it.
We would gladly accept PRs if you have ideas on how we can improve documentations around this feature.
