### ISSUE TITLE
Backporting a bug fix to 3.7.x

### ISSUE THREAD

**Issue by blacktooth** [square/wire#2104]
Hi,

We use the square wire version 3.7.0 and want to know if the [fix](https://github.com/square/wire/issues/2042) can be backported to 3.7.x as this bug prevents using Protobuf schemas with no packages. Is it possible?  I am open to contribution.

Thanks

**Comment by oldergod** [comment]
Now that Okio 3 is released, Wire 4 will get attention and be released as stable before the end of the year.
Would that work for you?

**Comment by blacktooth** [comment]
We have release a dependent on this fix before that. We are planning to migrate to wire 4 separately once the APIs are finalized and stable version is released. It would be great if this fix can be back ported to 3.7.x as our production code depends on that.

**Comment by oldergod** [comment]
https://github.com/square/wire/releases/tag/3.7.1

**Comment by blacktooth** [comment]
Thank you!
