### ISSUE TITLE
Unable to find google/type/latlng.proto

### ISSUE THREAD

**Issue by chemouna** [square/wire#2110]
have a proto file that uses `import "google/type/latlng.proto";` using it wire returns this error:

> Cause: unable to find google/type/latlng.proto

`import "google/protobuf/wrappers.proto";` gets imported correctly though. 

is `latlng.proto` not included by wire ? 
if so what's the recommended approach to include them when using wire ?

thank you.

**Comment by oldergod** [comment]
`latlng.proto` is part of a `proto-google-common` artifact which Wire doesn't know about.
You could use them by adding the dependency via `protoPath` or `sourcePath` depending on your use case.

![image](https://user-images.githubusercontent.com/1767669/140168453-86cfdbfd-0964-4f99-bef8-c4f6ab8efc51.png)

**Comment by chemouna** [comment]
thanks a lot for the help @oldergod,
i tried first this approach:

```kotlin
sourcePath {
	 protoPath("src/main/proto", "com.google.api.grpc:proto-google-common-protos:2.0.1")
}
```
but that fails because in the generate model `com.google.type.LatLng` is not found.

so tried adding the dependency to the module where wire models are generated 
```kotlin
implementation("com.google.api.grpc:proto-google-common-protos:2.0.1")
```

this fails with `Unresolved reference: ADAPTER` for `LatLng.ADAPTER`references in the generated model, i assume this is because LatLng model used was not generated by wire ?

tried using sourcePath as well thinking with source path it will get generated: 
```kotlin
protoPath("com.google.api.grpc:proto-google-common-protos:2.0.1")
sourcePath("src/main/proto", "com.google.api.grpc:proto-google-common-protos:2.0.1")
```
but with that i'm getting `Cause: unable to find google/protobuf/api.proto`

any input into what's the appropriate configuration to use to get it compiling and get the generated models importing and referencing `LatLng` ? 

for context a simplification for my proto file:

```kotlin
syntax = "proto3";

package "apis.v1";

import "google/type/latlng.proto";

message Point {
   google.type.LatLng location = 1;
}
```

**Comment by oldergod** [comment]
See if you can find what you need from the documentation: https://square.github.io/wire/wire_compiler/#inputs-and-outputs

You probably want two `sourcePath` block, one with your local protos, and one pointing to `google-common-protos`.

**Comment by chemouna** [comment]
tried different possible combinations from the doc and all of them failed with 

> Cause: unable to find google/protobuf/api.proto
>   searching 0 proto paths:

for example this config with two sourcePath blocks fails with that error:
```
wire {
    sourcePath {
        srcDir("src/main/proto")
    }

    sourcePath {
        srcJar("com.google.api.grpc:proto-google-common-protos:2.6.0")
    }
}
```
small project with the config [here](https://github.com/chemouna/protoexample)

**Comment by oldergod** [comment]
The error message is explicit, Wire cannot find `google/protobuf/api.proto`. In which artifact does it live? Once you know, you can add it as another sourcePath.

**Comment by chemouna** [comment]
was able to use a solution that bundles google's common proto files in the main jar we're using for the app proto files , thank you for the help.
