### ISSUE TITLE
searching 0 proto paths:for file D:\AndroidProject\Protobuff\app\src\main\proto/opentelemetry\proto\trace\v1\student.proto

### ISSUE THREAD

**Issue by movemoveLife** [square/wire#2112]
In a simple Andriod project, use protobuf and wire.

Mac os: 
use protobuf and wire, Build Success!

Windows10: 
use protobuf and wire, Build Failed! When only use protobuf, build Success!

error:searching 0 proto paths:for file D:\AndroidProject\Protobuff\app\src\main\proto/opentelemetry\proto\trace\v1\student.proto

You can see "\main\proto/opentelemetry\" the "/" in the path, I think In Windows10, wire not correct handle path.

**Comment by oldergod** [comment]
Tracked in #1325 

We'll try to fix that soon.
