### ISSUE TITLE
wire-grpc-client version 3.7.1 not published?

### ISSUE THREAD

**Issue by charleskorn** [square/wire#2116]
I've just tried to upgrade my app from Wire 3.7.0 to 3.7.1, and the build is failing because it can't find version 3.7.1 of `wire-grpc-client` ([sample build](https://github.com/batect/batect/runs/4116058266?check_suite_focus=true#step:7:40)). 

Looking on [Maven Central](https://repo1.maven.org/maven2/com/squareup/wire/wire-grpc-client/),  the most recent version from the 3.x series is 3.7.0.

Is this expected?

**Comment by oldergod** [comment]
Thanks for reporting. I don't know what happened but I just released it.

**Comment by charleskorn** [comment]
Awesome, thanks for fixing this so quickly (and on a Sunday as well).
