### ISSUE TITLE
Link to Precompiled JAR Broken

### ISSUE THREAD

**Issue by commonsguy** [square/wire#2134]
In [this section of the project README](https://github.com/square/wire#generating-code-with-wire), there is "Download the latest precompiled jar." That links to https://search.maven.org/remote_content?g=com.squareup.wire&a=wire-compiler&c=jar-with-dependencies&v=LATEST, which is returning a 404.

**Comment by commonsguy** [comment]
The reason I tried using the link was for providing a repro case for #2135. That's the first time I've used that JAR; our normal way to invoke `WireCompiler` is via a custom Gradle task using the `wire-compiler` dependency. 

AFAIK, the Gradle plugin does not work with Android modules, only with pure Java and Kotlin ones. If I am mistaken on that point, or 4.0.0 addresses that limitation, my apologies!

But, if that limitation is still in place, I would recommend documenting both a Gradle-plugin and a non-Gradle-plugin way of using the Wire compiler, by whatever means that you want to support. That doesn't mean that you need the precompiled JAR, though.

**Comment by oldergod** [comment]
Wire should work with Android modules starting from `4.0.0-alpha.1`. If you see any problems, we'd be happy to hear about them.

**Comment by commonsguy** [comment]
> If you see any problems, we'd be happy to hear about them.

In a light spike test, alpha20 works fine with the Gradle plugin in an Android module. And, `permitPackageCycles true` seems to work there as well!

**Comment by oldergod** [comment]
The precompiled JAR link is also fixed. Thanks for reporting.
