### ISSUE TITLE
WireCompiler: Unknown argument --permit_package_cycles 

### ISSUE THREAD

**Issue by commonsguy** [square/wire#2135]
Running `java -jar wire-compiler-3.7.1-jar-with-dependencies.jar --permit_package_cycles`, using the JAR from [Maven](https://repo1.maven.org/maven2/com/squareup/wire/wire-compiler/3.7.1/), results in:

```
Exception in thread "main" java.lang.IllegalArgumentException: Unknown argument '--permit_package_cycles'.
	at com.squareup.wire.WireCompiler$Companion.forArgs(WireCompiler.kt:334)
	at com.squareup.wire.WireCompiler$Companion.forArgs$default(WireCompiler.kt:248)
	at com.squareup.wire.WireCompiler$Companion.main(WireCompiler.kt:234)
	at com.squareup.wire.WireCompiler.main(WireCompiler.kt)
```

That flag was added back in #1760. 

Looking at [the 3.7.1 source for `WireCompiler.kt`](https://github.com/square/wire/blob/3.7.1/wire-library/wire-compiler/src/main/java/com/squareup/wire/WireCompiler.kt), it looks like `PERMIT_PACKAGE_CYCLES_OPTIONS` is defined but is not used. Instead, `permitPackageCycles` seems to be controlled via [by the `--emit_applied_options` CLI option](https://github.com/square/wire/blob/3.7.1/wire-library/wire-compiler/src/main/java/com/squareup/wire/WireCompiler.kt#L332):

```kotlin
arg == EMIT_APPLIED_OPTIONS -> permitPackageCycles = true
```

However, AFAICT, that too does not work, insofar as the compiler still fails if packages form a cycle if you use `--emit_applied_options`.

It's entirely possible that this is user error, or that this option is only supported through the Gradle plugin, or something like that. Or, since this option appears to be undocumented, perhaps it is not meant for Wire users.

**Comment by oldergod** [comment]
Thank you. It's fixed on master now via https://github.com/square/wire/pull/2114#discussion_r743729592
I'll be released within Wire 4.0
