### ISSUE TITLE
Naming conflicts

### ISSUE THREAD

**Issue by phungleson** [square/wire#216]
I have a few messages with the same name and the way wire generate the message look like this

```java
package private;

import public.ChatMessage;

public final class ChatMessage extends Message {
  public final ChatMessage message;
}
```

This cause compilation error since `ChatMessage` appears twice.

Please understand this is a dummy example and I want to keep the class name the same.

Do we have any solution to make it work, like using qualified name all the time instead of `import`?

Or anywhere of wire codebase I should look into?

**Comment by JakeWharton** [comment]
Somewhat related to #184.

Is it actually the package names which use reserved words in the real protos? That presents an interesting problem because we'd have to do something like append an underscore or something.

**Comment by phungleson** [comment]
It is because of the same classe names.


```java
package private;

public final class ChatMessage extends Message {
  public final public.ChatMessage message;
}
```

**Comment by JakeWharton** [comment]
If it's just duplicated class names then this can be considered a duplicate of #184.

**Comment by phungleson** [comment]
Okay
