### ISSUE TITLE
WireCompiler podspec should not cause Gradle to run

### ISSUE THREAD

**Issue by sethfri** [square/wire#2173]
From @swankjesse :
Gradle leaves behind a daemon, and this pollutes the host machine.
If there’s a Gradle daemon already running, the two tend to fight and cause the build to fail
This is too slow

Maybe we could instead ship wire-compiler.jar in the Podspec?
Or even better, build a GraalVM native image so there’s no JVM at all polluting our Macs.

**Comment by JakeWharton** [comment]
You could also just disable the daemon

**Comment by sethfri** [comment]
Hey @JakeWharton, I don't follow, do you mind elaborating? My current plan to tackle this is to just point the podspec to the jar in Maven Central

**Comment by JakeWharton** [comment]
You can pass `--no-daemon` to not have a daemon stay alive.

The current change means we can no longer deploy internal releases nor test local branches. Seems like a step backward. You already need the JVM to run the compiler after all so you're not saving much.

**Comment by sethfri** [comment]
I think the primary issue for me is speed. Building the compiler isn't something that should be done during pod install time, because that's a command engineers need to run multiple times per day. That work is often cached, but when it's not (I do a clean installation multiple times per week if not multiple times per day) it's really painful.

I don't think this prevents testing with other jars unless there's something I'm missing.
