### ISSUE TITLE
`WireTask` cache is different when using maven coord

### ISSUE THREAD

**Issue by chrisjenx** [square/wire#2179]
When the path of the project changes and using a Maven Coordinate for the proto sources we get WireTask cache misses:
![image](https://user-images.githubusercontent.com/1167793/146503614-c1bf23cd-b031-48e9-a580-9664c387dfd1.png)
```
    sourcePath {
        srcJar("com.maven.coord:protos:20211216221427")
        include("instacart/fulfillment/public_apis/**", "google/type/**")
    }
```

Changing to a jar bundled into the project seems to workaround for now
```
    sourcePath {
        srcJar("lib/protos-20211216221427.jar")
        include("instacart/fulfillment/public_apis/**", "google/type/**")
    }
```

**Comment by chrisjenx** [comment]
FYI the resulting cache key should be the same given all the inputs are the same - we'll see if we can attach all inputs/outputs to the build scans so we can do a comparison

**Comment by chrisjenx** [comment]
FYI, I downgraded from `android-library` to just pure `kotlin("jvm")` that now produces the same output from `generateMainProtos` so `compileKotlin` is the same.

I'm trying to find the code, but when the maven coord gets downloaded, is the downloaded file in a absolute path?

**Comment by oldergod** [comment]
Obsolete. Please reopen if this keeps happening.

**Comment by chrisjenx** [comment]
Pretty sure it's still an issue just not had chance to test it recently. If I get a chance I'll let you know

**Comment by oldergod** [comment]
This might be related to `WireInput` resolving all files before passing them to the `WireTask`
`InputLocation.base` would end up within `$HOME/.gradle/cache/....` and this would break the build cache
