### ISSUE TITLE
Generated annotations for repeated fields doesn't compile.

### ISSUE THREAD

**Issue by dhenry-stripe** [square/wire#2195]
Hi folks, the following compile time error occurs after updating from `4.0.0-alpha.11` to `4.0.0`:

extension.proto:
```
syntax = "proto2";
package ext;

enum PII {
  LOCATION,
  // additional values
}

extend google.protobuf.FieldOptions {
  repeated PII pii = 1;
}
```
message.proto:
```
message Address {
  string line1 = 1 [json_name = "line1", (.ext.pii) = LOCATION];
  // additional fields 
}
```

Wire `4.0.0-alpha11`:
```
public class Address(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY
  )
  // additional fields
)
```

Wire `4.0.0`:
```
public class Address(
  @PiiOption(listOf(
    PII.LOCATION
  ))
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY
  )
 // additional fields
)
```
The code generated by Wire `4.0.0` fails to compile with the following errors:
`An annotation argument must be a compile-time constant`
`Type mismatch: inferred type is List<PII> but PII was expected`

So the generated `PiiOption` annotation is unaware that its value is repeated. The generated `Address` class is aware of the repeated value, but the generated code is invalid.

What is the expected behavior here? Is this a regression?

**Comment by oldergod** [comment]
Probably a bug. In the meantime, If you don't use the annotation and are happy with it not being generated, you can set `emitDeclaredOptions` and `emitAppliedOptions` to false in your `wire` config block.

**Comment by dhenry-stripe** [comment]
Ah ok, we don't need the annotation. Setting those flags works as expected, Thanks!
