### ISSUE TITLE
Gradle DSL does not work with version catalogs

### ISSUE THREAD

**Issue by JakeWharton** [square/wire#2207]
You cannot do `srcJar(libs.whatever)`, for example. This returns a `Provider` of type [`MinimalExternalModuleDependency`](https://docs.gradle.org/current/javadoc/org/gradle/api/artifacts/MinimalExternalModuleDependency.html).

Would be nice to help completely eliminate dealing with string coordinates.

**Comment by oldergod** [comment]
Dup of #1946
