### ISSUE TITLE
Are there any plans to support max keyword with reserved?

### ISSUE THREAD

**Issue by ttymsd** [square/wire#2210]
We write like .proto 
```
enum TestEnum {
  REASON_CODE_UNKNOWN = 0;
  REASON_CODE_ANY = 1;
  reserved 2 to max;
}
```

run compile when get error message `expected an integer but was max`
Do you have any plans to support this kind of writing?

**Comment by oldergod** [comment]
We'll fix, thanks for reporting.

**Comment by oldergod** [comment]
Wire will not crash when parsing max for enums but reserved are still not honoured. This will be followed in #797
