### ISSUE TITLE
"error: package com.squareup.wire does not exist" for code generated with wire 4.2.0

### ISSUE THREAD

**Issue by ionel-sirbu-crunch** [square/wire#2215]
Hello,

I've got a Java project, Spring Boot based, that that uses `wire` 3.7.1 at the moment & I'm trying to upgrade to `4.2.0`, but I seem to have some issues.
We use maven & we've written a maven plugin for generating the java code from proto files during the `generate-sources` phase, using `wire-compiler` & `wire-java-generator`. I've already upgraded `wire` on the plugin side & that seems to work fine, the sources are generated just fine.
However, when it gets to compiling the generated code, maven fails with plenty of `package com.squareup.wire does not exist` & `cannot find symbol` errors. Basically none of these are resolved:
```java
import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.ReverseProtoWriter;
import com.squareup.wire.Syntax;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import okio.ByteString;
```

The right version of `wire-runtime` seems to be picked up by maven though:
```
[DEBUG]  C:\path\to\maven\repository\com\squareup\wire\wire-runtime\4.2.0\wire-runtime-4.2.0.jar
```

Versions used:

- Spring Boot: 2.6.3
- proto syntax: proto2

What am I missing? Is there anything else needed at compile time besides the `wire-runtime` dependency?

Thanks!

**Comment by JakeWharton** [comment]
Try 'wire-runtine-jvm' as the `artifactId` of the runtime dependency.

**Comment by ionel-sirbu-crunch** [comment]
> Try 'wire-runtine-jvm' as the `artifactId` of the runtime dependency.

Oh, ok, I see the whole `expect`/`actual` kotlin paradigm being used there. Indeed, everything works fine after using `wire-runtine-jvm` 👍
It might be worth for the maintainers of the library to update the README, to give devs a bit of a heads-up about that.

Many thanks!

**Comment by ionel-sirbu-crunch** [comment]
Thank you guys!
