### ISSUE TITLE
Present BoolValue field gets deserialized as null in Kotlin

### ISSUE THREAD

**Issue by zsoltvilagos** [square/wire#2222]
We're creating Proto payload with multiple kinds of libraries, including Google Java/Kotlin Protobuf, TypeScript and last but not least Wire Kotlin.

We have a case when we create Proto payload with Google Kotlin & read it with Wire based like the following:

Proto:
```
message MyMessage {
    google.protobuf.BoolValue my_bool_value = 1;
}
```

Create payload with Google:
```
val message =
    myMessage {
        my_bool_value = boolValue { value = false }
    }
val bytes = message.toByteArray()
val hex = bytes.joinToString { it.toString(radix = 16).padStart(2, '0') } // for debugging
```

Then parse with Wire:
```
val messageWireDecode = MyMessage.ADAPTER.decode(bytes)

println(messageWireDecode)
```

What we get is that `my_bool_value` is not printed, it's not present in the payload.

I checked the sheer bytes with the original (private) code, building an understanding of Proto format & serialization.

If we create the payload with Google Kotlin, then it writes the `my_bool_value` tag + field type, then 0 as field length because it doesn't serialize `false`. In our case: hex `32 00` (32 because our field tag is dec 6).
Wire then won't set `MyMessage.my_bool_value` on decode, but leave it null, we think because of [this](https://github.com/square/wire/blob/master/wire-library/wire-runtime/src/commonMain/kotlin/com/squareup/wire/ProtoAdapter.kt#L1314).

If we create the payload with Wire, then it writes the `my_bool_value` tag + field type, then length 2 because it also writes the encapsulated bool's tag (`08`) and the value `false` (`00`). In our case hex `32 02 08 00`.

Disclaimer: I mean this as a first contact because I expect that there might be a specific reason in the background. I can of course tend to having a sample project with a small proto like above and runnable code to reproduce. Or even look into having a failing test on a personal fork, like pointed out by the contribution guidelines.

**Comment by oldergod** [comment]
I confirmed in a test. I'll address. Thanks for reporting.

**Comment by zsoltvilagos** [comment]
> I confirmed in a test. I'll address. Thanks for reporting.

Great news! Thank you!
