### ISSUE TITLE
I impoted wire. I can't build my Android project.

### ISSUE THREAD

**Issue by k-horiuchi** [square/wire#2237]
I read this.
https://github.com/square/wire/blob/master/wire-library/docs/wire_compiler.md

Is this document a liar?
I can't build my Android project.

![image](https://user-images.githubusercontent.com/47852441/160560199-279e118c-255d-4dae-b36e-2d30336ff3a9.png)
![image](https://user-images.githubusercontent.com/47852441/160560295-80fee542-1a6c-4a76-8713-61e17290946c.png)

**Comment by oldergod** [comment]
Would you be able to make a sample project so that we can reproduce the problem?

**Comment by k-horiuchi-work** [comment]
OK. Please, wait.

**Comment by k-horiuchi** [comment]
@oldergod 
I created sample project.
https://github.com/k-horiuchi/jetpack-compose-wire-example

**Comment by oldergod** [comment]
There's something wrong with the project. If you remove all the Wire stuff, I don't think it'll be able to build the project. Have you confirmed all is good before you even added Wire?

**Comment by k-horiuchi** [comment]
@oldergod
You said something scary.
You had better cancel the statement.

This is a project that comes standard with Android Studio.
I just started Android Studio, selected "New Project" and selected "Empty Compose Activity".
And I put in the wire.

The operation has been confirmed. And there can be no problem.

**Comment by k-horiuchi** [comment]
@oldergod
I reproduced this in 3 minutes.
https://user-images.githubusercontent.com/47852441/160919661-6f120a8b-dfed-4282-b35c-60d98047cdb9.mp4

**Comment by oldergod** [comment]
Two things:
- Before you add Wire, you already added other plugins which break your builds.
- You apply Wire on `app` but you're also trying to apply Wire at the root `build.gradle` file where as the error you're getting say, there are no Java, Kotlin, or Android plugin applied.

**Comment by k-horiuchi** [comment]
@oldergod
Either way, this document is invalid.

**Comment by oldergod** [comment]
If you think things could be improved, you're welcome to push a PR. Gradle and Android official documentations have good resources which explains how Gradle projects work.
