### ISSUE TITLE
Missing extensions support for OneofOptions in proto3

### ISSUE THREAD

**Issue by hhkkxxx133** [square/wire#2241]
Hello,

As fixed in the #1396, extensions are now supported in proto3 only for custom options use case. However `OneofOptions` is missing from the [list](https://github.com/square/wire/blob/master/wire-library/wire-schema/src/commonMain/kotlin/com/squareup/wire/schema/Options.kt#L397).

Sample schema:
```
import "google/protobuf/descriptor.proto";

extend google.protobuf.OneofOptions {
  optional int64 my_oneof_option = 50003;
}

message MyMessage {
  oneof qux {
   option (my_oneof_option) = 42;

    string quux = 3;
  }
}
```

**Comment by oldergod** [comment]
Can fix!
