### ISSUE TITLE
Nullable Annotations?

### ISSUE THREAD

**Issue by EddieRingle** [square/wire#225]
Would it be Wire's responsibility to add Nullable annotations to optional fields (or I guess in proto3's case, all fields), or does it not even make sense to do that? As it stands using Wire-generated types in Kotlin, all fields are considered safe when it reality they are often null (since they're optional).

**Comment by JakeWharton** [comment]
The fundamental problem here is that JSR 305 never got traction and now there's no less than 10 nullable annotations and various degrees of support for each of those spread across tooling.

I think the only reasonable approach is extensible code generation that allows you to do this yourself.

**Comment by EddieRingle** [comment]
Yeah, I suppose that makes sense. I didn't realize JSR 305 was in such a sorry state. How disappointing.

I hate to ask, but is there an ETA on Wire v2, then?

**Comment by swankjesse** [comment]
I'm tempted to commit to JSR 330’s `@Nullable` anyway. Does including it do harm?

**Comment by JakeWharton** [comment]
> Does including it do harm?

Nothing _really_ beyond the transitive dependency that would have to be on 'wire-runtime'.

> ETA on Wire v2

No, but work has just (re)started so we'll be pushing it forward whereas before it was just blowing smoke.

**Comment by vanvlack** [comment]
You could look into allowing an option to turn on JSR303 annotations, which would require the user to include bean validation stuff. The annotations themselves do nothing but act as markers, requiring a bean validation impl to be called on the beans.

https://jcp.org/en/jsr/detail?id=303

Just a thought (and small dependency if used): http://search.maven.org/#artifactdetails%7Cjavax.validation%7Cvalidation-api%7C1.1.0.Final%7Cjar

**Comment by JakeWharton** [comment]
That jar has a lot more than annotations in it. It seems to be a mechanisms for validators not publishers. We use the Findbugs JSR305 artifact in our app at present (in addition to Android's support-annotations package): http://search.maven.org/#artifactdetails%7Ccom.google.code.findbugs%7Cjsr305%7C3.0.0%7Cjar

**Comment by vanvlack** [comment]
@JakeWharton 

> It seems to be a mechanisms for validators not publishers

That's correct. As beans generated from proto's are likely shared at times between publishers and validators, the option, not the requirement, to have these might be nice.

Again, likely not an issue if extensibility of Message writing comes in, where anyone can add at any time. The nice thing about JSR-303, is more annotations are available, and it's not dead like JSR-305. JSR-330 seems like an interesting choice, as it's more around dependency injection vs validation.

**Comment by JakeWharton** [comment]
Oh, sorry. I missed the 303 vs 305 distinction in your original message.

**Comment by JakeWharton** [comment]
For the next release and when using `--android` nullability annotations are included. Not a general solution for Java users though.

**Comment by EddieRingle** [comment]
:+1: 

@JakeWharton Too bad we can't just ignore Java and unilaterally adopt Kotlin with it's null-safety features. :(

**Comment by EddieRingle** [comment]
Fixed by PR #649 / 8d4171c87. Thanks @swankjesse! (I mean, I'm not currently using Wire, but it's good this finally got done.)
