### ISSUE TITLE
grpcServerCompatible fails on services with two methods

### ISSUE THREAD

**Issue by yschimke** [square/wire#2260]
This simple proto change results in an error

```
service Whiteboard {
  rpc Whiteboard (stream WhiteboardCommand) returns (stream WhiteboardUpdate) {
  }
  rpc Whiteboard2 (stream WhiteboardCommand) returns (stream WhiteboardUpdate) {
  }
}
```

```
Same file /wire/samples/wire-grpc-sample/server-plain/build/generated/source/wire/com/squareup/wire/whiteboard/WhiteboardWireGrpc.kt is getting generated by different services:
  Whiteboard at wire/samples/wire-grpc-sample/server-plain/../protos/src/main/proto/com/squareup/wire/whiteboard/whiteboard.proto:58:1
  Whiteboard at wire/samples/wire-grpc-sample/server-plain/../protos/src/main/proto/com/squareup/wire/whiteboard/whiteboard.proto:58:1
```

**Comment by oldergod** [comment]
Can you share the generating configuration? If that's the protoc-API-ed generation, it's not really under any maintenance.

**Comment by yschimke** [comment]
It's just the one from `samples/wire-grpc-sample` with that API change. I thought it was more around GRPC support, than protoc.  I thought it still used wire types.

https://github.com/yschimke/wire/commit/ff04f56bf8b4a1cea144f4b6685162392728a3a8

**Comment by oldergod** [comment]
This one pass: `gradle samples:wire-grpc-sample:server:generateProtos`
This one fails: `gradle samples:wire-grpc-sample:server-plain:generateProtos`

The `server-plain` uses the `grpcServerCompatible` option.
```kotlin
  /** True to also generate gRPC server-compatible classes. Experimental feature. */
  val grpcServerCompatible: Boolean = false,
```
This feature is more or less without owner right now.
If you don't need this feature, you can exclude the `server-plain` module and continue playing with the sample.

**Comment by yschimke** [comment]
Makes sense, I was hoping to use it, to grab the gRPC MethodDescriptors.  But figured it was finally simpler to just copy an paste the Wire definitions from the internals of the generated code.
