### ISSUE TITLE
Cannot resolve symbol 'AnyMessage' with wire 4.3.0

### ISSUE THREAD

**Issue by onexuan** [square/wire#2275]
I use wire in android
api "com.squareup.wire:wire-runtime:4.3.0"
but
Cannot resolve symbol 'AnyMessage' with wire 4.3.0

**Comment by oldergod** [comment]
I am not able to repro. Would you be able to write a sample project which repros the problem?

**Comment by onexuan** [comment]
It means that wire class cannot be found in android
