### ISSUE TITLE
Missing Documentation or Issue?

### ISSUE THREAD

**Issue by cyph3rcod3r** [square/wire#2301]
Using wire version: 4.4.0

build.gradle :

`wire {
   kotlin {
       rpcCallStyle = 'suspending'
       rpcRole = 'client'
   }
}`

Output Class:
`public interface WelcomeServiceClient : Service {
  public fun welcome(): GrpcCall<WelcomeRequest, WelcomeResponse>
}`

Not adding suspend keyword in the function.

**Comment by oldergod** [comment]
For client roles, the generated class doesn't need to hold suspending methods. The returned type `GrpcCall` or `GrpcStreamingCall` will expose suspending methods though.

**Comment by oldergod** [comment]
The gRPC sample has been updated last month with the latest APIs. https://github.com/square/wire/blob/master/samples/wire-grpc-sample/client/src/main/java/com/squareup/wire/whiteboard/MainActivity.kt#L50

**Comment by cyph3rcod3r** [comment]
Ok, still the example looks different from what the code is generated for me. For my 1 grpc servoce it creates 

>  grpc client interface which i posted in the code above.
> grpc client class which has implementation and it takes in `GrpcClient` as param and instead of calling client.create we can directly use this class. Its not mentioned in the doc

**Comment by cyph3rcod3r** [comment]
![Screenshot 2022-07-08 at 4 23 10 PM](https://user-images.githubusercontent.com/13975996/178955316-ed69584b-88d6-449c-a557-8cf1755525ce.png)

Its giving this warning

**Comment by cyph3rcod3r** [comment]
![Screenshot 2022-07-14 at 3 19 33 PM](https://user-images.githubusercontent.com/13975996/178955417-412f1038-52dc-43e6-a0e2-56c293656435.png)
Its giving this warning

**Comment by oldergod** [comment]
The warning is coming from Android, not Wire. You could refer to [Android's documentation around coroutines](https://developer.android.com/kotlin/coroutines?gclid=CjwKCAjwoMSWBhAdEiwAVJ2ndsGelPwYOq9j-FuzwXLhqzrkN-YbtBTHDRV8wPOjn1pre8Y2Mr_hiBoC0moQAvD_BwE).
