### ISSUE TITLE
Generate code to support JSON serializing/deserializing as well?

### ISSUE THREAD

**Issue by wakandan** [square/wire#231]
In my company, we want to use wire-generated java code to support json deserialization by adding extra jackson annotations (like `@JsonCreator`, `@JsonProperty` and so on) so we made some changes in the wire's code. I want to check if this is something that wire wants to support because it's such a common use case that protobuf is introduced later into an json-driven legacy system. If yes I can clean up the code a bit to perhaps add an extra flag like `--support-json` for that functionality and make a pull request. Thanks.

**Comment by JakeWharton** [comment]
Supporting JSON and supporting Jackson are two very different things. We never use Jackson for JSON so its inclusion would be an odd specialization. A better approach would be providing extensibility points for the code generation to allow you to customize what's happening for whatever arbitrary customizations you want to make.

**Comment by vanvlack** [comment]
+1 to extensibility over including directly. Ideally, I could create a MessageWriter of my own, that generates pojo's how I would like, including the proto bits (or not for that matter).

**Comment by wakandan** [comment]
hmm that means if I want to generate both json & protobuf, I need to practically copy the code from current message writer into a new one, and add the json support code in? I think I might not understand this correctly. 

Btw, the reason I mentioned jackson is that we're using dropwizard.

**Comment by JakeWharton** [comment]
Seems like you'd only need to generate `InstanceCreator` types? No? Jackson should be able to read the fields for serialization and for deserialization we offer a public constructor that takes the values of every field.

**Comment by wakandan** [comment]
I'm not aware of `InstanceCreator` yet

Jackson wasn't able to deserialize automatically. It was because there's no explicit mapping for fields, so jackson doesn't know which field to map to which json attribute. We're using `JsonCreator` annotation with added `JsonProperty` annotation for fields in the constructor like this
```
@com.fasterxml.jackson.annotation.JsonCreator
  public Search(@com.fasterxml.jackson.annotation.JsonProperty("trips") List<Trip> trips, @com.fasterxml.jackson.annotation.JsonProperty("cabin") Cabin cabin, @com.fasterxml.jackson.annotation.JsonProperty("adults_count") Integer adults_count, @com.fasterxml.jackson.annotation.JsonProperty("children_count") Integer children_count, @com.fasterxml.jackson.annotation.JsonProperty("infants_count") Integer infants_count) {
..
}
```

**Comment by JakeWharton** [comment]
Er, sorry. `InstanceCreator` is Gson. Looks like Jackson (sadly) has no analogous. The closest thing appears to be these very strange [mix-in annotation classes][1].

In any case, we aren't going to do something like support Jackson out-of-the-box. However, extensibility is on our mind as the ability to modify the generated code can solve a lot of problems including some of our own internal ones.

 [1]: http://wiki.fasterxml.com/JacksonMixInAnnotations

**Comment by wakandan** [comment]
We looked into Gson as well, but since it's almost magical, it tends to be slower compared to jackson. Mixin annotation class is also an option, but in wire-generated code's case  it's almost a redundancy (because the code is already quite simple). I would be interested to hear what direction of solving this you have in mind

**Comment by JakeWharton** [comment]
Exposing the model for the to-be-generated class and letting you add to it.

**Comment by wakandan** [comment]
clarification please :+1:

**Comment by wakandan** [comment]
ping @JakeWharton 

could you give some direction please :dancer:  thanks.

**Comment by rage-shadowman** [comment]
How about using a [handlebars](http://handlebarsjs.com/)/[velocity](http://velocity.apache.org/index.html) template?

If you look at [Avro](https://github.com/apache/avro/tree/master/lang/java/compiler/src/main/velocity/org/apache/avro/compiler/specific/templates/java/classic), that's how it generates its java classes. This way square/wire could provide the template for the files as they are written now, and developers could modify the template to include Jackson annotations or replace the public final properties and Builders with private mutable properties using getters/setters (personally, I think that is a horrible thing to do, but some people -- read: lousy programmers ;P -- may prefer it that way) or anything else that we might want to add to the generated classes.

**Comment by JakeWharton** [comment]
I don't think we want to sacrifice our code generation mechanism (which is superior to those template engines) for this edge case. An easy way to support this now is by generating a `JsonAdapter` (or whatever your library requires) based on a `Schema` and then registering it with your serializer.

**Comment by rage-shadowman** [comment]
What would we be sacrificing? Looking at the code that is generated, I don't really see what would change in the final generated class. There may be a speed hit, but only on running the plugin (compile time), not when using the generated classes (runtime).

**Comment by JakeWharton** [comment]
Automatic imports and properly scoped references. Add a proto named String or Object or reference two with the same simple name and every template approach breaks and devolves into using qualified names everywhere. AutoValue has to work around some naming collisions bug every few months because they use templates. JavaPoet-based solutions don't.

**Comment by rage-shadowman** [comment]
While I agree that qualifying all class names is not something you want to do in manually generated classes, I would also argue that qualified names are not an issue in auto-generated code that isn't intended to be modified. In fact, it may be seen as a benefit, because now you know right away where that class comes from and why you're IDE is telling you that "List" is not a "List".

**Comment by JakeWharton** [comment]
It is intended to be looked at, though, and we value code that looks like
it was written by a person.

**Comment by oldergod** [comment]
Fixed.
