### ISSUE TITLE
Export proto file from generated code

### ISSUE THREAD

**Issue by jonluca** [square/wire#2350]
Is it possible to get the original proto file that generated the class or instance?

**Comment by oldergod** [comment]
There are no API to do that at the moment but it should be easy to build a tool that does this. Although we might be loosing some information around conflicting names in classes or fields.

**Comment by jonluca** [comment]
Was this completed? Or just closing stale issues?

**Comment by oldergod** [comment]
Sorry, I closed it because we don't plan on building this.
