### ISSUE TITLE
wire-gradle-plugin not supprt kotlin > 1.6.20 

### ISSUE THREAD

**Issue by tdv-rf** [square/wire#2358]
Just default configuration. 

![image](https://user-images.githubusercontent.com/29626213/206895103-af58c1c5-82b3-4f06-acc8-5a63c73e2ec4.png)

If i use kotlin 1.6.20 all compiled ok. But any upper verison for example 1.7.20 not compiled with exception. 
![image](https://user-images.githubusercontent.com/29626213/206895072-fc0f90ac-4160-4c51-a1bf-a34605775fe0.png)

 Couldn't find debug in {androidTest=null, androidTestDebug=null, androidTestRelease=null, debug=null, main=null, release=null, test=null, testDebug=null, testRelease=null}

**Comment by oldergod** [comment]
Obsolete.
