### ISSUE TITLE
Unresolved reference builded classes Android Studio/IDEA

### ISSUE THREAD

**Issue by feelgood4** [square/wire#2381]
After build proto classes in submodule, android studio dont indexing them (Build is success,  not indexing only in code editor)

Implimentation problem in repository:
https://github.com/feelgood4/WireKotlinIndexProbem

I don't know what is it connected with. The same code with android library is indexing

Wire in Gradle:
```
apply plugin: 'kotlin'
apply plugin: 'java-library'
apply plugin: 'com.squareup.wire'

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

wire {
    sourceSets {
        main {
            resources {
                srcDir("src/main/proto")
            }
        }
    }
    kotlin {}
}

dependencies {
    implementation "com.squareup.wire:wire-runtime:4.4.3"
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
}
```

**Comment by feelgood4** [comment]
UPD: (Added repository with two stub libs for generating proto classes:)[https://github.com/feelgood4/WireKotlinIndexProbem]
- proto (where proto file places)
- stub-kotlin (java lib created proto classes from jar proto lib)
- stub-android-kotlin (android lib created proto classes from jar proto lib)

android stub lib is successful indexed in app, but stub-kotlin not

**Comment by feelgood4** [comment]
UPD: (Added repository with two stub libs for generating proto classes:)[https://github.com/feelgood4/WireKotlinIndexProbem]
- proto (where proto file places)
- stub-kotlin (java lib created proto classes from jar proto lib)
- stub-android-kotlin (android lib created proto classes from jar proto lib)

android stub lib is successful indexed in app, but stub-kotlin not

**Comment by oldergod** [comment]
Maybe because the plugin is set to `4.4.1` and we fixed a problem in between?

Here's a patch I made to get it working
[wire.patch](https://github.com/square/wire/files/10534132/wire.patch)

**Comment by feelgood4** [comment]
> ```diff
> squareup
> ```

oh lol, thanks and sorry for repositories in project. by the way not syncing srcjar without prebuilding proto jar is bug?

**Comment by oldergod** [comment]
> by the way not syncing srcjar without prebuilding proto jar is bug?

I don't understand the question.

**Comment by feelgood4** [comment]
> > by the way not syncing srcjar without prebuilding proto jar is bug?
> 
> I don't understand the question.

```
wire {
    sourcePath {
        srcJar = "$rootDir/proto/build/libs/proto.jar"
    }

    kotlin {}
}
```
```
Invalid path string: "/Users/feelgood4/AndroidStudioProjects/WireKotlinIndexProbem/proto/build/libs/proto.jar".
For individual files, use the following syntax:
wire {
  sourcePath {
    srcDir 'dirPath'
    include 'relativePath'
  }
}
```
 is expected behavior that gradle failed syncing without builded jar?

**Comment by oldergod** [comment]
I suspect the file doesn't exist when the build runs.
