### ISSUE TITLE
Wire doesn't support non-default file system: com.google.common.jimfs.JimfsFileSystem

### ISSUE THREAD

**Issue by liqin-z** [square/wire#2417]
Hi, I'm working on a maven project using wire-schema, the version is 4.5.2-jvm. I need to use the schema loader to read the protobuf idl directly from string and store them into Jimfs, however I'm getting the IllegalStateException when I create the schema loader. The code looks like below 
```
try {
          FileSystem fs = Jimfs.newFileSystem(Configuration.unix());
          String protoFileName = "ProtoTest.proto"
          Path path = fs.getPath("/" + protoFileName);
          Files.write(path, protoDefine.getBytes());
          
          SchemaLoader schemaLoader = new SchemaLoader(fs);   // this line will throw the error
          schemaLoader.initRoots(Lists.newArrayList(Location.get("/")), Lists.newArrayList(Location.get("/")));
          
          Schema schema = schemaLoader.loadSchema();
          ProtoFile protoFile = schema.protoFile("/" + protoFileName);
        } catch (Exception e) {
            throw new RuntimeException(e);
}
```

I have found the issue #2024 and seems he used the jimfs just fine. Wondering since which version does schemaloader no longer take jimfs? Thanks.

**Comment by JakeWharton** [comment]
Probably broken when Wire was rewritten to use Okio's filesystem which is very unfortunate.

**Comment by JakeWharton** [comment]
Is this the exception you are seeing: https://github.com/square/wire/blob/master/wire-schema/src/jvmMain/kotlin/com/squareup/wire/schema/internal/fileSystems.kt#L27
