### ISSUE TITLE
Wrong constructor parameter order on Kotlin classes

### ISSUE THREAD

**Issue by elvinas-liut** [square/wire#2432]
Currently it is not possible to use Wire to generate Kotlin classes and use them with Moshi to decode JSON data.

The error:

> java.lang.IllegalArgumentException: method com.example.proto.Subscriptions.<init> argument 1 has type java.lang.String, got java.lang.Integer
  at java.lang.reflect.Constructor.newInstance0(Native Method)
  at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
  at com.squareup.wire.KotlinConstructorBuilder.build(KotlinConstructorBuilder.kt:112)

If you check this line
https://github.com/square/wire/blob/master/wire-runtime/src/jvmMain/kotlin/com/squareup/wire/KotlinConstructorBuilder.kt#L116

It is clear that it is wrongly assumed that the order of the fields returned by `Class.getDeclaredFields` matches the order of the constructor parameters. But that's actually not true as the order is undefined (and in my case is alphabetical):
<img width="805" alt="Screenshot 2023-04-10 at 23 32 49" src="https://user-images.githubusercontent.com/2812754/230995137-e83c45d3-91ea-48f8-864c-2348c6820c00.png">

While the constructor is as this:
<img width="805" alt="Screenshot 2023-04-10 at 23 33 49" src="https://user-images.githubusercontent.com/16777267/230994267-11c2bbf6-0f92-4f66-8666-3092271b476f.png">

Here is a link to the documentation:

https://docs.oracle.com/javase/8/docs/api/java/lang/Class.html#getDeclaredFields--
> The elements in the returned array are not sorted and are not in any particular order.

**Comment by elvinas-liut** [comment]
As a workaround I ordered fields in alphabetical order on the Message object. Now it works but. Of course this is not future-proof but at least it does not block me.

```
message Subscriptions {
	int32  active_count = 2;
	string active_name = 1;
	int32  cancelled_count = 6;
	string cancelled_name = 5;
	int32  expired_count = 8;
	string expired_name = 7;
	int32  new_count = 4;
	string new_name = 3;
	string shop_uri = 9;
}
```

**Comment by oldergod** [comment]
Are you passing the `WireJsonAdapterFactory` to `Moshi` ?

**Comment by elvinas-liut** [comment]
Yup. Retrofit is defined like this:
```
Retrofit.Builder()
            .client(client.addInterceptor{
                it.proceed(it.request().newBuilder().header(
                        "Authorization",
                        Credentials.basic("admin", "admin")
                ).build())
            }.build())
            .addConverterFactory(
                MoshiConverterFactory.create(
                    Moshi.Builder().add(WireJsonAdapterFactory()).build()
                )
            )
            .baseUrl("https://api-test.example.com/")
            .build()
            .create(BackendInterface::class.java)
```

**Comment by oldergod** [comment]
Hmm. We have plenty json tests around JSON. Would you be able to add a test case which shows the problem?
Either with a sample project or a new test in [MoshiPizzaTest.kt](https://github.com/square/wire/blob/master/wire-moshi-adapter/src/test/java/com/squareup/wire/MoshiPizzaTest.kt) ?

**Comment by elvinas-liut** [comment]
I've created a sample project:
https://github.com/elvinas-liut/WireTest

Now the interesting part.

I've created two tests (similar to `MoshiPizzaTest.kt`): one with ordered object properties and one with unordered. And they both pass!
[ExampleUnitTest.kt](https://github.com/elvinas-liut/WireTest/blob/master/app/src/test/java/com/example/wiretest/ExampleUnitTest.kt
)

But if you'll try to build and run the app (e.g. on emulator) it crashes with the same error I reported. Source code used on the app is here: [ViewModel.kt](https://github.com/elvinas-liut/WireTest/blob/master/app/src/main/java/com/example/wiretest/ViewModel.kt)

I do not know why it works on tests but it might be related to the environment. For tests it uses local tools e.g. Amazon Corretto but devices are using OpenJDK with ART. As they are different implementations of Java SE the implementation of `Class.getDeclaredFields` may differ too. But it's just a guess.

**Comment by oldergod** [comment]
Thanks for the sample.

It looks like the problem is on us assuming that `Class.getDeclaredFields()` returns a sorted list BUT the doc says "The elements in the returned array are not sorted and are not in any particular order."

Interesting....

**Comment by oldergod** [comment]
We tried to avoid having to add indexes for all generated code but it looks like our new solution was not sufficient. We'll try to look into it soon.
