### ISSUE TITLE
Runtime Dependency kaml 0.20.0 has vulnerabilities

### ISSUE THREAD

**Issue by MurphySteven** [square/wire#2434]
Hi,

Not sure if this fits the security vulnerability reporting policy as its an external dependency, so I've raised the issue here.

All versions of wire-compiler have a runtime dependency on kaml version 0.20.0 which has vulnerabilities flagged against it.  It seems only the latest version, 0.53.0, has no known vulnerabilities.

**Comment by oldergod** [comment]
Cheers, I'll bump
