### ISSUE TITLE
protoPath configuration resolving is broken for Gradle > 8

### ISSUE THREAD

**Issue by sergei-lapin** [square/wire#2441]
While trying to resolve a `protoPath` configuration within build on Gradle >= 8 (tested on 8.0.2 and 8.1.1) one get the following error (tested with Wire 4.5.2-4.5.6):

```
Could not determine the dependencies of task ':proto-lib:generateMainProtos'.
> Resolving dependency configuration 'default' is not allowed as it is defined as 'canBeResolved=false'.
  Instead, a resolvable ('canBeResolved=true') dependency configuration that extends 'default' should be resolved.
```

[Here](https://github.com/sergei-lapin/issue-reproducers/tree/wire-gradle-issues) you can find a MRE (commit 2547967)

**Comment by oldergod** [comment]
Looking into supporting Gradle 8 very soon

**Comment by sergei-lapin** [comment]
Hi, @oldergod !
Is there any chance of pushing this through? 🙏

**Comment by oldergod** [comment]
It has been more difficult than expected. But I'm still working on it.

**Comment by oldergod** [comment]
Should be fixed with https://github.com/square/wire/pull/2563

**Comment by sergei-lapin** [comment]
Any chance on having this as 4.9.0-SNAPSHOT or 4.8.2, maybe?

**Comment by oldergod** [comment]
A snapshot should be ready once this job publishes: https://github.com/square/wire/actions/runs/5941469130

I want to do more testing internally before releasing 4.8.2

**Comment by oldergod** [comment]
Even the snapshot might not be published. Dokka is causing trouble... which I hope I'll be able to check tomorrow

**Comment by oldergod** [comment]
The snapshot is out if you wanna try @sergei-lapin 
https://s01.oss.sonatype.org/content/repositories/snapshots/com/squareup/wire/wire-gradle-plugin/4.9.0-SNAPSHOT/

**Comment by sergei-lapin** [comment]
@oldergod tried with Gradle 8.0.2 and 8.3 — the issue is fixed!
