### ISSUE TITLE
Unclear how to pull in missing Google protobufs

### ISSUE THREAD

**Issue by malachid** [square/wire#2444]
Using Wire 4.5.6

Our BE started importing "google/protobuf/field_mask.proto"

This resulted in `unable to resolve google.protobuf.FieldMask`

Adding a `protoPath` for `protobuf-java` results in all of:
- `Unresolved reference: ADAPTER`
- `Type mismatch: inferred type is UpdateUserProfileRequest? but FieldMask? was expected`
- `Type mismatch: inferred type is FieldMask but UpdateUserProfileRequest was expected`

Adding a `sourcePath` instead of a `protoPath` for `protobuf-java` results in:
- `Unresolved reference: ADAPTER`
- `Type mismatch: inferred type is MethodOptions? but HttpRule? was expected`
- `Type mismatch: inferred type is HttpRule but MethodOptions was expected`

That last set also happens if I use an `include` for the specific protos I want included.

As a side note, if I go back to the revision prior to the BE importing field_mask.proto, everything is working. If I then include protobuf-java in the compilation, then the build fails due to duplications.

Is there a correct way to use the referenced proto?

Thanks!

**Comment by oldergod** [comment]
So Wire doesn't know about FieldMask and doesn't have specific code to deal with it. This means that in order to use FieldMask, one has to ask Wire to generate them.
```kotlin
wire {
  sourcePath {
    srcDir("src/main/proto")
  }

  sourcePath {
    srcJar("com.google.protobuf:protobuf-java:<version>")
    include("google/protobuf/field_mask.proto")
  }

  kotlin {
  }
}
```

I had a proto like
```protobuf
syntax = "proto2";

package squareup;

import "google/protobuf/field_mask.proto";

message Player {
  optional string name = 1;
  optional int32 jersey_number = 2;
  optional google.protobuf.FieldMask field_mask = 3;
}
```

and was able to execute the following:
```kotlin
fun main() {
  val player = Player(
    name = "John",
    jersey_number = 33,
    field_mask = FieldMask(listOf("a", "b"))
  )
  println(Player.ADAPTER.decode(player.encode()))
}
```

I'm not sure why you're getting errors with stuff like `MethodOptions` or `HttpRule`. Those are not part of `FieldMask`, are they?

**Comment by malachid** [comment]
`FieldMask` does not appear to include `MethodOptions` or `HttpRule`.  Agreed that it was very confusing.

The only way we were able to get around it was to include a physical copy of `field_mask.proto` and change the `java_package` of it.  Every time it referenced `protobuf-java`, I got errors.

**Comment by oldergod** [comment]
Maybe you were also adding `protobuf-java` to compilation? which isn't needed

**Comment by oldergod** [comment]
Closing, no clear action to take.
