### ISSUE TITLE
Kotlin - make jsonName casing configurable

### ISSUE THREAD

**Issue by DougSig** [square/wire#2452]
Currently, the Kotlin generator sets `WireField.jsonName` to the camel case version of the field name. If I want to keep the field names as snake case, I have to do this for every field:
```
message ExampleMessage {
  ExampleField example_field = 1 [json_name = "example_field"];
}
```

**Comment by oldergod** [comment]
This follows the spec so it's unlikely we change anything in the behavior here.
```
  // JSON name of this field. The value is set by protocol compiler. If the
  // user has set a "json_name" option on this field, that option's value
  // will be used. Otherwise, it's deduced from the field's name by converting
  // it to camelCase.
  optional string json_name = 10;
```

https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/descriptor.proto#L255-L259

**Comment by jdbp-classpass** [comment]
I think `WireJsonTest` would be the place for the new tests? That's where the existing `writeIdentityValues` option is exercised.
