### ISSUE TITLE
how to custom the format of output java code

### ISSUE THREAD

**Issue by tennkou** [square/wire#2461]
my wire version is 4.3.0
question 1. by some reasons, my proto file has some fields witch has the same Type and Name, just like
   ` package com.a.b;
message Info {
    Apple Apple                 = 1;
}`
the default generated code for this field is Apple com_a_b_Apple;
can I custom my output format like "Apple apple" ?

question 2.  I used to use wire version 2.3.0-SNAPSHOT (wire-compiler-2.3.0-SNAPSHOT-jar-with-dependencies.jar) , it can generate java classes with getter and hasXXX methods. now i want to change version to 4.3.0, can version 4.3.0 generate classes with getter and hasXXX methods?

**Comment by oldergod** [comment]
1. No. You have to modify the proto schema.
2. Yes.
