### ISSUE TITLE
Name collisions still behave badly

### ISSUE THREAD

**Issue by JakeWharton** [square/wire#247]
```proto
package squareup.foobar;

option java_package = "com.squareup.wire";

message Message {
  message ProtoField {
    optional string boo = 1;
  }
}
```
<img width="540" alt="screen shot 2015-07-06 at 8 36 45 pm" src="https://cloud.githubusercontent.com/assets/66577/8536404/ee9d2dae-241e-11e5-8669-92730788df0d.png">

**Comment by swankjesse** [comment]
Looks like JavaPoet bugs.

**Comment by swankjesse** [comment]
This is fixed.
