### ISSUE TITLE
Replace TimeStamp type from java.time.Instant to ThreeTenABP 

### ISSUE THREAD

**Issue by skydoves** [square/wire#2473]
Is there any way to replace the TimeStamp type from `java.time.Instant` with `org.threeten.bp`, which comes from @JakeWharton's [ThreeTenABP](https://github.com/JakeWharton/ThreeTenABP)? Or do we need to use desugar to use `java.time.Instant` below API level 26?

**Comment by oldergod** [comment]
it's unlikely we'll be adding support for ThreeTenABP so [desugaring](https://developer.android.com/studio/write/java8-support-table) seems the best option indeed.

**Comment by skydoves** [comment]
Thanks for the quick response!
