### ISSUE TITLE
Allow setting a common wire prefix.

### ISSUE THREAD

**Issue by kshood** [square/wire#2479]
Problem: Proto libraries that set `option java_multiple_files = true;` can cause name conflicts between protoc and wire.

Proposed Solution: If wire added a common prefix, this would virtually guarantee that no conflict is possible. If this prefix is optional (and possibly set by the user) on a per-target basis, it would also allow incremental roll out.

**Comment by oldergod** [comment]
Could the [wire_package](https://github.com/square/wire/blob/master/wire-schema/src/jvmMain/resources/wire/extensions.proto#L65-L70) suffice?

**Comment by oldergod** [comment]
I would be worried about something which is configurable outside the `.proto` files because it would not translate to consumers of the library doing it.

**Comment by oldergod** [comment]
No clear actions to take.
