### ISSUE TITLE
Messages location is not resolved correctly

### ISSUE THREAD

**Issue by jianchaoxudd** [square/wire#2480]
If i have the following structure:
directory: src/protos/service/test.proto
directory: src/protos/service/common.proto
directory: src/protos/other/other.proto
`test.proto` has
```
syntax = "proto3";

package test;

import "service/common.proto";
import "other/other.proto";

message TestMessage {
    CommonMessage field = 1;
    other.OtherMessage field1 = 2;
}
```
`common.proto` has
```
syntax = "proto3";

package test;

message CommonMessage {
  SubMessage field = 1;
}

message SubMessage {
  string field = 1;
}
```
`other.proto` has
```
syntax = "proto3";

package other;

message OtherMessage {
    string field = 1;
}

```

If i am trying to load this through SchemaLoader 
```
    loader.initRoots(
      sourcePath = listOf(Location.get("src/protos/service")),
      protoPath =  listOf(Location.get("src/protos/service"), Location.get("src/protos")),
    )
    loader.loadSchema()
```

This will throw error:
```
common.proto needs to import service/common.proto
  for field field (..src/protos/service/common.proto:6:3)
  in message test.CommonMessage (..src/protos/service/common.proto:5:1)
```

By debugging through the loadSchema method, the following happens
1. load types for sourcePath first.
2. looks for imports
3. load types from imports (which it will overrides the type within sourcePath, hence it has different location now)
4. validator will check the type and found out that the location is not expected, hence the erorr

Is this expected?

**Comment by jianchaoxudd** [comment]
Plus, if i change common.proto to:
```
syntax = "proto3";

package test;

message CommonMessage {
  SubMessage field = 1;
}

message SubMessage {
  string field = 1;
}

enum State {
  Unknown = 0;
  OK = 1;
}
```

I got 
```
multiple enums share constant Unknown:
  1. test.State.Unknown (../src/protos/service/common.proto:14:3)
  2. test.State.Unknown (../src/protos/service/common.proto:14:3)
  for file ../src/protos/service/common.proto
```

**Comment by oldergod** [comment]
The working directory doesn't seem correctly set I think.

```
src/protos/service/test.proto
src/protos/service/common.proto
src/protos/other/other.proto
```

If `test.proto` imports `import "service/common.proto";`, this means the working directory is `src/protos`.
When initiating roots, what happens if you set the following?
```kotlin
   loader.initRoots(
      sourcePath = listOf(Location.get("src/protos")),
      protoPath =  listOf(), // it doesn't look like you need to resolve external proto dependencies so empty is good.
    )
    loader.loadSchema()
```

**Comment by jianchaoxudd** [comment]
If I leave the working directory to "src/protos", it works. But I don't want to load other directories under src/protos. 
For example, if I have the following protos. I don't want to load service2 as sourcePath
```
src/protos/service/test.proto
src/protos/service/common.proto
src/protos/other/other.proto
src/protos/service2/service2.proto
```

**Comment by oldergod** [comment]
What if you do `Location.get("src/protos", "service/test.proto")` and things like this?

**Comment by jianchaoxudd** [comment]
does that mean i can only load `test.proto`? but i want to load all of proto under service directory

**Comment by oldergod** [comment]
No clear actions to take.
