### ISSUE TITLE
Ability to use custom gRPC clients on Multiplatform

### ISSUE THREAD

**Issue by iTaysonLab** [square/wire#2484]
Hello!

I am currently developing a client for a service which uses Protobuf-over-WebSocket implementation instead of traditional HTTP requests, but to avoid boilerplate, I decided to use Wire's gRPC bindings.

The protobufs provide RPC information, so I can generate them, however:
- `CLIENT` role has the needed ADAPTER's in the method bindings, however it heavily depends on OkHttp/Wire gRPC runtime:
```kotlin
import com.squareup.wire.GrpcCall
import com.squareup.wire.GrpcClient
import com.squareup.wire.GrpcMethod

public class GrpcCommunity(
  private val client: GrpcClient,
) : Community {
  public override fun ClearSinglePartnerEventsAppPriority():
      GrpcCall<CCommunity_ClearSinglePartnerEventsAppPriority_Request, CCommunity_ClearSinglePartnerEventsAppPriority_Response>
      = client.newCall(GrpcMethod(
      path = "/Community/ClearSinglePartnerEventsAppPriority",
      requestAdapter = CCommunity_ClearSinglePartnerEventsAppPriority_Request.ADAPTER,
      responseAdapter = CCommunity_ClearSinglePartnerEventsAppPriority_Response.ADAPTER
  ))
```
Here, `CCommunity_ClearSinglePartnerEventsAppPriority_Request.ADAPTER` and `CCommunity_ClearSinglePartnerEventsAppPriority_Response.ADAPTER` are binded, removing the boilerplate in client implementation. It is a preferred approach, because everything is settled, but it has a direct dependency to `GrpcClient` which is not `open`, making custom implementations impossible.

- `SERVER` role does not provide ADAPTER's except for package name in `WireRpc`:
```kotlin
@WireRpc(
  path = "/CloudConfigStore/Download",
  requestAdapter = "steam.webui.cloudconfigstore.CCloudConfigStore_Download_Request#ADAPTER",
  responseAdapter = "steam.webui.cloudconfigstore.CCloudConfigStore_Download_Response#ADAPTER",
  sourceFile = "webui/service_cloudconfigstore.proto",
)
public suspend fun Download(request: CCloudConfigStore_Download_Request): CCloudConfigStore_Download_Response
```
Here, `requestAdapter` and `responseAdapter` are defined as package name references - which requires reflection on JVM and is not available at all in K/Native.

I've tried developing a custom workaround implementation for `GrpcClient`, but this will lead to conflicts and other errors if a library's user decides to import Wire's gRPC client for it's own needs.

Ideally, this could be an ability to provide custom imports compatible with `GrpcClient`, maybe something like an shared interface, using a configuration variable:
```kotlin
wire {
  kotlin {
    rpcRole = "client"
    rpcClientName = "com.example.MyGrpcClient"
  }
}
```

This issue is somewhat similar to #1962, but request/response adapter reflection was not mentioned in that issue.

Thanks!

**Comment by oldergod** [comment]
Could we just make `GrpcClient` open?

**Comment by iTaysonLab** [comment]
Well, I have tried it, and it just doesn't work :(

Because GrpcClient's actual JVM implementation has private constructors (and differs from the definition), IDE just keeps me saying `Cannot access '<init>': it is private in 'GrpcClient'` even when trying to make basic class like:

```kotlin
import com.squareup.wire.GrpcCall
import com.squareup.wire.GrpcClient
import com.squareup.wire.GrpcMethod
import com.squareup.wire.GrpcStreamingCall

class CustomGrpcClient: GrpcClient() {
    override fun <S : Any, R : Any> newCall(method: GrpcMethod<S, R>): GrpcCall<S, R> {
        TODO("Not yet implemented")
    }

    override fun <S : Any, R : Any> newStreamingCall(method: GrpcMethod<S, R>): GrpcStreamingCall<S, R> {
        TODO("Not yet implemented")
    }
}
```

However, I'm trying to do it in `common` sourceset (while K/M project targets are only JVM and Android separately). Kotlin is `1.9.10` and Wire is `4.9.1`.

**Comment by oldergod** [comment]
Hmmm, I think it works if you implement it in the target directly?
I don't think you can do that in common right now because the declaration of `GrpcClient` doesn't have a constructor at all: `expect abstract class GrpcClient`

**Comment by iTaysonLab** [comment]
> implement it in the target directly

Tried, however the same code in the `jvmMain` target throws the same private constructor exception as well (while it being the only one constructor at all).

By the way, adding a non-JVM target enables me to do something in `commonMain`, it throws me an `This class does not have a constructor` exception, while removing the `()` gives me `This type has a constructor, and thus must be initialized here`.

What I could possible suggest is making `GrpcClient` a common interface with a platform implementation, but I fear that it would break backward compatibility as well.

**Comment by oldergod** [comment]
Hmm I think the problem is that one can create their own implementation of GrpcClient for JS and native, but not for the JVM.
And on top of that, you actually want to write something in common main for all platforms to use?

**Comment by iTaysonLab** [comment]
> you actually want to write something in common main for all platforms to use

Yeah, that's what I want.

My library is communicating with the Steam API using a custom-made multiplatform WebSocket transport. They have defined RPC services in protobufs that communicate with their infrastructure, however it is not "real" gRPC:

```proto
service Authentication {
  rpc BeginAuthSessionViaCredentials (.CAuthentication_BeginAuthSessionViaCredentials_Request) returns (.CAuthentication_BeginAuthSessionViaCredentials_Response);
}
```
(source: https://github.com/SteamDatabase/Protobufs/blob/908ae83fb4e86dbff60ccb008d4ab089196e5bf7/webui/service_authentication.proto#L207C9-L207C23)

So, how does it work: my "gRPC" client receives a request with both adapters + service name supplied, it sends the data through a WebSocket instance and receives it back with automatic decoding. Wire's generation is enough for that, I just need a way to provide a custom `GrpcClient` implementation.

I can do it now by supplying adapters + service names manually each time I want to use an API, but I would like to reduce the boilerplate amount, transforming this:

```kotlin
steamClient.unifiedMessages.execute(
            signed = false,
            methodName = "Authentication.BeginAuthSessionViaQR",
            requestAdapter = CAuthentication_BeginAuthSessionViaQR_Request.ADAPTER,
            responseAdapter = CAuthentication_BeginAuthSessionViaQR_Response.ADAPTER,
            requestData = CAuthentication_BeginAuthSessionViaQR_Request(...)
)
```

into something like this:
```kotlin
steamClient.unifiedMessages.unsignedService<AuthenticationService>.BeginAuthSessionViaQR(
            CAuthentication_BeginAuthSessionViaQR_Request(...)
)
```
(For Native platforms it would be somewhat different due to absence of `Proxy` and reflection, yet still it's very helpful in the JVM world)

I know that this is a highly specific request, but this modification would be very helpful for further code size reducing and improved support for various non-HTTPS RPC implementations.

Thanks!
