### ISSUE TITLE
OneOf field is missing option value

### ISSUE THREAD

**Issue by jianchaoxudd** [square/wire#2503]
Protobuf3 now support option in oneOf field. However, in Wire it doesn't have option in the OneOf field

Example:
```

extend google.protobuf.OneofOptions {
  optional int32 my_option = 12345;
}

message Object{
  oneof oneofField {
    option (my_option) = 54321;
    string oneOfOne = 102;
    int32 oneOfTwo = 103;
  }
}

```

In Wire [OneOf](https://github.com/square/wire/blob/master/wire-schema/src/commonMain/kotlin/com/squareup/wire/schema/OneOf.kt) class doesn't have Options.

**Comment by oldergod** [comment]
Correct. We can parse them since #2242 but cannot fetch the set values. Is it something you need?

**Comment by jianchaoxudd** [comment]
> Correct. We can parse them since #2242 but cannot fetch the set values. Is it something you need?

Yes, we need the option value to enable more flexible use cases based on the value.

**Comment by oldergod** [comment]
I'll try to address that next week.
