### ISSUE TITLE
When using `protoLibrary = true`, adding library dependencies via `api` or `implementation` are not added to `protoPath`

### ISSUE THREAD

**Issue by Nava2** [square/wire#2614]
As described, creating a `protoLibrary = true` project that has Kotlin sources, e.g.:
```kotlin
// library project
wire {
  protoLibrary = true
  kotlin {}
}
```

For a consumer project
```kotlin
// consumer project
dependencies {
  // This does not add the library to the `protoPath` configuration
  implementation(project(":library-project"))

  // Without, proto fails to compile
  // protoPath(project(":library-project"))
}

wire {
  kotlin {}
}
```

**Comment by oldergod** [comment]
Hi, this works as expected. `protoLibrary` adds the `.proto` files to the artifact.
`implementation` will only add dependencies on the artifact's classes. You have to manually define how you want to depend on the artifact's protos by using either `protoPath` or `sourcePath`.

**Comment by Nava2** [comment]
Hmm, okay. It'd be great if this was a potential feature to opt-in to. It seems a bit odd to require duplicated entries for most cases.

**Comment by oldergod** [comment]
I wonder if it's be possible for you to create a configuration which would apply both `implementation` and `protoPath`.

**Comment by oldergod** [comment]
I'll close for we are not taking actions on this.

**Comment by Nava2** [comment]
Sounds good to me!
