### ISSUE TITLE
java.lang.IllegalArgumentException: No WireType for value

### ISSUE THREAD

**Issue by ptjob** [square/wire#262]
code:
Wire wire = new Wire();
VerifyTicketRsp ticketRsp = wire.parseFrom(moaResult.objectBytes, VerifyTicketRsp.class);

java.lang.IllegalArgumentException: No WireType for value 118
  at com.squareup.wire.WireType.valueOf(WireType.java:36) 
  at com.squareup.wire.MessageAdapter.read(MessageAdapter.java:521) 
  at com.squareup.wire.Wire.parseFrom(Wire.java:144) 
  at com.squareup.wire.Wire.parseFrom(Wire.java:135)

**Comment by danrice-square** [comment]
This sounds like corruption in the data source. You could try to parse it with standard protoc:

```
protoc --decode_raw < input_file
```

**Comment by ptjob** [comment]
the problem come sometime. almost 1/100000

**Comment by swankjesse** [comment]
No action to take here quite yet. If you can provide us with an example, that'd be awesome.

(Also, we now throw an IOException type in this case, which should avoid crashing your app.)

**Comment by fangzhzh** [comment]
We have the same problem, we saw this crash in our crash log, but we can't reproduce it.

I guess it's cache problem, and it's just guess.
So my question is:
@ptjob Do you use a static Wire like this
``
public static Wire WIRE = new Wire();
``
