### ISSUE TITLE
Option to remove enum prefixes in kotlin

### ISSUE THREAD

**Issue by jephthia** [square/wire#2648]
Is there an option to generate enums and strip the prefix? For example with a proto like the following:
```protobuf
syntax = "proto3";

enum ProjectCategory {
    PROJECT_CATEGORY_UNKNOWN = 0;
    PROJECT_CATEGORY_EXAMPLE = 1;
}
```

Some languages have an option (or do it by default) to generate the following:
```rust
enum ProjectCategory {
    Unknown,
    Example,
}
```

But currently in kotlin the generated code is
```kotlin
public enum class ProjectCategory(
  override val `value`: Int,
) : WireEnum {
  PROJECT_CATEGORY_UNKNOWN(0),
  PROJECT_CATEGORY_EXAMPLE(1),
  // ...
}
```  

Would it be possible to add an option so that we could use
```kotlin
ProjectCategory.EXAMPLE
```
instead of
```kotlin
ProjectCategory.PROJECT_CATEGORY_EXAMPLE
```

**Comment by oldergod** [comment]
I'm assuming those prefixes are used to avoid problems when generating code in C and the like?
I understand the use case and it's however unlikely we'll have enough room to implement this.
Their necessity could be decreased with more organized namespaces I think?

**Comment by jephthia** [comment]
That's correct, the prefixes are there because in some languages they create naming conflicts, but in languages where such conflicts don't exist like Kotlin and Rust for example, the prefix can safely be removed. But I understand if there's no room to implement this, it isn't a deal breaker after all.
