### ISSUE TITLE
LinuxArm64 Target support

### ISSUE THREAD

**Issue by ShayOinif** [square/wire#2732]
Hello, I use wire-runtime in my projects
on linuxArm64 target.
Can you add the target to at least wire-runtime?

Regards,
Shay OInif

**Comment by ShayOinif** [comment]
While we are at it..
I see that through out the entire repo and in generated code the indentation is 2 white spaces.
Any particular reason for 2 instead 4?

**Comment by ShayOinif** [comment]
And I created a pull request:  #2733

**Comment by JakeWharton** [comment]
2 is simply the correct amount!
