### ISSUE TITLE
generated duplicate class when use Wire with Jetpack proto datastore?

### ISSUE THREAD

**Issue by pennya** [square/wire#2759]
I'm facing a problem setting up the wire plugin in my Android project.

when i use wire with Jecpack proto datastore, then the following error occurs.
error: duplicate class: xxxx

I know proto datastore use standard protocol buffers library like protobuf-java-lite

how to solve it?  
Is Wire and proto datastore compatible with each other?

**Comment by oldergod** [comment]
What class is getting duplicated? And who is generating them apart Wire ?

**Comment by pennya** [comment]
@oldergod it is custom class compiled with each compiler (protoc and wire compiler)
@JakeWharton Is there any problem with using Wire in jetpack datastore?

I made a separate module and the module was handled to use a Wire Compiler, and the issue of duplicate classes disappeared.
Finally, I succeeded in building the compilation build.
Thanks for answering my questions.

**Comment by oldergod** [comment]
Another way for you to avoid conflict if you're using both protoc and Wire is to add the wire_package option to your `.proto` files. example: https://github.com/square/wire/blob/82a1dead3feb1135664ee0ddee4370bbc623dce0/wire-protoc-compatibility-tests/src/main/proto/squareup/proto3/kotlin/extensions/wire_message.proto#L20-L22

**Comment by pennya** [comment]
@JakeWharton 
Have you ever used the Jetpack Proto Datastore library?
Is there any problem in using classes generated by the Wire Compiler?
Do the classes generated by Wire require any additional work during Serialization and Deserialization with Jetpack DataStore?
Thank you in advance for your answer.

**Comment by JakeWharton** [comment]
> Have you ever used the Jetpack Proto Datastore library?

I have not.

> Is there any problem in using classes generated by the Wire Compiler?

Yes. The proto datastore relies on Google protobuf files for serialization. If you want to use Wire you will have to write a custom serializer and depend only on the core of datastore (i.e., not proto or preference versions).
