### ISSUE TITLE
Wire doesn't appear to be compatible with the configuration cache in gradle 8+

### ISSUE THREAD

**Issue by staktrace** [square/wire#2837]
Standalone minimal reproducer project is at https://github.com/staktrace/wire-bug-20240226-cc. Basically, when wire is run with the configuration cache enabled and gradle 8+, pretty basic operations fail as wire is unable to locate all the necessary input files.

This appears to be similar to https://github.com/square/wire/issues/2815

**Comment by staktrace** [comment]
AFAICT wire 5.0.0-alpha.square.3 fixes this problem. But we should probably still add this as a testcase in wire so it doesn't regress

**Comment by staktrace** [comment]
Adding a test in https://github.com/square/wire/pull/2890

**Comment by staktrace** [comment]
So although the minimal reproducer project in https://github.com/staktrace/wire-bug-20240226-cc works now, I'm still seeing a problem in real-world usage that looks the same (configuration cache enabled, gradle 8+, wire 5.0+) so I'm going to reopen this issue while I investigate.

**Comment by staktrace** [comment]
5.0.0-alpha.square.9 at least seems to not have the problem any more. I guess I'll close this

**Comment by oldergod** [comment]
@staktrace I don't think this version exists though?

**Comment by staktrace** [comment]
Lol we're using so it definitely does exist! https://artifactory.global.square/ui/native/square-public/com/squareup/wire/wire-bom/5.0.0-alpha.square.9/
