### ISSUE TITLE
Why does Wire throw and not fallback to the default value if a required enum value is missing?

### ISSUE THREAD

**Issue by jameshreaver** [square/wire#2857]
Hi @oldergod,
What is the rationale behind Wire's implementation of proto2 default enum values? Specifically, if a required enum field is missing, why does the wire implementation for proto2 throw an exception, rather than defaulting to the first valid value of the enum as per protobuf 2 specifications (proto3 implementation does default to the enum 0)? For instance:
```
syntax = "proto2";
enum MyEnum {
  MY_A = 0;
  MY_B = 1;
}
message MyProto {
  required MyEnum my_enum = 1;
}
```
generates
```
override fun decode(reader: ProtoReader): MyProto {
  var my_enum: MyEnum? = null
  val unknownFields = reader.forEachTag { tag ->
    when (tag) {
      1 -> try {
        my_enum = MyEnum.ADAPTER.decode(reader)
      } catch (e: ProtoAdapter.EnumConstantNotFoundException) {
        reader.addUnknownField(tag, FieldEncoding.VARINT, e.value.toLong())
      }
      else -> reader.readUnknownField(tag)
    }
  }
  return MyProto(
    my_enum = my_enum ?: throw missingRequiredFields(my_enum, "my_enum"),
    unknownFields = unknownFields
  )
}
```
Proto3's wire implementation does default to the enum 0, so why does proto2's implementation not?
Thanks!

P.S. I'm also curious as to why default value are supported (in the sense that they lead to the generation of a static field e.g. `MyEnum.DEFAULT_<VALUE>` but they are not actually used anywhere in the generated code.

**Comment by oldergod** [comment]
Wire throws if the field is _required_ and missing. That's the spec for required field. What value would you set otherwise? There are no default values for types in proto2 (while there is one for proto3)

**Comment by jameshreaver** [comment]
The proto2 spec say that it should return the first enum value (though, unlike proto3, this doesn’t have to be UNSPECIFIED)

**Comment by oldergod** [comment]
I feel like there are two discussions happening.

1. Wire throws if a required field has no value on decoding.
2. Default enum values on proto2 may be the first constant but Wire doesn't set fields to their default value on decoding.

**Comment by jameshreaver** [comment]
Correct. For point 1, I just wanted to check this behaviour follows the proto2 language guide. For point 2, I believe instead that Wire should return default values according to the specs, especially for optional fields.

**Comment by JakeWharton** [comment]
Default values are not set so that you can discern whether a value was present or absent in the actual bytes. You can use `Wire.get` to fallback to the default in Java, or just `?:` in Kotlin.
