### ISSUE TITLE
Merge Redactor into ReflectiveMessageAdapter

### ISSUE THREAD

**Issue by JakeWharton** [square/wire#286]
Redacting behavior is a property of the message adapter implementation.

**Comment by swankjesse** [comment]
Is redacting about toString or toBytes? I thought it was only the former.

**Comment by JakeWharton** [comment]
Me too. Apparently there's a thing that nulls fields though. No idea what it's use for.

**Comment by swankjesse** [comment]
Let's sweep that under the rug unless @mattprecious prefers otherwise.

**Comment by JakeWharton** [comment]
Apparently it's being used. See http://go/codesearch?q=com.squareup.wire.Redactor
