### ISSUE TITLE
Serialization bytes do not match on-wire bytes

### ISSUE THREAD

**Issue by JakeWharton** [square/wire#288]
The class is serialized adjacent to the bytes instead of just bytes.

**Comment by swankjesse** [comment]
Are you referring to Java serialization? That's non-optional.

**Comment by swankjesse** [comment]
Ahh, now that I've seen `com.squareup.wire.MessageSerializedForm` I understand a little better. What would you prefer?

**Comment by JakeWharton** [comment]
I was hoping it would only be the message bytes. If you serialize to a
DataOutputStream or your write to a ProtoWriter you'd get the same bytes.

**Comment by swankjesse** [comment]
The problem is that when you deserialize, `ProtoReader` requires the caller provide the expected type. DataInputStream assumes the bytes-on-the-wire are self-describing.
