### ISSUE TITLE
Incompatible public classes without major version change

### ISSUE THREAD

**Issue by gvaish** [square/wire#302]
This breaks the definition of the version number.

#### Problem

The major version has remained the same but public interface has changed such that it is incompatible.

v1.3.1: https://github.com/square/wire/blob/wire-1.3.1/wire-runtime/src/main/java/com/squareup/wire/Message.java#L151-L155
v1.8.0: https://github.com/square/wire/blob/wire-1.8.0/wire-runtime/src/main/java/com/squareup/wire/Message.java#L154-L164

#### Questions

* Can we bring back the `Message(Builder)` ctor?

#### Suggestion:

* Introduce the old constructor

```java
protected Message(Builder b) {
   this();
   setBuilder(b);
}
```

This makes `1.8.1` (or whatever) compatible with all the older versions `1.x`

**Comment by JakeWharton** [comment]
What were you using it for?

**Comment by JakeWharton** [comment]
The project isn't following semver or anything so really we're under no requirement to bump the major version. In 1.4 we replaced and entire class in the public API with one from a new dependency.

**Comment by JakeWharton** [comment]
I'd also argue that these methods are only for use by generated code and not truly part of the public API. There's a lot of these and we most definitely do not guarantee stability across releases. With every version the generated code must be updated in tandem. Otherwise nearly every release would be a major release.

We'll make that explicit with an annotation or Javadoc comment in the future.

**Comment by gvaish** [comment]
@JakeWharton I guess, it's less to do with semver and more to do with the spirit of version conventions to be followed.

For wider adoption and ease of integration, it is important to follow best practices and conventions used widely in the industry. SemVer is just one of them.

-----

Coming to the first question - "What were you using it for?"

My project has dependencies on two libraries - one uses `1.3.3` while the other `1.8.0` resulting in a conflict when including both. I have also reached out the library owners to provide an update.

-----

And to your last point, here's the thing:

##### Step 1.
LibraryA uses `wire-compiler@v1.3.3` and generates the model classes. The generated code is:

```
final class Model1 extends Message {
  Model1(Builder b) {
    super(b);
  }
}
```

##### Step 2.

LibraryB uses `wire-compiler@v1.8.0` and generates the model classes.

The generated code is:

```
final class Model2 extends Message {
  Model2(Builder b) {
    super();
    setBuilder(b);
  }
}
```

Even though the `Message` class is not to be used in `public` domain, do you think both `Model1` and `Model2` can be used in the same app?

**You cannot** because only one of the constructors is available.

*Adding* a new feature is *not* a breaking change, *removing* an existing *is*.

**Comment by JakeWharton** [comment]
Yes we know how backwards compatibility works. Like I said, we removed a
public type and replaced it with Okio in 1.4 so those versions won't
interop even if that constrictor is restored. And like I also said, we
currently provide no compatibility guarantees of the generated code across
versions either. You must regenerate the types with each update.

**Comment by gvaish** [comment]
Ok... hopefully the repository owners update to the latest versions at the earliest.

**Comment by JakeWharton** [comment]
With 2.0 we will make sure to make every effort to avoid this situation.
1.x was a bit of wild west just trying to get everything off the ground and
working.

**Comment by gvaish** [comment]
@JakeWharton Understand the race between release-rush and best practices.

Looking forward to v2.0 ASAP.

**Comment by swankjesse** [comment]
Yeah, our design for 2.x is more stable.
