### ISSUE TITLE
ProtoReader RECURSION_LIMIT is not configurable and is not following protobuf default 

### ISSUE THREAD

**Issue by jianchaoxudd** [square/wire#3085]
Hi team,

The [RECURSION_LIMIT=65 in ProtoReader](https://github.com/square/wire/blob/master/wire-runtime/src/commonMain/kotlin/com/squareup/wire/ProtoReader.kt#L525) is not configurable where grpc allows configurable limit and it is not following [protobuf default(100)](https://protobuf.dev/reference/cpp/api-docs/google.protobuf.io.coded_stream/#:~:text=Recursion%20Limit&text=Sets%20the%20maximum%20recursion%20depth,The%20default%20is%20100.&text=Decrements%20the%20recursion%20depth%20if%20possible.)

**Comment by oldergod** [comment]
Have you needed more than 65?

**Comment by jianchaoxudd** [comment]
hey @oldergod ,

Yes, our service has more than 65 depth, but not more than 100(protobuf default) yet.

**Comment by oldergod** [comment]
I think we'll change our value to 100 for now. We can offer an option to configure it in the future.

**Comment by jianchaoxudd** [comment]
Sounds good. Changing to 100 is good enough for now.

**Comment by jianchaoxudd** [comment]
Thanks for the quick fix! @oldergod , how long it takes to release the fix?

**Comment by oldergod** [comment]
This week
