### ISSUE TITLE
Conflict Messages during loadSchema

### ISSUE THREAD

**Issue by jianchaoxudd** [square/wire#3130]
Hi team,

We are seeing a `protoForTesting/test/test_service_one.proto needs to import protoForTesting/test/test_service_two.proto` exception when we load the following protobufs using `SchemaLoader`.

Proto directory structure:
```
- protoForTesting
   - common
       - common.proto
   - test
       - test_service_one.proto
       - test_service_two.proto
```

common.proto (**NOTE: no package definition):**
```
syntax = "proto3";

message Common {

}
```

test_service_one.proto
```
syntax = "proto3";

package test;

import "common/common.proto";

service TestingServiceOne {

  rpc TestingMethod(TestingServiceOneRequest) returns (TestingServiceOneResponse);
}

message TestingServiceOneRequest {
  Common common = 1;
}

message TestingServiceOneResponse {

}
```
test_service_two.proto:  **NOTE: the package definition is same as test_service_one.proto**
```
syntax = "proto3";

package test;

service TestingServiceTwo {

  rpc TestingTwoMethod(TestingTwoRequest) returns (TestingTwoResponse);

}

message TestingTwoRequest {
}

message TestingTwoResponse {
}

message Common {

}
```

And here is how we load the protobuf.
```
SchemaLoader(fs).apply {
        initRoots(
            sourcePath = listof(Location.get("", "protoForTesting/test/test_service_one.proto"), Location.get("", "protoForTesting/test/test_service_two.proto")),
            protoPath = listof(Location.get("", "protoForTesting")),
        )
        permitPackageCycles = true
        loadExhaustively = true
    }.loadSchema()
```

So the `test_service_one.proto` is importing the `Common` from `common/common.proto`, however it seems the Loader is trying to load the `Common` from the `test_service_two.proto` and complain.

**Comment by oldergod** [comment]
Thanks for reporting.

It's an interesting one. I think protoc and Wire don't do the same thing here. Wire will see `Common` in `message TestingServiceOneRequest { Common common = 1; }` and by default assumes the type is defined in the same package as the file which here is `test`.
Were you to do the following, it should compile.
```protobuf
message TestingServiceOneRequest {
  .Common common = 1; // the leading dot is the difference
}
```

I'm not sure it's worth doing something in Wire, knowing what to do might take more time than any fix.

**Comment by jianchaoxudd** [comment]
Thanks for the information.
```
message TestingServiceOneRequest {
  .Common common = 1; // the leading dot is the difference
}
```
does pass the compile.

**Comment by oldergod** [comment]
Closing as we don't intend to change Wire's behavior.
