### ISSUE TITLE
Extension classes should declare a `List<Extension>`

### ISSUE THREAD

**Issue by swankjesse** [square/wire#322]
So we don't need as much reflection in `Wire` when building the extensions map.

**Comment by swankjesse** [comment]
I'm going to punt on this because we already have the `registry_class` option.

@danrice-square is the registry class option popular?

**Comment by JakeWharton** [comment]
I might still attempt this change this week. Seems very straightforward.

**Comment by swankjesse** [comment]
If you do, please delete the `registry_class` alternative!
