### ISSUE TITLE
Please update your wire LICENSE

### ISSUE THREAD

**Issue by coder-suncc** [square/wire#392]
Hi,gays~
Thanks for all your outstanding contribution to provide this component to us。
However,there isn't a open-resource license,which make it a little difficult for us to use your library in our project。Would you update you License ? many thanks

---------------------------------
![cc](https://cloud.githubusercontent.com/assets/10388149/9869882/1f13f63e-5bba-11e5-85ea-636e5e9e0f4b.png)

**Comment by swankjesse** [comment]
Fixed. https://github.com/square/wire/blob/master/wire-runtime/src/main/java/com/squareup/wire/Message.java#L2

**Comment by JakeWharton** [comment]
The license is applied in the README as well. What you linked was the template which is included in the license. Changing this would be incorrect.
