### ISSUE TITLE
repeated field becomes a null instead of empty list

### ISSUE THREAD

**Issue by valeriyo** [square/wire#395]
It appears that in 1.8.0, 
 - A repeated field is initialized as empty list when built in code. For example, `new Person.Builder().build()` will set `addresses` field to an empty list.
 - However, if same field is missing in JSON as when receiving `{}`, the `addresses` field is set to null.

This inconsistent behavior leads to NPEs, since unit tests pass with flying colors, but real-life payloads may contain nulls.

**Comment by JakeWharton** [comment]
This is already fixed on `master`. Repeated fields will now never be `null`.

**Comment by valeriyo** [comment]
we'll pick up the fix with 2.0 then. thanks, Jake!
