### ISSUE TITLE
Android code generation

### ISSUE THREAD

**Issue by JakeWharton** [square/wire#413]
* [x] Implement `Parcelable`, likely by delegating to the adapter for `byte[]` (#435)
* [ ] 'support-annotations' `@Nullable`? (#225) 

Triggered by JavaGenerator options.

**Comment by EddieRingle** [comment]
@JakeWharton The Parcelable code that is generated for `createFromParcel()` fails to compile due to an unhandled checked exception here: https://github.com/square/wire/blob/master/wire-java-generator/src/main/java/com/squareup/wire/java/JavaGenerator.java#L467

**Comment by JakeWharton** [comment]
Can you file an issue or send a PR?

**Comment by EddieRingle** [comment]
@JakeWharton see #470
