### ISSUE TITLE
ProtoAdapter method naming inconsistency

### ISSUE THREAD

**Issue by JakeWharton** [square/wire#422]
We have `encode` and `encodeTagged` but `encodedSize` is named the same for both tagged and non-tagged variants.

**Comment by JakeWharton** [comment]
`encodedSizeTagged`? Quite the mouthful...

**Comment by swankjesse** [comment]
Hm.

**Comment by swankjesse** [comment]
`encode`/`encodeWithTag`
`encodedSize`/`encodedSizeWithTag`
?
