### ISSUE TITLE
Consider switch to Gradle

### ISSUE THREAD

**Issue by JakeWharton** [square/wire#440]
Now that we have variants of generated code, the inability to compile the variants (and necessity to suffix their filenames) as a sanity check is unfortunate. With Gradle, various test source sets could be created in which the generation could be done and independent dependencies (such as Android) could be provided to test compilation as well as the normal file comparison checks.

**Comment by JakeWharton** [comment]
Plus we could pull the Gradle plugin in-repo.

**Comment by swankjesse** [comment]
Gradle plugin in-repo is good enough motivation for me. I'm not considering this a release blocker for 2.0.

**Comment by ajaysarda** [comment]
+1 on this as we use gradle as our build tool for all projects.

**Comment by JakeWharton** [comment]
The use of the build system for Wire has no effect on what downstream projects use. If you use Gradle, use [our Gradle plugin][1] when it's released with 2.0.

 [1]: https://github.com/square/wire-gradle-plugin

**Comment by FranciscoE-Reuters** [comment]
Having a configurable gradle plugin or an update of @JakeWharton's would be nice.

**Comment by JakeWharton** [comment]
That is unrelated to this issue. We are considering Gradle for the build
system of Wire for compiling different versions of the generated code with
different dependencies.

**Comment by EddieRingle** [comment]
@JakeWharton I was interested in helping with this. I began a branch that converted most of what exists to Gradle, but I'm unsure of a few things:

* As far as I know, there's no easy way to build a Maven plugin within Gradle (short of executing a Maven process, I suppose). Would the Maven plugin module just be deprecated in favor of the Gradle plugin?
* It seems that it would also be difficult to both have the Gradle plugin in-repo while also packaging for external use. I've hit the following cycle so far:
  1. The sample wants to use the plugin to generate messages
  2. The plugin requires the `wire-compiler` module
  3. Plugin can't be in `buildSrc` and depend on `wire-compiler` (can it?), nor can you apply a subproject as a plugin (i.e., `apply from: project(':wire-gradle-plugin')`).

Do you have any thoughts?

**Comment by swankjesse** [comment]
What do other tools do?

**Comment by JakeWharton** [comment]
You can package the Gradle plugin but it cannot be used in the project by
another module. Maven's reactor is mutable which is what allows it to work
for it. It can be tested, though, using the new (and crappy) Gradle TestKit.

The advantage of Gradle is testing the variants of code generation
properly. The plugins can both be packaged separately at worst.

**Comment by EddieRingle** [comment]
@JakeWharton So maybe keep the Gradle plugin in-repo and move samples to another repo?

**Comment by EddieRingle** [comment]
@swankjesse @JakeWharton I have a branch with both the Gradle plugin and the samples in-repo. Before I submit a PR, should I delete the existing Maven build files?

**Comment by JakeWharton** [comment]
Yes. Two build systems are always worse than one, even if that one is wrong.

**Comment by EddieRingle** [comment]
@JakeWharton Delete the Maven plugin as well, then?

**Comment by JakeWharton** [comment]
There should not be a technical reason preventing a Maven plugin to be
built with Gradle. The hard part now is that we rely on a Maven plugin to
parse annotations and generate a file for us. We can switch to creating
that file manually (it's the XML descriptor for <configuration> in
consuming projects).

Just leave it in its folder with its pom for now.

**Comment by JakeWharton** [comment]
Or at worse we can split it out later...

**Comment by EddieRingle** [comment]
Submitted PR here: https://github.com/square/wire/pull/560

**Comment by astapleton** [comment]
What are the current plans for resolving this issue? I see that both the PRs related to it have not been updated since February and the gradle plugin repo has not been touched since August 2015.

**Comment by EddieRingle** [comment]
@astapleton they didn't move on my PR for one reason or another (likely just busy with other things). I haven't updated it since I heard @JakeWharton mention they were doing the work themselves anyway.

**Comment by gengjiawen** [comment]
I think a gradle-wire-plugin is really necessary.Without this plugin, working with gradle is really tedious.

**Comment by wilsonssss** [comment]
can anyone help? @JakeWharton still working on gradle-wire-plugin?

**Comment by swankjesse** [comment]
Done!
