### ISSUE TITLE
Collections.sort extension fields and their list for determinism

### ISSUE THREAD

**Issue by JakeWharton** [square/wire#445]
Right now the order is defined based on parse order. We should sort by name or tag value so that the parse order does not matter and does not thus cause generated code diff noise.

**Comment by swankjesse** [comment]
I really like parse order for fields. At least in the messages we write, parse order is deliberate!

**Comment by JakeWharton** [comment]
Yeah I phrased this wrong. The sort was for emitted fields which list things that shouldn't be determined by parse order. Declaration order in a proto should very much be honored.
