### ISSUE TITLE
Option allow_alias = true causes enum exception

### ISSUE THREAD

**Issue by sureshjoshi** [square/wire#508]
Hey all, loving the 2.0.0 library... I have a piece of code where I cannot change the protobuf unfortunately. It uses this repeated enum:

    enum System_Enum{
      option allow_alias = true;
      SYSTEM_ENUM_NONE  = 0;
      SYSTEM_NAME_SIZE  = 8;
      SYSTEM_SN_SIZE    = 17;
      SYSTEM_FW_SIZE    = 6;
      SYSTEM_HW_SIZE    = 6;
      SYSTEM_PCB_SIZE   = 17;
    }

After running it through Wire, I get:

    public static System_Enum fromValue(int value) {
      switch (value) {
        case 0: return SYSTEM_ENUM_NONE;
        case 8: return SYSTEM_NAME_SIZE;
        case 17: return SYSTEM_SN_SIZE;
        case 6: return SYSTEM_FW_SIZE;
        case 6: return SYSTEM_HW_SIZE;
        case 17: return SYSTEM_PCB_SIZE;
        default: return null;
      }
    }

Which then errors out during compilation as: 
Error:(44, 7) error: duplicate case label

Do, my question is whether this should fail out during the wire-compiler stage, or whether it should be allowed? Is this a bug with the repeated cases in a switch?

Again... Not my .proto file - so no power to change.

Also, please note that it is apparently valid according to Google: https://developers.google.com/protocol-buffers/docs/proto?hl=en#enum

**Comment by JakeWharton** [comment]
Yeah I guess the first value needs to win in this case.

**Comment by swankjesse** [comment]
Yeah we should fix this. Wanna send a pull request?
