### ISSUE TITLE
Wire-compiler-2.0.1-jar-with-dependencies.jar  is not in the release package

### ISSUE THREAD

**Issue by iwanglian** [square/wire#517]
In the user guide,  it tell the user a command line to generate Java code, 

'''
% java -jar wire-compiler-VERSION-jar-with-dependencies.jar \
    --proto_path=src/main/proto \
    --java_out=out \
    squareup/dinosaurs/dinosaur.proto \
    squareup/geology/period.proto
Writing com.squareup.dinosaurs.Dinosaur to out
Writing com.squareup.geology.Period to out
'''

But the Relase package only contain the source code.

**Comment by swankjesse** [comment]
http://search.maven.org/remotecontent?filepath=com/squareup/wire/wire-compiler/2.0.1/wire-compiler-2.0.1-jar-with-dependencies.jar

**Comment by swankjesse** [comment]
Maven central search is quite powerful, by the way.
http://search.maven.org/#search|ga|1|g%3A%22com.squareup.wire%22
