### ISSUE TITLE
Generate Service interfaces

### ISSUE THREAD

**Issue by ksperling** [square/wire#527]
Are there any plans to bring back generation of service interfaces in the near future? What was there was removed in 0fd0c07d4efe336de8ea80c5dcb50b1439bb331d with a remark about `wire-schema` "doing the same thing". Is the recommended approach to build my own code generator and maven plugin based on `wire-schema`?

**Comment by swankjesse** [comment]
Yeah, the recommended approach is currently building your own code generator. We could also make an official sample to start with, or something. The `JavaGenerator` class shows that this _should_ be very simple.

**Comment by swankjesse** [comment]
(At Square we have our own internal code generator for this, but it’s for our own internal RPC API. It’d be excellent to generate a GRPC-compatible interface, for example.)

**Comment by vanvlack** [comment]
@swankjesse an example that shows a basic setup for service generation would be super sweet.

**Comment by swankjesse** [comment]
Service generator sample is here:
https://github.com/square/wire/blob/master/wire-codegen-sample/src/main/java/com/squareup/wire/sample/ServiceGenerator.java

**Comment by rvijayraghavan** [comment]
@swankjesse Is there a way to use `wire` to go about generating a service interface from proto that can be used with Retrofit2?

**Comment by swankjesse** [comment]
Nothing at the moment. The challenge is that protos alone have no standard mechanism to bind to HTTP APIs.

**Comment by rvijayraghavan** [comment]
Thanks. 

> (At Square we have our own internal code generator for this, but it’s for our own internal RPC API. It’d be excellent to generate a GRPC-compatible interface, for example.)

Also yes, it would be awesome if `wire` can generate a gRPC-compatible interface. Is there a command-line support or any other way to do that as of today using `wire`? Is the recommended approach still writing our own code generator? Are there any other alternatives or examples?
