### ISSUE TITLE
Where to download Square Wire wire-compiler-VERSION-jar-with-dependencies.jar?

### ISSUE THREAD

**Issue by tim1004457** [square/wire#539]
RT

**Comment by JakeWharton** [comment]
You can download pre-built jars from Maven Central. Here's a list of all versions: http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.squareup.wire%22%20AND%20a%3A%22wire-compiler%22

On the right you'll see there's both a jar (without dependencies) and the jar-with-dependencies.

**Comment by tim1004457** [comment]
thank you~~
