### ISSUE TITLE
proto implementation bridge(s)

### ISSUE THREAD

**Issue by jnorthrup** [square/wire#545]
my project https://github.com/0xCopy/prautobeans was built to extend autobeans to gwt proto definitions and to publish binary packed structs against autobeans java interfaces 

there's a maven plugin module to perform the java interfaces generation  and  a library module to hold the annotations and the bytebuffer transcription and a unit test.  

the prautobeans objects are lazily reified attributes inside of a java proxy based on hashmap.  when a property is mutated the value is stored in the map until serialized again as bytes.

existing protocol buffer solutions for java all use byte[] heap objects, something prautobeans is not bound to. 

if noone is working on one, a translator for all of the post-google protobuffer implementations is a good idea to bridge between formal IDL's and java libraries with optimized write protocols.  At a minimum, it is important for me to follow context switch overheads and avoid pulling DirectByteBuffer object contents into ram as heap objects while making other proto proxies inter-operable.

**Comment by swankjesse** [comment]
Neat! Anything specifically actionable we should be doing here? I’m not sure how to respond to this.

**Comment by jnorthrup** [comment]
i'd like to figure out project impedences 

right now i use a backdated protostuffs parser.   i map interfaces using gwt autobeans http://www.gwtproject.org/doc/latest/DevGuideAutoBeans.html compatible methods (bean-properties) and build the cheapest possible proxy class to perform potentially 0-copy mapped io. 

wire readme says wire  generates attributes, so im assuming these are java classes, ruling out proxies and methods.  i have not examined your choice of parsers yet.  

i have a todo to write a formal proto bridge to prautobeans conversion. 

this is likely to be an xml file bindg multiple proto implemntations to each other over jms-ish.
this may be as simple as  a camel instance wiring together different proto java packages over jms.

**Comment by swankjesse** [comment]
No action for us to take here.
