### ISSUE TITLE
Lint Error: Package not included in Android 

### ISSUE THREAD

**Issue by mjordan-gpfw** [square/wire#563]
I'd like to pull in wire for an Android project.  But with wire-runtime:2.1.1, I get the following Lint error:

okio-1.5.0.jar: Invalid package reference in library; not included in Android: java.nio.file. Referenced from okio.Okio.

Am I using the correct wire runtime for Android? Is there a wire-runtime build that depends on an alternate okio build?

**Comment by JakeWharton** [comment]
You can safely tell lint to ignore the error. It is impossible for the offending method to be called on Android and it isn't used by Wire.
