### ISSUE TITLE
Error in my android app on creation of Dinosaur

### ISSUE THREAD

**Issue by delakanda** [square/wire#568]
I get this error in my android app when it tries to build the Dinosaur object

java.lang.NoClassDefFoundError: com.mypackage.proto.generated.Dinosaur$Builder

any ideas?

**Comment by JakeWharton** [comment]
This is a packaging problem with your app. The required classes are not being included.

**Comment by delakanda** [comment]
Any ideas on a proper packaging Technic? i did add the generated files to my projects package

**Comment by delakanda** [comment]
It worked...thanks...not sure what solved it but i uninstalled the app and reinstalled and it worked

**Comment by JakeWharton** [comment]
Glad to hear it.
