### ISSUE TITLE
Maven plugin compatibility with M2Eclipse

### ISSUE THREAD

**Issue by pushbit** [square/wire#571]
Is the Maven plugin expected to work in Eclipse?  I added the plugin to my pom, as shown in the README, but it doesn't appear to do anything (no sources or classes are generated from the proto files during build).  If I run `mvn compile` manually, the proto classes are generated and compiled to `target/classes`, though for some reason Eclipse isn't able to see/import them.  And after a `clean` in Eclipse I'm back to square one, with no proto classes.  Have I overlooked something or am I just in uncharted waters?

**Comment by JakeWharton** [comment]
We're not Eclipse uses so you probably need to run the plugin manually in
the IDE to see generated sources.

**Comment by pushbit** [comment]
M2Eclipse needs the below to integrate into the build lifecycle.  Most of it can be generated by quick fixing the error on `execution`, but then `action/ignore` needs to be changed to `action/execute` so that the plugin runs and generates the proto classes.  `runOnConfiguration` then allows the compiler to see the generated classes and compile them to `target/classes`.  Perhaps the README could link to this issue with a note for Eclipse users.

```xml
<pluginManagement>
	<plugins>
		<plugin>
			<groupId>org.eclipse.m2e</groupId>
			<artifactId>lifecycle-mapping</artifactId>
			<version>1.0.0</version>
			<configuration>
				<lifecycleMappingMetadata>
					<pluginExecutions>
						<pluginExecution>
							<pluginExecutionFilter>
								<groupId>com.squareup.wire</groupId>
								<artifactId>wire-maven-plugin</artifactId>
								<versionRange>[2.1.2,)</versionRange>
								<goals>
									<goal>generate-sources</goal>
								</goals>
							</pluginExecutionFilter>
							<action>
								<execute>
									<runOnConfiguration>true</runOnConfiguration>
									<runOnIncremental>true</runOnIncremental>
								</execute>
							</action>
						</pluginExecution>
					</pluginExecutions>
				</lifecycleMappingMetadata>
			</configuration>
		</plugin>
	</plugins>
</pluginManagement>
```

**Comment by JakeWharton** [comment]
I think we can embed that in META-INF so it happens automatically.
