### ISSUE TITLE
Make enums proto3 compliant for default value

### ISSUE THREAD

**Issue by mmarvick** [square/wire#575]
This is called out in the proto3 working document (https://github.com/square/wire/issues/279).

From the [proto3 spec](https://developers.google.com/protocol-buffers/docs/proto3#default):

> Note that for scalar message fields, once a message is parsed there's no way of telling whether a field was explicitly set to the default value (for example whether a boolean was set to false) or just not set at all: you should bear this in mind when defining your message types. For example, don't have a boolean that switches on some behaviour when set to false if you don't want that behaviour to also happen by default. Also note that if a scalar message field is set to its default, the value will not be serialized on the wire.

It looks like a few small updates to the compiled files would fix this issue:
- `Builder` methods should initialize any enum fields to their default value
- `ProtoAdapter#encode` methods should not encode anything if an enum field is set to the default value.
- `ProtoAdapter#decode` methods should set enum values on the builder to `null` when catching `EnumConstantNotFoundException` (since these values no longer default to `null`).

This could break backwards compatibility with proto2 users. I'm looking to see if there's any way to specify to the compiler that files should be built for proto3 vs. proto2, but can't find any.

**Comment by swankjesse** [comment]
Yeah, breaking proto2 is a Big Deal for us. I think the proto3 spec is pretty clumsy for default values, especially the part where you can’t differentiate absent from default.

**Comment by mmarvick** [comment]
Agreed, it seems like a big loss of clarity and backwards compatibility for a pretty small amount of data saved. It bit us unfortunately, since Wire is treating any unknown enum states as null (expected) as well as the default state (since no data comes back). That's our fault for using a proto2 library in a proto3 environment. We may just modify the compiler behavior on a local branch to get around that. I'd be happy to put up a PR too, but it seems like that would break things. Maybe in a separate branch, along with a --proto3 flag?

**Comment by JakeWharton** [comment]
We will use the source file's syntax declaration to decide between proto2
behavior and proto3 behavior.

**Comment by mmarvick** [comment]
Ah cool, did not know about that. Thanks!
