### ISSUE TITLE
compiler extend message problem

### ISSUE THREAD

**Issue by kaybinwong** [square/wire#576]
hi there,
     when i try to compiler the extend message (proto like below)  with version 1.8.0,but it occur error.
somebody tell me what i did wrongly, ths?
`
message PBOrder {
    optional int32 orderId = 1;             // 订单id
    optional PBUser user = 2;                // 用户
    optional int32 orderType = 3;           // 订单类型
    optional double amount = 4;             // 涉及金额
    optional int64 createDate = 5;          // 创建时间
    optional int32 orderStatus = 6;         // 订单状态
    optional double balance = 7;            // 余额
    optional string outerId = 8;            // 外部订单id
    extensions 100;
}

message PBTicketOrder {
    optional PBVenue venue = 1;
    optional PBVenueSeat seat = 2;
    optional PBCar car = 3;
    optional PBMatch match = 4;
    extend PBOrder {
        optional PBTicketOrder data_ext = 100;
    }
}`
![qq 20160515120233](https://cloud.githubusercontent.com/assets/5570216/15271961/3ef9cbc8-1a95-11e6-9dc1-4c00b0bd25a0.png)
![qq 20160515120315](https://cloud.githubusercontent.com/assets/5570216/15271960/3ef7f820-1a95-11e6-995c-6da0baac94ef.png)

**Comment by swankjesse** [comment]
We aren't fixing bugs with Wire 1.x anymore. Please upgrade to 2.x.
