### ISSUE TITLE
java_outer_classname for wire compiler

### ISSUE THREAD

**Issue by qning** [square/wire#577]
Does java_outer_classname work for wire compiler. It looks like compiler always generates separate java file for messages defined in the same protoc file.

**Comment by swankjesse** [comment]
Yes, this behavior is not configurable with Wire.

**Comment by kurtisnelson** [comment]
java_multiple_files = true is ideal behavior and outer_classname should be avoided, this allows for easier refactoring of large/nested protos.

**Comment by swankjesse** [comment]
No action to take here.

**Comment by AbeDillon** [comment]
The reasoning behind this decision seems a little heavy-handed. There are many cases where nested classes can make things easier.

1) I don't see how an outer class complicates refactoring in any way. InteliJ's refactoring tools handle moving things into and out of enclosing classes just fine. I don't know of any plug-ins that let me refactor a protobuf and have those changes propogate to my Java code, but that's not a deficiency of my protobuf compiler, nor is it the job of the protobuf compiler to enforce "best practices".

2) Refactoring generated code is already bad practice.

3) Java's lack of namespace support and/or aliasing means you either have to use overly verbose names or simulate proper namespaces with nested classes. That has it's drawbacks, of course, but it can be more helpful than harmful in many situations.

Pleased re-consider this feature. It should be trivial to implement!

**Comment by swankjesse** [comment]
You can work-around by nesting your messages in the `.proto` file.

```
message Outer {
  message Inner {
    ...
  }
}
```

**Comment by AbeDillon** [comment]
That works fine except for RPC Services which are not nest-able (for whatever reason). I can work with that. I just don't agree with the "ideal behavior" reasoning.
