### ISSUE TITLE
Could Wire send the message through TCP?

### ISSUE THREAD

**Issue by 0x464D58** [square/wire#606]
Hello, I think Wire's sample is only local ProtoBuf but I need more about article and sample about "How to send a message through TCP with Wire and how to handle a Receiver?"

I tried it in C#, It work as well with local ProtoBuf but I don't understand about ProtoBuf through TCP anymore.
PS. I'm interesting to send a message from Android to Valve's server.

**Comment by swankjesse** [comment]
Please ask usage questions on StackOverflow. We use this tracker for bug reports and feature requests only.
