### ISSUE TITLE
Support for wildcard *

### ISSUE THREAD

**Issue by fabriciointerama** [square/wire#612]
Instead of typing all .proto file names in the command line add support for wildcard `*`, for example:

```
java -jar %COMPILER% --proto_path=%SOURCE_PATH% --java_out=%OUTPUT_PATH% *.proto
                                                                         ↑
```

**Comment by JakeWharton** [comment]
If you omit *.proto the entire directory will be scanned recursively for
proto files.

**Comment by fabriciointerama** [comment]
Nice! Thank you!

**Comment by swankjesse** [comment]
You can use includes to whitelist the protos you want, or excludes to blacklist the protos you don’t want!
https://github.com/square/wire/pull/613

**Comment by fabriciointerama** [comment]
Nevermind. I found
> Pass `--excludes=google.protobuf.*` to the compiler to omit options from the generated code.

**Comment by swankjesse** [comment]
No further action to take on this.
