### ISSUE TITLE
Add @SuppressWarnings("all") to generated classes

### ISSUE THREAD

**Issue by cypressious** [square/wire#622]
Depending on your inspection settings, the generated code can produce warnings like

> Warning:(1112, 9) Access can be package local
> Warning:(187, 74) Access can be private
> Warning:(1384, 13) 'if' without braces

Adding the annotation to the generated classes would eliminate those.

**Comment by JakeWharton** [comment]
I'm not sure about this. Conversely, depending on your inspection settings,
you can find useful improvements to the generated code. Private member
access across nested class boundaries was recently eliminated from the
generated code because there's a warning for it that can be enabled.

**Comment by swankjesse** [comment]
No action to take on this.
