### ISSUE TITLE
`oneof` generated class does not contain `enum` types

### ISSUE THREAD

**Issue by Tandy1234** [square/wire#632]
Hi, 
I was playing with `oneof` keyword and found out that the generated class seems not following the doc. on https://developers.google.com/protocol-buffers/docs/reference/java-generated#oneof .
For example, if i have the follow in .proto:

```
message Message{
    oneof payload{
        int32 foo_int =4;
        string foo_string =9;
    }
}
```

it generates something like: 

```

  @WireField(
      tag = 4,
      adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  public final Integer foo_int;

  @WireField(
      tag = 9,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String foo_string;
```

but not the enum types as I expected;

And with that, it seems the only way I can know what "type" of my `payload` is checking `foo_int` and `foo_string` to see which one is not null. But what about if I want have adding more types in `oneof` block, is there a quicker way to know the "type" of my `payload`? 

Thanks in advance

**Comment by JakeWharton** [comment]
Wire does not conform to the generated code of Google's protobuf compiler.
There is currently no other way aside from null checking.

**Comment by Tandy1234** [comment]
Thanks for reply. Would this be a good thing to do in the future?

**Comment by swankjesse** [comment]
What would the API look like?

**Comment by Tandy1234** [comment]
My thought is that if we can do something similar to what `golang/protobuf` dose, having an extra getType() method to iterate all fields to return the type, and also having some sort of map so to map the type to the actual field

**Comment by swankjesse** [comment]
Could you provide example code for the `foo_int`, `foo_message` case? In my experience code that intends to make `oneof` easier doesn’t often succeed in Java.

**Comment by Tandy1234** [comment]
```
public enum payloadCase {
      foo_int(4)
      foo_string(9),
    };
```
I am not sure if this is helpful, but this is similar to the doc on https://developers.google.com/protocol-buffers/docs/reference/java-generated#oneof


Actually, I have another thought. Could we just provide a method to return the non-null field? 

providing a wrapper class,
```

    private class payload<T>{
        T field;
        Class<?> type;
        
        public Class<?> getType(){
            
        };
        
        public T getField(){
            return field;
        }
    }
```
and maybe a method like `getPayload()` to return it?

**Comment by swankjesse** [comment]
I’m looking at this API and I don’t see the improvement. Presumably this is where you’re starting from:

```
  if (message.foo_int != null) {
    doIntThings(message.foo_int);
  } else if (message.foo_string != null) {
    doStringthings(message.foo_string);
  } else {
    doNothing();
  }
```

The proposed API gets you here:

```
  Payload<?> payload = message.payload;
  if (payload.type == Integer.class) {
    doIntThings((Integer) payload.field);
  } else if (payload.type == String.class) {
    doStringthings((String) payload.field.);
  } else {
    doNothing();
  }
```

I think the closest we get with oneof that’s an improvement is a visitor, and it’s not really much better.

**Comment by kurtisnelson** [comment]
Hazzers could be generated for a one-of to solve this issue, but at a method + bytecode cost.

**Comment by swankjesse** [comment]
Unclear what action to take here.

**Comment by alecmuffett** [comment]
Hello All - I just found this, am wondering if there has been any change, since?
