### ISSUE TITLE
How to read length-delimited messages?

### ISSUE THREAD

**Issue by mxk** [square/wire#633]
This may be a dumb question, but I can't figure out the answer by looking at the runtime or generated source code. I have a Bluetooth connection on Android over which I'm sending length-delimited messages (`parseDelimitedFrom()` and `writeDelimitedTo()` in Google's protobuf API). With Wire, writing looks like this:

``` java
writer.writeVarint32(Msg.ADAPTER.encodedSize(msg));
Msg.ADAPTER.encode(writer, msg);
sink.flush();
```

How do I read the response? If I call `Msg.ADAPTER.decode(reader)`, it immediately tries to read the next tag without figuring out how long the message is, and ProtoReader doesn't expose any way for me to limit the message length manually (and it's all `final`, so I can't add this functionality myself).

I don't want to read the whole message into a byte[] and decode from there because my messages may be 4-8 KB in size and it is more efficient to decode them as the data is being received instead of waiting until the entire message is buffered in memory.

It looks like my best option right now is to implement a wrapper around BufferedSource, read the delimiter manually, and have exhausted() return true when the limit is reached. That's a lot of work for basic protobuf functionality. Am I missing some existing way of doing this?

**Comment by JakeWharton** [comment]
Have a look at https://github.com/square/wire/compare/jw/delimited which shows how you can interact with length-delimited protos.

**Comment by JakeWharton** [comment]
I would like to make this easier though.

**Comment by mxk** [comment]
Thanks, I got it to work with some tweaks. Don't really like the fact that this solution puts two buffers between the InputStream and ProtoReader, and also that you need two new ProtoReaders for every message (I modified the code so that at least the BufferedSources are reused). Seems like ProtoReader already has everything that's needed to decode multiple length-delimited messages, but that functionality just needs to be exposed.

**Comment by JakeWharton** [comment]
Yeah I'm already working on it.

**Comment by swankjesse** [comment]
No further action to take on this.

**Comment by JakeWharton** [comment]
See https://github.com/square/wire/discussions/2745#discussioncomment-7826737

We need to add an API to `ProtoReader` to make this not awful, but we should perhaps consider doing something more than the bare minimum while we're here.
