### ISSUE TITLE
SchemaException when generating maps

### ISSUE THREAD

**Issue by jrobinson3k1** [square/wire#635]
Currently getting this error:

```
Error:Execution failed for task ':app:generateDebugWireProtos'.
> SchemaException generating Wire Java source for src/main/proto: unable to resolve map<string, string>
  for field attributes (C:\workspace\hacc\app\src\main\proto\jasonrobinson/hacc/homeassistant.proto at 11:5)
  in message jasonrobinson.hacc.generated.homeassistant.State (C:\workspace\hacc\app\src\main\proto\jasonrobinson/hacc/homeassistant.proto at 6:1)
```

with this proto file:

```
syntax = "proto3";

package jasonrobinson.hacc.generated.homeassistant;
option java_package = "com.jasonrobinson.hacc.generated.homeassistant";

message State {
    string entity_id = 1;
    string last_changed = 2;
    string last_updated = 3;
    string state = 4;
    map<string, string> attributes = 5;
}
```

I'm using the 2.2.0 runtime. Removing the map generates the pojo as expected.

**Comment by jrobinson3k1** [comment]
Actually I think I might have mistaken blame. The issue is probably with the wire gradle plugin since it's generating the java, not the runtime.

**Comment by swankjesse** [comment]
FYI Wire does not yet support proto3. We should probably fix it to make this more explicit!

**Comment by JakeWharton** [comment]
What version of Wire are you using? That error is indicative of an old version.

**Comment by jrobinson3k1** [comment]
2.2.0, but I was using the gradle plugin, not the jar, to generate the pojos.

**Comment by swankjesse** [comment]
We’ll support Maps in 2.3.0, coming soon.
