### ISSUE TITLE
"no main manifest attribute, in wire-compiler"

### ISSUE THREAD

**Issue by rostopira** [square/wire#638]
I'm trying to generate java classes using jar downloaded from Maven
Tried with version 2.2.0 and 2.1.2
In terminal I see following error `no main manifest attribute, in wire-compiler-2.1.2.jar`

**Comment by swankjesse** [comment]
Try the `-with-dependencies` jar instead.
http://repo1.maven.org/maven2/com/squareup/wire/wire-compiler/2.2.0/wire-compiler-2.2.0-jar-with-dependencies.jar

**Comment by rostopira** [comment]
```
$ java -jar -with-dependencies wire-compiler-2.2.0.jar --proto-path=kid-in-the-city/mobile/src/main/proto/ --java-out=./
Unrecognized option: -with-dependencies
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

**Comment by swankjesse** [comment]
```
java -jar wire-compiler-2.2.0-jar-with-dependencies.jar ...
```

**Comment by swankjesse** [comment]
(the link to download that file is above)
