### ISSUE TITLE
Ability to suppress line/column comments

### ISSUE THREAD

**Issue by pforhan** [square/wire#643]
If a project checks in the generated wire sources (why? long story) the source line numbers can frequently be the only changes in a file.  This can happen if a proto is under heavy development.

It'd be great if we could just suppress generation of these altogether.  In the meantime we use:

```bash
if [[ `uname` == 'Darwin' ]]; then
    find src -name '*.java' | xargs sed -i '' -E "s/proto at [0-9]+:[0-9]+/proto/g"
else
    find src -name '*.java' | xargs sed -i -E "s/proto at [0-9]+:[0-9]+/proto/g"
fi
```

**Comment by JakeWharton** [comment]
#641
