### ISSUE TITLE
How to compile with creation class than named as .proto FileName?

### ISSUE THREAD

**Issue by bagrusss** [square/wire#654]
How to compile with creation classes than named as .proto FileName and contains inner proto message classes?

For example, I have file LoginService.proto file with messages description: 

```
message LoginClient {
    message Request {
        optional string path = 1 [default = "/path_req"];
        optional string method = 2 [default = "post"];
        optional string param1 = 3;
        optional string param2 = 4;
    }
    message Response {
        required string someParam1 = 1;
        required string someParam2 = 2;
    }
}
```

And I need that generator create this class:

```
public final class LoginService {
    public static final class LoginClient extends Message<LoginClient, LoginClient.Builder> {
       ...
          public static final class Request extends ... {
                ...
          }

          public static final class Response extends ... {
               ...
          }
       ...
    }
}
```

**Comment by JakeWharton** [comment]
We don't support this. Why do you need the extraneous enclosing class?

**Comment by bagrusss** [comment]
Because this library uses different way of class generation. I migrate from google protobuf and proto models classes in our project are grouped by logical parts as in the example above. 
Such code is easier to maintain in large projects for my opinion.

**Comment by JakeWharton** [comment]
We don't really have plans to support this. The intention of the library
isn't parity with Google's decisions. Top-level classes for grouping
logical parts are not idiomatic in Java which is the only language this
project supports. Packages are the grouping mechanism of choice. You should
be able to specify the java_package option to include the name of the file
which will result in the same logical grouping but in a much more idiomatic
way for the language.

**Comment by swankjesse** [comment]
No action to take on this.
