### ISSUE TITLE
any way to remove the final keyword in generated java class

### ISSUE THREAD

**Issue by gydhy8** [square/wire#666]
I want to  remove the final keyword before the member variable in generated java class,  I need change the value under a scene

**Comment by swankjesse** [comment]
Use `newBuilder()` to create a new instance.

**Comment by gydhy8** [comment]
sorry,  I didn't understand what do you mean. this is my message definition as follow:

message GiftListInfo {
    required uint32 id= 1;
    required string nickname= 2;
    required string picture= 3;
    required uint32 gift_type= 4;
}

This is one of the corresponding generated member variables in the class by your jar utils or maven utils:

@WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#UINT32",
      label = WireField.Label.REQUIRED
  )
  public final Integer id;

The **id** field is final type, I can't modify its value, use newBuilder() can't solve my problem too. The **final** keyword was auto added in when this class file was auto generated by your maven or jar utils. How to prevent it ???
