### ISSUE TITLE
any way to remove the final keyword in generated java class

### ISSUE THREAD

**Issue by gydhy8** [square/wire#667]
I want to remove the final keyword before the member variable in generated java class, I need change the value under a scene.

This is my message definition as follow:

message GiftListInfo {
required uint32 id= 1;
required string nickname= 2;
required string picture= 3;
required uint32 gift_type= 4;
}

This is one of the corresponding generated member variables in the class by your jar utils or maven utils:

@wirefield(
tag = 1,
adapter = "com.squareup.wire.ProtoAdapter#UINT32",
label = WireField.Label.REQUIRED
)
public final Integer id;

The id field is final type, I can't modify its value, use newBuilder() can't solve my problem too. The final keyword was auto added in when this class file was auto generated by your maven or jar utils. How to prevent it ???

**Comment by JakeWharton** [comment]
Wire generates immutable classes. This is simpler and safer than mutable ones. Only the builders can change values and they will always return a new instance. This is by design and we do not allow it to be controlled.

**Comment by gydhy8** [comment]
thanks for your detailed answer, thank you very much!
