### ISSUE TITLE
may the ProtoAdapter add a decode(byte[], offset, length)?

### ISSUE THREAD

**Issue by suarezu** [square/wire#674]
![image](https://user-images.githubusercontent.com/11764393/29352514-8ba5a4e8-8299-11e7-859c-321acf725fd3.png)

So that whenever a Message class is instantiated, there is no need to alloc a global new byte[]; a large enough byte[] can be reused in a loop.

**Comment by swankjesse** [comment]
For this I recommend using `BufferedSource`, which can be dynamically sized and streamed.
