### ISSUE TITLE
Proto3 compatible JSON serialization

### ISSUE THREAD

**Issue by rage-shadowman** [square/wire#684]
The current `WireTypeAdapterFactory` implementation generates incompatible JSON text since it doesn't mangle property names like proto3 does (where "foo_bar" becomes "fooBar" and "_id" becomes "Id").

It would be nice to have an alternative adapter factory that does mangle the property names in a proto3 compatible way (replacing `"_" + character` with `toUpper(character)`).

**Comment by swankjesse** [comment]
Proto3 has a bunch of questionable design decisions, and this is one of ’em. To make this work we’ll need to integrate with a JSON library like Moshi and do the name mangling there. Ugh.

**Comment by rage-shadowman** [comment]
I agree that this was a poor decision. However, that **is** what they decided. So without mangling the property names, wire is not compatible with protobuf3 JSON format.

Is compatibility something that is on the radar?

Would it be much more difficult than mangling the `FieldBinding` names in your `MessageTypeAdapter` class?

**Comment by swankjesse** [comment]
We should do name mangling in the adapter.

**Comment by rage-shadowman** [comment]
I wouldn't suggest mangling the name in the adapter in a backward-incompatible fashion. This was more of a hypothetical "would it work if...". If so, then we could create another adapter that is proto3 compatible.

**Comment by swankjesse** [comment]
Tracking as https://github.com/square/wire/issues/1387
