### ISSUE TITLE
Constructor with more than 255 arguments generated

### ISSUE THREAD

**Issue by hbursk** [square/wire#691]
When using a proto file that has more than 255 sub-message types, a constructor is generated that has more than 255 arguments which is a limit in the JVM. This prevents compiling. Is there a way to disable the constructor generation when using 2.2.0 wire compiler from the command line? I've tried the --compact and --android flags hoping they would address that, but no such luck.

**Comment by rage-shadowman** [comment]
Or maybe an option for Builder based constructors only?

```java
MyClassConstructor (Builder builder) {
   this.param1 = builder.param1;
   this.param2 = builder.param2;
   // and on and on...
   this.paramN = builder.paramN;
}
```

BTW - Having 255 fields sounds like a maintenance nightmare, even if you only have to maintain the proto file. What are you doing that makes it so high?

**Comment by hbursk** [comment]
I'm testing out a change I made on a local checkout where I don't fill out the parameters if the fields size is too high. That way, you always get something that can compile without having to use a flag that affects all the other files being generated. If that works out, I'll make a PR for it. 

For convience, all the message types were wrapped into one message type so that it's easy to create a message by creating this one mothership object type, and accessing its members. In retrospect, more domain spacing for different types of messages would have been better.

**Comment by hbursk** [comment]
Using my approach, I had to remove final from the members. So that probably wouldn't pass a PR. If I have time, I'l try the Builder passed into the constructor approach.
