### ISSUE TITLE
Nullable annotations for Android without Parcelable

### ISSUE THREAD

**Issue by LukeStClair** [square/wire#693]
Currently, Wire supports Nullable via the "--android" flag, which also bundles in Parcelable. Parcelable introduces some unfortunate dependencies, however, whereas Nullable tends to be usable by a lot of tools (https://github.com/uber/NullAway, for instance) with minimal added overhead/dependencies (just the Android support annotations).

https://github.com/square/wire/issues/225 runs down some of the different options around Nullability annotations - before opening a PR, I wanted to see if people had thought about supporting a flag to only include android support annotations, but not the rest of Android (right now, this just looks like Parcelable and Nullable to me, after scanning for emitAndroid, though I could've missed something. 

Would personally prefer to specify --android-annotations to indicate that we'd add android-specific annotations vs full Android support.

Happy to submit this PR here - it felt to me like the jsr305 route wasn't as worth the added annoyance for consumers, and that scoping to Android for now was extremely low cost (supporting another flag).

**Comment by JakeWharton** [comment]
The only reason we never added these was the lack of a good choice. I am
strongly against adding JSR 305 to anything new. We should be tearing it
out of places and not adding it. There's efforts for a new set, but until
then maybe we do JetBrains annotations? The other problem is that it forces
a dependency where there might not be one. With Android we are basically
guaranteed the annotations will be present.

**Comment by LukeStClair** [comment]
Yeah, I was thinking the same thing around JSR 305 - it seems to me like the path of least resistance here is to just add a flag to generate the Android annotation w/out the Parcelable support. Downside is that it's another build flag, but that's about it - seems like compelling functionality to me, so I'll probably just put up a PR and see what folks think if there's no conceptual reason not to.
