### ISSUE TITLE
error in Windows when import google/protobuf/proto

### ISSUE THREAD

**Issue by bianbian-org** [square/wire#695]
I import some google proto in my protos, but its compile failed under Windows.
Maybe the problem of "/" and "\\" ?

google/protobuf/descriptor.proto needs to import google\protobuf\descriptor.proto
 for field file (google/protobuf/descriptor.proto at 57:3)
 in message google.protobuf.FileDescriptorSet (google/protobuf/descriptor.proto at 56:1)
 google/protobuf/descriptor.proto needs to import google\protobuf\descriptor.proto
 for field message_type (google/protobuf/descriptor.proto at 74:3)
....
google\protobuf\type.proto needs to import google/protobuf/type.proto
  for field syntax (H:\IdeaProjects\src\main\proto\google\protobuf\type.proto at 153:3)
  in message google.protobuf.Enum (H:\IdeaProjects\src\main\proto\google\protobuf\type.proto at 143:1)
google\protobuf\type.proto needs to import google/protobuf/type.proto
  for field options (H:\IdeaProjects\src\main\proto\google\protobuf\type.proto at 163:3)
  in message google.protobuf.EnumValue (H:\IdeaProjects\src\main\proto\google\protobuf\type.proto at 157:1)
        at com.squareup.wire.schema.Linker.link(Linker.java:119)
        at com.squareup.wire.schema.SchemaLoader.loadFromDirectories(SchemaLoader.java:167)
        at com.squareup.wire.schema.SchemaLoader.load(SchemaLoader.java:106)

**Comment by OrezzerO** [comment]
same problem. I modify the loadFromDirectories method in SchenaLoader.java ,and released a SNAPSHOT version
```
private Schema loadFromDirectories(Map<Path, Path> directories) throws IOException {
    final Deque<String> protos = new ArrayDeque<>(this.protos);
    if (protos.isEmpty()) {
      for (final Map.Entry<Path, Path> entry : directories.entrySet()) {
        Files.walkFileTree(entry.getValue(), new SimpleFileVisitor<Path>() {
          @Override public FileVisitResult visitFile(Path file, BasicFileAttributes attrs)
              throws IOException {
            if (file.getFileName().toString().endsWith(".proto")) {
              protos.add(entry.getValue().relativize(file).toString());
            }
            return FileVisitResult.CONTINUE;
          }
        });
      }
    }

    Map<String, ProtoFile> loaded = new LinkedHashMap<>();
    loaded.put(DESCRIPTOR_PROTO, loadDescriptorProto());

    boolean convertSeparator = false;
    if (java.io.File.separator.equals("\\")) {
      convertSeparator = true;
    }
    while (!protos.isEmpty()) {
      String proto = protos.removeFirst();

      if (convertSeparator) {
        proto = proto.replaceAll("\\\\", "/");
      }
      if (loaded.containsKey(proto)) {
        continue;
      }

      ProtoFileElement element = null;
      for (Map.Entry<Path, Path> entry : directories.entrySet()) {
        Source source = source(entry.getValue(), proto);
        if (source == null) {
          continue;
        }

        Path base = entry.getKey();
        try {
          Location location = Location.get(base.toString(), proto);
          String data = Okio.buffer(source).readUtf8();
          element = ProtoParser.parse(location, data);
          break;
        } catch (IOException e) {
          throw new IOException("Failed to load " + proto + " from " + base, e);
        } finally {
          source.close();
        }
      }
      if (element == null) {
        throw new FileNotFoundException("Failed to locate " + proto + " in " + sources);
      }

      ProtoFile protoFile = ProtoFile.get(element);
      loaded.put(proto, protoFile);

      // Queue dependencies to be loaded.
      for (String importPath : element.imports()) {
        protos.addLast(importPath);
      }
    }

    return new Linker(loaded.values()).link();
  }
```
