### ISSUE TITLE
Kotlin- and Java-generated protos are incompatible

### ISSUE THREAD

**Issue by Egorand** [square/wire#707]
This presents an issue for gradual migration to Kotlin. For example, Java protos have `public static final ADAPTER` fields and access it as `Foo.ADAPTER`. In Kotlin, this has been changed to a nested `object ADAPTER`, which is great for Kotlin callers, but Java callers would need to use `Foo.ADAPTER.INSTANCE`. We need to make sure this kind of compatibility is taken into account. Also, ideally we'd like this to be an opt-in feature behind a compiler flag, so that we don't generate unnecessary code for 100% Kotlin projects.

**Comment by Egorand** [comment]
`WireConverterFactory` also relies on `ADAPTER` being a `public static` field.

**Comment by swankjesse** [comment]
I’d like for the compiled code to make `ADAPTER` look like a public static final field. Maybe we could do a `@JvmStatic` thing on a member of the companion?

**Comment by Egorand** [comment]
@swankjesse #714
