### ISSUE TITLE
Kotlin generator todos

### ISSUE THREAD

**Issue by mc-lovin** [square/wire#728]
- [ ]   Options support
- [x]   Add oneof support
- [x]   Add Map support
- [ ]   Add Custom Adapter support
- [x]  replace find with an O(1) operation
- [x] use kotlinpoet for generating lambdas
- [ ] Generate default fields

**Comment by Egorand** [comment]
@mc-lovin I can start working on Map support if you don't mind

**Comment by Egorand** [comment]
@mc-lovin what is "use kotlinpoet for generating lambdas" about?

**Comment by mc-lovin** [comment]
@Egorand sorry missed this comment, This was about generating this block 

```
        val unknownFields = reader.forEachTag { tag ->
                        when (tag) {
                            1 -> number = ProtoAdapter.STRING.decode(reader)
                            2 -> type = PhoneType.ADAPTER.decode(reader)
                            else -> TagHandler.UNKNOWN_TAG
                        }
                    }
```
using updated kotlin poet functions instead of using the generic `addStatment` for generating the lambda

**Comment by Egorand** [comment]
Got it, I can work on this. I'm pretty sure though we're already using the latest APIs, but can make sure.

**Comment by Egorand** [comment]
Yeah, we're good, as we didn't introduce any new APIs in KotlinPoet to support this - it was an implementation change that's present in 1.0.0.

**Comment by Egorand** [comment]
I'm gonna close this issue and open separate issues for each TODO
