### ISSUE TITLE
Opt-in to strict go-style package dependency cycle checks

### ISSUE THREAD

**Issue by swankjesse** [square/wire#732]
If you write `.proto` files and generate golang code from them, the golang compiler will fail if there are cycles between packages in the generated Go code.

This is super awful and Go is a bad language!

But we should probably check for this in Wire to prevent good developers from accidentally writing protos that the bad Go language can’t handle.

**Comment by swankjesse** [comment]
This is implemented now and is not optional!

**Comment by oldergod** [comment]
There's now an option to opt-out.
