### ISSUE TITLE
Decouple Parsing and Processing from Language Emitting

### ISSUE THREAD

**Issue by JakeWharton** [square/wire#75]
This would help make the library extension friendly. You could easily write an "ObjectiveWire" variant (in Java, mind you) that depended on this library's parsing and processing but chose to emit Objective-C code. There's no reason everyone should have to figure out parsing and dependency analysis just to emit different languages.

 * [x] Parsing
 * [x] Pruning
 * [ ] Emitting
 * [ ] Command-line interface

**Comment by wdroste** [comment]
+1

**Comment by JakeWharton** [comment]
This happened on `master` over the last two weeks. It's not exposed for "plugins" yet, but that's on the roadmap.
