### ISSUE TITLE
Kotlin generator: oneof with kotlin keyword name creates broken code

### ISSUE THREAD

**Issue by andrew-arnott** [square/wire#801]
The following proto generates broken Kotlin code:

```
message TestMessage {
  optional string type = 1;
  oneof class {
    string id = 2;
    int64 version = 3;
  }
  oneof object {
    string data = 4;
    string config = 5;
  }
  oneof interface {
    string more = 6;
  }
}
```

The sealed classes that are generated are named so that they don't conflict with keywords by adding an underscore at the end, but they are not referenced with the underscore elsewhere:

```
    sealed class Class_ {
        data class Id(val id: String) : TestMessage.Class()

        data class Version(val version: Long) : TestMessage.Class()
    }

    sealed class Object_ {
        data class Data(val data: String) : TestMessage.Object()

        data class Config(val config: String) : TestMessage.Object()
    }

    sealed class Interface_ {
        data class More(val more: String) : TestMessage.Interface()
    }
```

**Comment by andrew-arnott** [comment]
I took a look at this one today. It's more involved. Basically, Kotlin Poet has a `NameAllocator` class that the `KotlinGenerator` here is using, but the name allocator is not supported by the various builder classes. So, what happens is the superclass reference is just a `TypeName` without any knowledge that the `NameAllocator` actually renamed it to have an underscore at the end.

**Comment by Egorand** [comment]
FYI we've reverted back to how Wire 2 was modelling `oneof`s, so this issue is not relevant anymore. I'm gonna close the ticket.
