### ISSUE TITLE
Kotlin generator: enum from another message creates broken code

### ISSUE THREAD

**Issue by andrew-arnott** [square/wire#802]
The following example should reproduce the issue:

```
message TestOne {
  optional string id = 1;
  enum TestEnum {
    ENTRY = 1;
    ANOTHER = 2;
  }
}

message TestTwo {
  optional TestOne.TestEnum e = 2;
}
```

The enum is not fully qualified in the generated TestTwo class.

**Comment by andrew-arnott** [comment]
I put up a PR to fix this. See https://github.com/square/wire/pull/804

**Comment by Egorand** [comment]
Does it have to be fully qualified though? Would it be sufficient to just import the enum?

**Comment by andrew-arnott** [comment]
There's a specific case in our codebase that would not work with just importing. We have multiple enums with the name `Status` that are used by other protos. So we need `Foo.Status` and `Bar.Status` to differentiate.
