### ISSUE TITLE
gRPC support working document

### ISSUE THREAD

**Issue by oldergod** [square/wire#821]
Work left to support gRPC:

- [x] Remove `CoroutineContext`s out of our APIs in [GrpcMethod](https://github.com/square/wire/blob/master/wire-grpc-tests/src/main/java/com/squareup/wire/GrpcMethod.kt).
- [x] Generate service interfaces (see [RouteGuide](https://github.com/square/wire/blob/master/wire-grpc-tests/src/test/java/routeguide/RouteGuide.kt)).
- [x] Rewrite OkHttp's [StreamAllocation](https://github.com/square/okhttp/blob/master/okhttp/src/main/java/okhttp3/internal/connection/StreamAllocation.java) to a state machine.
  - [x] Maybe replace [EventListener](https://github.com/square/okhttp/blob/master/okhttp/src/main/java/okhttp3/EventListener.java) too.
- [x] Check if proto2 supports gRPC as well: yes!
- [x] Write many tests, mostly around error cases.
- [ ] Have Tracon to support duplex.
- [ ] [Server Support](https://github.com/square/wire/issues/957)

**Comment by ZacSweers** [comment]
Are there any plans to support bi-directional streaming?

**Comment by swankjesse** [comment]
Plans?! It's already done!

**Comment by ZacSweers** [comment]
This is the last time I ask a question for a coworker without checking if it's already  done 😅
