### ISSUE TITLE
Scoping of enum values do not follow C++ naming conventions

### ISSUE THREAD

**Issue by mpdifran** [square/wire#839]
It seems like wire allows enum values to be named as children, instead using the C++ naming convention (enum values are siblings to their type). The lack of this restriction allows certain `.proto` files to compile fine using wire, but not with other compilers, such as `protoc`.

For example, you can generate Java classes for the following protobuf file using wire, but not using `protoc`:

```
syntax = "proto3";

message Test {
    enum Enum1 {
        FIRST = 0;
        SECOND = 1;
    }
    enum Enum2 {
        FIRST = 0;
        SECOND = 1;
    }
}
```

More information can be found here: https://github.com/apple/swift-protobuf/issues/838

**Comment by JakeWharton** [comment]
Hmm somewhere there is a test for this. I distinctly remember writing it.

**Comment by JakeWharton** [comment]
Found it!

https://github.com/square/wire/blob/4e2e7ceb18c4d974d99fabc10908dc1c4f4bd54e/wire-compiler/src/test/java/com/squareup/wire/WireCompilerErrorTest.kt#L96-L120

**Comment by JakeWharton** [comment]
The test is in a weird place, but the validation lives in the schema:

https://github.com/square/wire/blob/master/wire-schema/src/main/java/com/squareup/wire/schema/Linker.java#L308-L332

**Comment by mpdifran** [comment]
Ah ok, good to see this case is covered. I'm chatting with my team now to determine why we're not seeing any errors.

**Comment by mpdifran** [comment]
Looks like all the enums I'm seeing an error for are at the root level. Do you have any tests covering that case (instead of enums embedded in a message)? i.e.

```
Instead of:

message Foo {
  enum Bar {
    QUIX = 0;
    FOO = 1;
  }

  enum Bar2 {
    BAZ = 0;
    QUIX = 1;
  }
}

Something like:

enum Bar {
  QUIX = 0;
  FOO = 1;
}

enum Bar2 {
  BAZ = 0;
  QUIX = 1;
}
```

**Comment by JakeWharton** [comment]
We do not. Sent #846.
