### ISSUE TITLE
Standardize generated field names based on convention

### ISSUE THREAD

**Issue by creativepsyco** [square/wire#87]
// Copied from JavaWriter
Currently, the field names are directly derived from the `.proto` files. However, it would be better if while generating the code some conventions can be followed like:

* Hungarian notation for fields
* Convert underscore in proto field names to camel case

Right now, a field declared as `request_id` remains as `request_id` in Java Code and sometimes feels weird to be calling a function like `request_id(21)`

will follow up with a pull request.

**Comment by EddieRingle** [comment]
@swankjesse @JakeWharton Would this possibly be an issue better suited for JavaPoet?

**Comment by swankjesse** [comment]
This is deliberate. Our goal: don’t break grep.

**Comment by udalov** [comment]
@swankjesse What would be wrong with this feature being implemented behind a command line option? Readable code is much more important to me (and I imagine other people) than the ability to use grep, especially since the latter is often better solved by an IDE.

**Comment by swankjesse** [comment]
It’s not grep specifically, but the whole universe of tools that keep working if you avoid such transformations.

**Comment by udalov** [comment]
I can understand that (although never had to use any of such tools) but it doesn't answer my question: is there anything wrong with the implementation of the new name generation hidden behind a switch?

**Comment by swankjesse** [comment]
Adding such a feature is an implicit endorsement that it’s a good idea. I don’t!

Even in IntelliJ, I really like being able to go from a proto message field like `payment_expires_at` to the corresponding Java field also named `payment_expires_at` by `Command+F`. With any kind of mapping I need to do the work to search for `paymentExpiresAt` before I can go from `.proto` to `.java`.
