### ISSUE TITLE
Inconsistent bytes length between wire-compiler and protoc

### ISSUE THREAD

**Issue by TedaLIEz** [square/wire#879]
I have had one proto3 file like:
```protocol buffer
message Rsp {
        map<string,int32> nums = 1;			
	int64 count = 2;			
	int64 time = 3;			
};
```

I tried to use two different tools: `protoc` and `wire-compiler` to generate the corresponding java class and compare the byte[] taken from their API.

```java
Map<String, Integer> nums = new HashMap<String, Integer>();
Rsp mockRsp = Rsp.newBuilder()
      .setTime(1000L)
      .putAllNums(nums)
      .setCount(0L)
      .build();    // from protoc
byte[] mockBytes = mockRsp.toByteArray();
Rsp wireMockRsp = new Rsp.Builder()
    .time(1000L)
    .nums(nums)
    .count(0L)
    .build();   // from wire-compiler
byte[] wireMockBytes = wireMockRsp.encode();
```
Then I print out the `mockBytes` and `wireMockBytes`
mockBytes:
0x18 0xE8 0x07
wireMockBytes:
0x10 0x00 0x18 0xE8 0x07

It seems like wire-compiler will have two more bytes than what I got in protoc's generated Java class. I think one of them will be broken If my server gives me the bytes from his code(e.g pass a protocol buffer from golang)

I have no idea what happened here, does `proto3` not fully supported in wire?

P.S:
protoc version: 3.7.0
wire-runtime: 2.3.0
wire-compiler: 2.3.0

tested in MacOS

**Comment by swankjesse** [comment]
Proto 3 will omit 0s. Wire will include em.

**Comment by TedaLIEz** [comment]
> Proto 3 will omit 0s. Wire will include em.

Because proto 3 omitting 0s, parsing proto3's bytes with wire will give me null values when it comes across 0s. I could perform null-check with all the fields in my proto to avoid NullPointerException. Is it designed on purpose? I am not sure this issue should be a feature for supporting proto3 standard.

**Comment by swankjesse** [comment]
We should explicitly not support proto3?

**Comment by TedaLIEz** [comment]
It seems that wire had plans for supporting proto3 #279 . My issue is only about those null-checks, not on your decisions. I think null-checks here is a workaround with this issue. Btw, sorry for my poor English.

**Comment by oldergod** [comment]
Closed. We'll follow-up in #1386.
