### ISSUE TITLE
Android Support for Gradle Plugin

### ISSUE THREAD

**Issue by mannodermaus** [square/wire#881]
Thank you for providing a Gradle plugin with Wire 3.0. What are the current plans and potential roadmap to support Android projects in `wire-gradle-plugin`? Currently, support is limited to pure-Java and Kotlin projects. Introducing Android support will require flavor-specific proto generation as well. Happy to contribute here, just testing the waters beforehand.

Thanks in advance!

**Comment by jrodbx** [comment]
We're working on that in the coming weeks!

**Comment by sagarsuri29** [comment]
Eagerly waiting for this feature 😃

**Comment by bgkprashant** [comment]
Hi, I'm getting below error when i generate java source for Android studio.
-----------------------------------------------------------------------------
Task with name 'compileJava' not found in project ':app'

How to rectify this error?

**Comment by matejdro** [comment]
Is this ticket obsolete? We are using wire in Android library modules without issues.

**Comment by mannodermaus** [comment]
Scanning the source of the most recent Gradle plugin, it seems like it is, yeah. Not sure when support for Android was added, but let me close this request.
