### ISSUE TITLE
D8: Program type already present: com.squareup.wire.package-info

### ISSUE THREAD

**Issue by Egorand** [square/wire#882]
Similar to https://github.com/square/okhttp/issues/4395. `wire-runtime`, `wire-moshi-adapter` and `wire-gson-support` all include a `package-info.java` file under the `com.squareup.wire` package, and these files clash when being packaged into a single APK.

It should be easy to fix following the OkHttp PR: https://github.com/square/okhttp/pull/4438

**Comment by jrodbx** [comment]
Should we instead file an issue on Google's tracker?  D8 is part of the Android toolchain and it looks like they've fixed bugs in the recent past of a similar nature:

https://issuetracker.google.com/issues/118569372
https://issuetracker.google.com/issues/122715929
https://issuetracker.google.com/issues/120102996

**Comment by Egorand** [comment]
I don't think it's Google's fault in our case, we're just packaging two classes with the same name. This might be solvable by Gradle configuration, in which case it might be something to mention in README.

**Comment by JakeWharton** [comment]
Convert those artifacts to Kotlin and the problem goes away!

**Comment by oldergod** [comment]
:thinkaboutit:

**Comment by Egorand** [comment]
Artifacts converted to Kotlin!
