### ISSUE TITLE
Different proto files loaded between SchemaLoader and NewSchemaLoader

### ISSUE THREAD

**Issue by ryanhall07** [square/wire#898]
This might not be a bug and just user error :) To start I just wanted to document my findings, in case others run into similar issues.

When using the `WireCompiler`, which uses the `SchemaLoader`, only the explicit proto files I have listed in the arguments are loaded. For example:

```
java WireCompiler --proto-path=large-jar-with-protos.jar my_proto1.proto my_proto2.proto
```

Even though `large-jar-with-protos.jar` has 1000s of proto files bundled in it, only `my_proto1.proto` and `my_proto2.proto` (and their dependencies) are loaded.

However, it appears when using `WireRun`, which uses the `NewSchemaLoader`, it loads the 1000s of proto files in `large-jar-with-protos.jar`. We are using the new wire gradle plugin, which uses `WireRun`.

```
wire {
  sourcePath large-jar-with-protos.jar
}
```

This is causing issues for my org, since the large proto file has colliding `FieldOptions`, which now result in fully qualified name methods like `fully_qualified_required(...)` instead of `required()`. This is now not backwards compatible with previously generated Wire code.

**Comment by swankjesse** [comment]
Yikes. I suspect our configuration is wrong; the difference between the old and new schema loaders is significant.

**Comment by swankjesse** [comment]
Fix should be straightforward, you can explicitly pick which protos to load from the jar.

**Comment by swankjesse** [comment]
Our `sourcePath {}` API assumes it’s including inputs from a directory but we need to also support including inputs from .jar files as well.

I think we need to change this method:
```
  fun sourcePath(closure: Closure<SourceDirectorySet>)
```

To instead take something like

```
  fun sourcePath(closure: Closure<ProtoRootSet>)
```

That `ProtoRootSet` method could delegate to `SourceDirectorySet`, or not. We just need to accept relative paths within directories or .jar files; WireRun does all the file reading anyway.
