### ISSUE TITLE
Wire doesn't accept multiple extension ranges declared in one `extensions` statement

### ISSUE THREAD

**Issue by CurtisFenner** [square/wire#927]
The Protobuf spec allows multiple extension ranges to specified in a single `extensions` statement: [The spec specifies the following grammar:](https://developers.google.com/protocol-buffers/docs/reference/proto2-spec#extensions)

```
extensions = "extensions" ranges ";"
ranges = range { "," range }
range =  intLit [ "to" ( intLit | "max" ) ]
```

Here's an example protobuf message using this grammar:
```
message Msg {
    extensions 1, 3 to 5;
}
```

Google's protoc compiler accepts the above.
However, Wire only allows a single range; attempting to compile the above yields a syntax error. This discrepancy means a risk when using both Wire and Google's protoc in the same code base, or when trying to move from one to the other.

I'm not familiar with the Wire codebase, but it looks like the parsing code in [ProtoParser.readExtensions](https://github.com/square/wire/blob/master/wire-schema/src/main/java/com/squareup/wire/schema/internal/parser/ProtoParser.java#L471) is what doesn't allow multiple ranges. I'm not sure what other pieces of code may need to change to accommodate multiple ranges.

**Comment by JakeWharton** [comment]
The grammar is new(ish) and didn't exist when we wrote the parser. The
grammar also has historically had inaccuracies which we've filed bugs
about. This may not have been allowed when we wrote the parser or perhaps
it just wasn't document and wasn't present in the corpus of protos we parse.

Should be an easy fix, though.
