### ISSUE TITLE
Zero Long value deserialized to null

### ISSUE THREAD

**Issue by DHosseiny** [square/wire#929]
Hi
My problem is that server sends 0 for a long value but it deserialized to null. how can I change this behavior?(except with Wire.get()) should I change .proto file?

version: wire 3.0.0 alpha1
platform: android

**Comment by Egorand** [comment]
Make sure the client and the server use the same schema. The value being deserialized to null indicates that it was missing on the wire, which means the server either didn't send it, or sent it with a different tag.

**Comment by DHosseiny** [comment]
I used protobuf-java and wire for an Api that returns a List to check results and discovered that:
protobuf-java converted result: <ByteString@2671f7d size=0> (Empty ByteString)
wire  converted result: null
I am sure server not send null but empty list.

**Comment by DHosseiny** [comment]
My problem is the design decision, For example in proto3 a boolean is Boxed Boolean and default value is Null when it was missing on the wire. but it is different from [protobuf-java](https://github.com/protocolbuffers/protobuf/tree/master/java) and this is not usefull. because on serverside developer initiates a class that for example has a boolean that is not changed and is false by default but when he/she desirializes and sends it, it will change to null on clientside. it's a little weird at least in java when default value for boolean is false.

**Comment by Egorand** [comment]
Looks like your server talks proto3 (missing field is assigned a default value), whereas Wire only supports proto2 (missing optional field is assigned a null value), hence the semantics is different.

**Comment by DHosseiny** [comment]
Sorry maybe it is a misunderstanding by me. Don't Wire 3 supports proto3?

**Comment by Egorand** [comment]
No

**Comment by DHosseiny** [comment]
Oops so let's close it.
