### ISSUE TITLE
Fix gRPC APIs

### ISSUE THREAD

**Issue by oldergod** [square/wire#964]
```kotlin
suspend fun foo(a: A) : B

fun foo(a: A) : ReceiveChannel<B>

fun foo() : Pair<SendChannel<A>, Deferred<B>>

fun foo() : Pair<SendChannel<A>, ReceiveChannel<B>>
```

- [ ] backpressure test
- [x] more tests

**Comment by swankjesse** [comment]
![IMAG0519](https://user-images.githubusercontent.com/133019/57646514-c3a9c600-758e-11e9-8ef6-02aa9e8bac1b.jpg)

**Comment by swankjesse** [comment]
![IMAG0520](https://user-images.githubusercontent.com/133019/57646558-dae8b380-758e-11e9-83bb-c1f95d49a4b7.jpg)

**Comment by JakeWharton** [comment]
Glad to see that `suspend` hack gone.

**Comment by Egorand** [comment]
@oldergod done?

**Comment by oldergod** [comment]
Not yet. Will check this week and let you know.

**Comment by swankjesse** [comment]
Needs a fix for blocking APIs. We’re returning channels when they should instead be parameters.
